### ISSUE TITLE
Error: SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by born2net** [angular/angular-cli#1946]
> ## Please provide us with the following information:

In Windows 10 64 bit
Typescript 2.0.2
Node 4.4.3
installed via:  npm install -g angular-cli@webpack
latest ng version (installed now)
getting an error of

```
root|msweb>ng -v
Error while running script "C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\addon\ng2\models\config\config.ts":
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.require.extensions..ts (C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\lib\bootstrap-local.js:30:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module._load (C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\lib\bootstrap-local.js:55:22)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\addon\ng2\models\config.ts:7:16)
    at Module._compile (module.js:409:26)
Error while running script "C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\addon\ng2\models\config.ts":
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.require.extensions..ts (C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\lib\bootstrap-local.js:30:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module._load (C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\lib\bootstrap-local.js:55:22)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\addon\ng2\models\config.ts:7:16)
    at Module._compile (module.js:409:26)
C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\addon\ng2\models\config\config.ts:23
        this._config = new (schema_class_factory_1.SchemaClassFactory(schema))(configJson, ...fallbacks);
                                                                                           ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.require.extensions..ts (C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\lib\bootstrap-local.js:30:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module._load (C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\lib\bootstrap-local.js:55:22)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\addon\ng2\models\config.ts:7:16)
    at Module._compile (module.js:409:26)
```

**Comment by danimalia** [comment]
I am also getting this on OSX El Cap for all ng commands.

**Comment by wjke** [comment]
need node version 6.x

**Comment by born2net** [comment]
really? in the requirements shows 4.x

**Comment by wjke** [comment]
yes and need Typescript 2.0.0

**Comment by born2net** [comment]
ok with node 6 getting diff error:

```
root|msweb>tsc -v
Version 2.0.2
root|msweb>node -v
v6.5.0
root|msweb>ng
Error while running script "C:\Users\root\AppData\Roaming\npm\node_modules\angular-cli\addon\ng2\commands\serve.ts":
Error: Cannot find module 'portfinder'
    at Function.Module._resolveFilename (module.js:455:15)
```

**Comment by majew7** [comment]
Upgrading NodeJS from `v5.10.1` --> `v6.9.5` fixed the issue for me on OSX (El Capitan v10.11.6).  This wasn't expected to be necessary, as https://angular.io/docs/ts/latest/cli-quickstart.html suggests that NodeJS v4.x.x is fine.

**Comment by netdotter787** [comment]
Same issue in Ubuntu 16.04
$ ng new first-app
/home/abin/.nvm/v4.4.5/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-class-factory.js:34
            result.push(...indices);
                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/abin/.nvm/v4.4.5/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/index.js:3:30)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by ErikMj69** [comment]
It's not working on node v5.7.0 too, I had to upgrade it to 6.10.2

**Comment by yapro** [comment]
./nodejs/bin/node -v
v6.11.0

./node_modules/angular-cli/bin/ng new starsite-js
/home/lebnik/work/node_modules/@ngtools/json-schema/src/schema-class-factory.js:34
            result.push(...indices);
                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/lebnik/work/node_modules/@ngtools/json-schema/src/index.js:3:30)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
