### ISSUE TITLE
v15 "ng generate application" command in existing angular 15 appliction generates test.ts that is invalid

### ISSUE THREAD

**Issue by feodorar** [angular/angular-cli#24352]
### Command

generate

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v14

### Description

Angular v15 eliminates the need for a test.ts file. When doing the migration from 14 to 15, certain code blocks were removed from the test.ts files but the files are still there. Everything was working fine.
Then I wanted to add a new app to my monorepo with "ng generate application new-app" and it created a test.ts file that contained the code blocks that were eliminated during the migration from all other test.ts files. 
When running "ng test new-app" I get errors because of that.

Here you can see which code blocks I'm talking about:
![grafik](https://user-images.githubusercontent.com/60470513/204842272-03a3551a-26b7-444f-8674-725b263d0f58.png)

And here is the stack trace from "ng test new-app":

`Chrome Headless 107.0.5304.121 (Mac OS 10.15.7) ERROR
  An error was thrown in afterAll
  Uncaught TypeError: __webpack_require__(...).context is not a function
  TypeError: __webpack_require__(...).context is not a function
      at Object.377 (http://localhost:9876/_karma_webpack_/webpack:/projects/new-app/src/test.ts:24:25)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at __webpack_exec__ (http://localhost:9876/_karma_webpack_/main.js:12012:48)
      at http://localhost:9876/_karma_webpack_/main.js:12013:54
      at Function.__webpack_require__.O (http://localhost:9876/_karma_webpack_/webpack:/webpack/runtime/chunk loaded:23:1)
      at http://localhost:9876/_karma_webpack_/main.js:12014:56
      at webpackJsonpCallback (http://localhost:9876/_karma_webpack_/webpack:/webpack/runtime/jsonp chunk loading:34:1)
      at http://localhost:9876/_karma_webpack_/main.js:1:65
Chrome Headless 107.0.5304.121 (Mac OS 10.15.7): Executed 0 of 0 ERROR (0 secs / 0 secs)
Chrome Headless 107.0.5304.121 (Mac OS 10.15.7) ERROR
  An error was thrown in afterAll
  Uncaught TypeError: __webpack_require__(...).context is not a function
  TypeError: __webpack_require__(...).context is not a function
      at Object.377 (http://localhost:9876/_karma_webpack_/webpack:/projects/new-app/src/test.ts:24:25)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at __webpack_exec__ (http://localhost:9876/_karma_webpack_/main.js:12012:48)
      at http://localhost:9876/_karma_webpack_/main.js:12013:54
      at Function.__webpack_require__.O (http://localhost:9876/_karma_webpack_/webpack:/webpack/runtime/chunk loaded:23:1)
      at http://localhost:9876/_karma_webpack_/main.js:12014:56
      at webpackJsonpCallback (http://localhost:9876/_karma_webpack_/webpack:/webpack/runtime/jsonp chunk loading:34:1)
Chrome Headless 107.0.5304.121 (Mac OS 10.15.7): Executed 0 of 0 ERROR (0.006 secs / 0 secs)`

### Minimal Reproduction

on a angular v14 repo with multi-project setup, run:
ng update @angular/core@15 @angular/cli@15

then run "ng generate application new-app"

then run "ng test new-app"

### Your Environment

```text
Angular CLI: 15.0.1
Node: 16.13.0
Package Manager: npm 8.19.3
OS: darwin x64

Angular: 15.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   15.0.1
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.2.10
@angular/cdk                    15.0.0
@angular/material               15.0.0
@schematics/angular             14.2.10
ng-packagr                      15.0.1
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by alan-agius4** [comment]
Looks like something is pulling an old version of `@schematics/angular`. 


Can you run `npm ls @schematics/angular`?

**Comment by tbertran** [comment]
I'm getting the same error when running `ng test` after upgrading Angular to 15.0.2:

````
> ng test --karma-config projects/my-app-core/karma.conf.dev.js

⠋ Generating browser application bundles (phase: setup)...    TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browerslist configuration. For more information, see https://angular.io/guide/build#configuring-browser-compatibility
✔ Browser application bundle generation complete.
30 11 2022 13:04:39.405:WARN [karma]: No captured browser, open http://localhost:9876/
30 11 2022 13:04:39.418:INFO [karma-server]: Karma v6.4.1 server started at http://localhost:9876/
30 11 2022 13:04:39.418:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
30 11 2022 13:04:39.421:INFO [launcher]: Starting browser Chrome
30 11 2022 13:04:40.065:INFO [Chrome 107.0.0.0 (Windows 10)]: Connected on socket 2gZecspicWrNDZgWAAAB with id 48055424
Chrome 107.0.0.0 (Windows 10) ERROR                                                                                                                                                                             
  An error was thrown in afterAll
  Uncaught TypeError: __webpack_require__(...).context is not a function
  TypeError: __webpack_require__(...).context is not a function
      at Module.67568 (http://localhost:9876/_karma_webpack_/webpack:/projects/my-app-core/src/test.ts:26:25)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at __webpack_exec__ (http://localhost:9876/_karma_webpack_/main.js:208579:48)
      at http://localhost:9876/_karma_webpack_/main.js:208580:54
      at Function.__webpack_require__.O (http://localhost:9876/_karma_webpack_/webpack:/webpack/runtime/chunk loaded:23:1)
      at http://localhost:9876/_karma_webpack_/main.js:208581:56
      at webpackJsonpCallback (http://localhost:9876/_karma_webpack_/webpack:/webpack/runtime/jsonp chunk loading:34:1)
      at http://localhost:9876/_karma_webpack_/main.js:1:75
Chrome 107.0.0.0 (Windows 10): Executed 0 of 0 ERROR (0 secs / 0 secs)
Chrome 107.0.0.0 (Windows 10) ERROR
  An error was thrown in afterAll
  Uncaught TypeError: __webpack_require__(...).context is not a function
  An error was thrown in afterAll
  Uncaught TypeError: __webpack_require__(...).context is not a function
  TypeError: __webpack_require__(...).context is not a function
      at Module.67568 (http://localhost:9876/_karma_webpack_/webpack:/projects/my-app-core/src/test.ts:26:25)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at __webpack_exec__ (http://localhost:9876/_karma_webpack_/main.js:208577:48)
      at http://localhost:9876/_karma_webpack_/main.js:208578:54
      at Function.__webpack_require__.O (http://localhost:9876/_karma_webpack_/webpack:/webpack/runtime/chunk loaded:23:1)
      at http://localhost:9876/_karma_webpack_/main.js:208579:56
      at webpackJsonpCallback (http://localhost:9876/_karma_webpack_/webpack:/webpack/runtime/jsonp chunk loading:34:1)
````

````
Angular CLI: 15.0.2
Node: 18.10.0
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 15.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.2
@angular-devkit/build-angular   15.0.2
@angular-devkit/core            15.0.2
@angular-devkit/schematics      15.0.2
@angular/cdk                    15.0.0
@angular/cli                    15.0.2
@schematics/angular             15.0.2
ng-packagr                      15.0.1
rxjs                            7.5.7
typescript                      4.8.4
 ````

**Comment by alan-agius4** [comment]
@tbertran see https://github.com/angular/angular-cli/issues/24287

**Comment by feodorar** [comment]
> 

The result of "npm ls @schematics/angular" is this:

[...]
├─┬ @angular/cli@15.0.1
│ └── @schematics/angular@15.0.1
├─┬ @cypress/schematic@2.3.0
│ └── @schematics/angular@14.2.10
└─┬ ngx-build-plus@15.0.0
  └── @schematics/angular@15.0.1

Looks like cypress might be contributing to this issue?!

**Comment by alan-agius4** [comment]
Yes that is correct.

**Comment by alan-agius4** [comment]
Hi @feodorar, I am unable to replicate this issue using the same modules layout. Is it possible to provide a reproduction? Thanks.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
