### ISSUE TITLE
Module @angular-cli/ast-tools not found

### ISSUE THREAD

**Issue by carlosvalle** [angular/angular-cli#1882]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
**angular-cli@1.0.0-beta.11-webpack.3** 
node 6.4.0

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
run `ng new project`

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.
It seems that this npm package has not been published yet

> ---------------------------------------------------------------

**Comment by billdwhite** [comment]
Same here

**Comment by Yonet** [comment]
Same problem here. When I list my global node modules, I do get a peer dependency errors as well.

npm list -g -depth=0
/usr/local/lib
├── angular-cli@1.0.0-beta.11-webpack.3
├── grunt@1.0.1
├── gulp@3.9.1
├── mongo@0.1.0
├── node-sass@3.8.0
├── npm@3.10.3
├── protractor@4.0.4
├── rimraf@2.5.4
├── ts-node@1.3.0
├── typescript@2.0.0
└── typings@1.3.3

npm ERR! peer dep missing: rxjs@5.0.0-beta.6, required by @angular/core@2.0.0-rc.5
npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/compiler-cli@0.5.0
npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
npm ERR! peer dep missing: webpack@1.x.x || 2.x.x, required by string-replace-loader@1.0.3
npm ERR! peer dep missing: @angular/platform-server@^2.0.0-rc.5, required by @angular/compiler-cli@0.5.0
npm ERR! peer dep missing: zone.js@^0.6.6, required by @angular/core@2.0.0-rc.5
npm ERR! peer dep missing: tslint@^3.0.0, required by tslint-loader@2.1.5
npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
npm ERR! peer dep missing: typescript@^1.8.0 || ^1.9.0-dev, required by tsickle@0.1.6


Thanks!

**Comment by sculove** [comment]
+1

**Comment by lindsaymarkward** [comment]
I get this running `ng serve` after upgrading to the beta.3.
```
npm list angular-cli                      

├─┬ angular-cli@1.0.0-beta.11-webpack.3 
│ ├── UNMET PEER DEPENDENCY @angular/platform-server@^2.0.0-rc.5
│ └── UNMET PEER DEPENDENCY webpack@2.1.0-beta.21
└── UNMET PEER DEPENDENCY typescript@2.0.0

npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/compiler-cli@0.5.0
npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
npm ERR! peer dep missing: webpack@1.x.x || 2.x.x, required by string-replace-loader@1.0.3
npm ERR! peer dep missing: @angular/platform-server@^2.0.0-rc.5, required by @angular/compiler-cli@0.5.0
```

**Comment by rsnj** [comment]
Just ran: ```npm install -g angular-cli@webpack```

and now I get several errors whenever I run any ng command
```
$ ng --version
Error while running script "/usr/local/lib/node_modules/angular-cli/addon/ng2/utilities/ast-utils.ts":
Error: Cannot find module '@angular-cli/ast-tools'
```

**Comment by hansl** [comment]
I forgot to publish the `ast-tools` package. This should be fixed soon.

**Comment by ReneVallecillo** [comment]
Ok that was fast

**Comment by phmello** [comment]
@hansl thanks for you quick response, I think is worth notice that during the installation Im getting the message:
[execSync v1.0.2]
Native code compile failed!!
according to [this](https://github.com/cri5ti/grunt-shell-spawn/pull/35), the dependency should be dropped in favor of
sync-exec as execSync is no longer maintained.

cheers

**Comment by carlosvalle** [comment]
still @angular-cli/ast-tools not found - anyone else also having the same issue after upgrading to .4?

**Comment by phmello** [comment]
after upgrading to .5, same error

**Comment by lindsaymarkward** [comment]
https://gitter.im/angular/angular-cli - @hansl says it's coming... He's working on it as we 'speak'.

**Comment by hansl** [comment]
This is fixed with the latest webpack (8) release. Just upgrade to the latest webpack. Sorry for the problems.

Cheers!

**Comment by ReneVallecillo** [comment]
Now working on node 6.5

Just had to install again.

**Comment by beliyu** [comment]
again with 
"node@6.9.1",
"angular-cli@1.0.0-beta.19-2",
"@angular-cli/ast-tools@1.0.1"

**Comment by nukuuk** [comment]
after upgrading to angular-cli@1.0.0-beta.19, am getting same error after "ng new my-project"
am using:  node@6.9.1, npm@3.10.8, windows 10/64bit

> Cannot find module '@angular-cli/ast-tools'
Error: Cannot find module '@angular-cli/ast-tools'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\utilities\ast-utils.js:4:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\models\find-lazy-modules.js:7:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\models\webpack-build-typescript.js:4:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\models\webpack-config.js:2:34)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\tasks\build-webpack.js:6:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\commands\build.js:3:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Class.includedCommands (C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\addon\index.js:21:16)
    at C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\node_modules\angular-cli\lib\models\project.js:392:61
    at Array.forEach (native)
    at Project.addonCommands (C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\node_modules\angular-cli\lib\models\project.js:391:15)
    at Project.eachAddonCommand (C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\node_modules\angular-cli\lib\models\project.js:426:30)
    at module.exports (C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\node_modules\angular-cli\lib\cli\lookup-command.js:33:13)
    at CLI.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\node_modules\angular-cli\lib\cli\cli.js:34:26)
    at tryCatch (C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:521:7)
    at flush (C:\Users\User\AppData\Roaming\npm\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by tallkid24** [comment]
Getting the same with beta-18. It was working earlier today.

**Comment by sdeuvarow** [comment]
same with beta-17 and beta-18

**Comment by totemusik** [comment]
Same for me. 
Worked perfect yesterday, but now trying to set up a new project I do get errors

**Comment by roelver** [comment]
Same for me using beta-19-2.

**Comment by MiguelGL** [comment]
Same here, `angular-cli@1.0.0-beta.19-2` (via npm install -g angular-cli, had a previous cli version installed).

`node --version` => `v7.0.0`
`npm --version` => `3.10.8`

Using nvm. 

```
miguelgl@mgl-macbook:~$ which ng
/Users/miguelgl/.nvm/versions/node/v7.0.0/bin/ng
```

```
miguelgl@mgl-macbook:~$ ll `which ng`
lrwxr-xr-x  1 miguelgl  staff    38B Oct 28 22:33 /Users/miguelgl/.nvm/versions/node/v7.0.0/bin/ng -> ../lib/node_modules/angular-cli/bin/ng
```

```
miguelgl@mgl-macbook:~$ ll /Users/miguelgl/.nvm/versions/node/v7.0.0/lib/node_modules/
total 0
drwxr-xr-x  18 miguelgl  staff   612B Oct 28 22:33 angular-cli
drwxr-xr-x  25 miguelgl  staff   850B Oct 25 15:16 npm
```

**Comment by pkraus109** [comment]
Same issue.

**Comment by ayubali** [comment]
i spent my hole day and getting same error.

**Comment by MerlinMartel** [comment]
same here. tried to install an older version on angular-cli (beta-16) and I have the same issue now... I'm stuck...

**Comment by sdeuvarow** [comment]
It's fixed not. Run npm install ... it should work now.

**Comment by fredricadell** [comment]
It works.. I had to do
npm uninstall -g angular-cli 
and 
npm install -g angular-cli@latest 
then it worked fine.

**Comment by nadeemse** [comment]
Anyone got it fixed, I am getting the same issue.

Cannot find module '@angular-cli/ast-tools'
Error: Cannot find module '@angular-cli/ast-tools'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/utilities/ast-utils.js:4:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/models/find-lazy-modules.js:7:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/models/webpack-build-typescript.js:4:27)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/models/webpack-config.js:2:34)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/tasks/build-webpack.js:6:24)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/commands/build.js:3:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Class.module.exports.includedCommands (/usr/local/lib/node_modules/angular-cli/addon/index.js:21:16)
    at /usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/models/project.js:392:61
    at Array.forEach (native)
    at Project.addonCommands (/usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/models/project.js:391:15)
    at Project.eachAddonCommand (/usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/models/project.js:426:30)
    at module.exports (/usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/cli/cli.js:34:26)
    at tryCatch (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by daddyschmack** [comment]
i'm getting the issue also, running mac sierra, everthing was running fine, then updated 2 days ago.  Now I reinstalled from scratch, and this is what happens:
@angular/platform-server@2.1.2 requires a peer of @angular/platform-browser@2.1.2 but none was installed.
user-MacBook-Pro:faclient username$ ng version
-bash: ng: command not found

user-MacBook-Pro:faclient username$ node --version
v6.4.0

**Comment by natificent** [comment]
Is it just me or do things just absolutely break on a regular basis for no apparent reason.

**Comment by daddyschmack** [comment]
I haven't noticed that.  This project has been very helpful to me and i appreciate all the work done on it.  Besides, it's not like we are paying for it so it's my opinion that we should be appreciative of the work being done for us.

**Comment by filipesilva** [comment]
We have an issue with the latest release a few days ago, more information can be found in https://github.com/angular/angular-cli/issues/2940.

**Comment by bertolo1988** [comment]
+1
