### ISSUE TITLE
Cannot find module 'rxjs/operators/map' when running any ng command

### ISSUE THREAD

**Issue by csaldan** [angular/angular-cli#9190]
Getting the following error when trying to run any ng commands.

`ng --version 
module.js:471
    throw err;
    ^

Error: Cannot find module 'rxjs/operators/map'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\work\fs\test\test-fspg\node_modules\@angular-devkit\core\src\json\schema\registry.js:15:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)`

My project was using cli version 1.4.5, Started happening after a fresh npm install Tried with latest 1.6.4 and got the same error. It was working fine last week.

**Comment by chandramuralis** [comment]
I got the same issue too

**Comment by StolenOrange** [comment]
me too

**Comment by mousedown** [comment]
yep, me too.

**Comment by cksekhar** [comment]
Me too. Not sure how can this happen after locking the version on package.json

**Comment by monicareddy30** [comment]
I tried installing new version of rxjs and it worked for me
npm install --save rxjs@5.5.2

**Comment by mousedown** [comment]
The Alpha fails, as does 5.5.6

I've tried @5.5.5 and that resolves.

npm install rxjs@5.5.5

**Comment by chandramuralis** [comment]
After updating rxjs package from 5.4.3 to 5.5.6 fixed the issue.

**Comment by csaldan** [comment]
Noticed a related bug https://github.com/angular/material2/issues/3552

**Comment by csaldan** [comment]
Related bug https://github.com/angular/devkit/issues/380

**Comment by mdarefull** [comment]
Same for me too, the project.json that I had contained:
"rxjs": "5.4.2",
Changing it to the version included with ng new scaffolding solved the problem:
"rxjs": "^5.5.2",

**Comment by sacgrover** [comment]
Remove node_module folder and run following command: npm install

**Comment by Brocco** [comment]
I am closing this issue as it will be tracked via angular/devkit#380.

**Comment by ppatil27** [comment]
As of now to get rid of this issue, please run npm install rxjs@5.5.6 globally on system after npm install

**Comment by Ronniep7** [comment]
npm install --save rxjs@5.6.0

**Comment by lovesinghchahal** [comment]
npm install rxjs@6 rxjs-compat@6 --save

**Comment by huynhquocbao92** [comment]
@lovesinghchahal 
Thanks you.
I have same error 
> **Cannot find module 'rxjs-compat/Observable'** 
> 

And after run install above, server build success :D

**Comment by pfiterman** [comment]
Thanks @lovesinghchahal  and @huynhquocbao92 
I have same error too

just before install rxjs and rxjs-compat packages (current version 6.2.0)
npm install rxjs@6.2.0 rxjs-compat@6.2.0 --save  

after server buil success

**Comment by kishor0412** [comment]
My issue resolved , after running below command,
**npm install rxjs@6.2.0 rxjs-compat@6.2.0 --save**

Thanks for saving my time.

**Comment by FranciscoChile** [comment]
I had the same problem after install primeicons (npm install primeicons), I resolve it with re-installation rxjs and rxjs-compat, I come late, sorry

**Comment by nuwansomasiri8** [comment]
npm install --save rxjs@5.6.0 will fix the issue.. It worked for me

**Comment by ehlilier** [comment]
I used yarn to reinstall. It worked.
