### ISSUE TITLE
Using paths inside tsconfig causing error on JIT: field 'browser' doesn't contain a valid alias configuration

### ISSUE THREAD

**Issue by PierreDuc** [angular/angular-cli#7341]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```
While using the `paths` object inside `tsconfig.json`, module resolution doesn't seem to work anymore since the latest release. It did work on `1.3.0-rc.5`. Ahead of Time does work. This seems to happen when you reference the `src` folder or anything lower down the tree

### Versions.
@angular/cli: 1.3.0
node: 8.2.1
os: win32 x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.3.0
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3

### Repro steps.
0. Upgrade cli to version `1.3.0`, this used to work in `1.3.0-rc.5` and before
1. Create a project
2. Set a paths property to `"@root/*": ["./*"]` inside `tsconfig.app..json`
3. Change the import of `AppComponent` inside `AppModule` to `import { AppComponent } from '@root/app/app.component';`
4. Run `ng serve`
5. Run `ng serve --aot` to see that this does work

### The log given by the failure.
```
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve '@root/app/app.component' in 'C:\Projects\angular-cli-v130-bug\src\app'
resolve '@root/app/app.component' in 'C:\Projects\angular-cli-v130-bug\src\app'
  Parsed request is a module
  using description file: C:\Projects\angular-cli-v130-bug\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Projects\angular-cli-v130-bug\package.json (relative path: ./src/app)
    resolve as module
      C:\Projects\angular-cli-v130-bug\src\app\node_modules doesn't exist or is not a directory
      C:\Projects\angular-cli-v130-bug\src\node_modules doesn't exist or is not a directory
      C:\Projects\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\Projects\angular-cli-v130-bug\node_modules
        using description file: C:\Projects\angular-cli-v130-bug\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\Projects\angular-cli-v130-bug\package.json (relative path: ./node_modules)
          using description file: C:\Projects\angular-cli-v130-bug\package.json (relative path: ./node_modules/@root/app/app.component)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\angular-cli-v130-bug\node_modules\@root\app\app.component doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\angular-cli-v130-bug\node_modules\@root\app\app.component.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\angular-cli-v130-bug\node_modules\@root\app\app.component.js doesn't exist
            as directory
              C:\Projects\angular-cli-v130-bug\node_modules\@root\app\app.component doesn't exist
```

### Desired functionality.
I would like to see no errors, obviously ;)

### Mention any other details that might be useful.
Created a [repo](https://github.com/PierreDuc/angular-cli-v130-bug) showing this issue

**Comment by karptonite** [comment]
My guess is that this is related to this commit:
https://github.com/angular/angular-cli/commit/cb0cc0886506d8243c0ed8fcba6a948ddb5adb25
It was a last minute addition, and seems to have made it into 1.3, despite a commit message that says "This is a feature because we do not want it in 1.3.0".

**Comment by strizzaflex** [comment]
I'm getting the same errors in my application. I followed the recreate steps and and I get the error without the aot flag so that confirms for me that it is not my app setup but something that changed in 1.3

**Comment by hieuxlu** [comment]
@PierreDuc et al: Fix the `@angular/cli` version in package.json to `1.3.0-rc.5` resolves this issue for me. This only occurs in `^1.3.0`.
@filipesilva FYI. Maybe the reason is what @karptonite has said.

**Comment by beeman** [comment]
My project does not build anymore after upgrading to 1.3.0 with this same error:

https://travis-ci.org/ngx-plus/ngx-forms/builds/263376710#L3634
https://github.com/ngx-plus/ngx-forms/commit/e7eefe0054ff7509c72ef99d0b0d6314230f8b1e

**Comment by beeman** [comment]
@tacman for me downgrading the local cli version is the workaround

**Comment by karptonite** [comment]
@hansl just bringing this to your attention, since you are the author of the PR that may be related to this issue. See: https://github.com/angular/angular-cli/issues/7341#issuecomment-321636356

**Comment by bastienJS** [comment]
I get the same error:    Field 'browser' doesn't contain a valid alias configuration

with v1.3.0 but I do not use AOT or paths in tsconfig.json!

**Comment by PierreDuc** [comment]
@bastienJS check if you have an import from `@angular/src/.../...`, this can also cause this error. Make sure to import only from `@angular/core` etc. Nothing from `src`

**Comment by dynameis** [comment]
I get the same error,
and I checked my code, nothing import from @anguar/src...  only import from @angular/core and @angular/core/testing

**Comment by karptonite** [comment]
I can no longer confirm this bug. What I thought was related to the `paths` config was actually related to having some import statements that explicitly included `.ts` in the path name. When I removed the `.ts` at the end of the import path name, the imports worked fine, as before.

**Comment by ismcagdas** [comment]
I have the same problem as @PierreDuc described. I have tried v1.3.1 and 1.4.0-beta.2, both resulted the same error message.
Can anyone from the team respond to this issue ?

Thanks.

**Comment by GarryBrown** [comment]
The same error  (project https://github.com/ngrx/platform.git works with another version cli) 
@angular/cli: 1.3.1
node: 6.11.2
os: win32 x64
@angular/cdk: 2.0.0-beta.8
@angular/animations: 4.3.5
@angular/cli: 1.3.1
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/compiler-cli: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/platform-server: 4.3.5
@angular/router: 4.3.5

**Comment by fachammer** [comment]
Having the same issue with version 1.3.1: 
`ERROR in ./src/main/web/app/app.module.ts`
`Module not found: Error: Can't resolve '@module/api'`

and 

`Field 'browser' doesn't contain a valid alias configuration`

where `@module/api` ist defined in `tsconfig.app.json`

**Comment by filipesilva** [comment]
@hansl can you take a look?

**Comment by nekkon** [comment]
@hansl @filipesilva @PierreDuc I had the same issue with the [library repo](https://github.com/nekkon/angular-cli-library) and managed to find a workaround. Not sure what is causing this and didn't have much time to look into it. Maybe my workaround helps you out. I have updated @PierreDuc repo ( there are pending pull requests ) with the solution. Now ng serve and aot works properly. 

My main changes were to change tsconfig.json to:

````{
  "compileOnSave": false,
  "compilerOptions": {
    "paths":{
      "@app/*": ["src/app/*"]
    },
    "baseUrl": ".",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}

and tsconfig.app.json to:

````{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "paths":{
      "@app/*": ["app/*"]
    },
    "outDir": "../out-tsc/app",
    "baseUrl": ".",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}

**Comment by PierreDuc** [comment]
@nekkon I'm sorry, I can see I did a boo boo while commiting the repo. Didn't actually commit the changes needed to show the error. I've updated my repo now

**Comment by nekkon** [comment]
@PierreDuc Yeah I noticed it. I added those changes based on your description (Repro steps).

**Comment by hieuxlu** [comment]
@PierreDuc @nekkon  It works fine when the path directory is located inside project root. When you move it outside of `\src` and references in `paths` as `..\modules`, for example, the error still occurs.

**Comment by PierreDuc** [comment]
@hieuxlu My guess is that there has been a dependency update. The error indeed did not occur anymore in my test repo. I've now changed the `paths` to reference the `src` folder from `tsconfig.app.json` and it's back. I've updated the repo and the initial issue

**Comment by dherges** [comment]
Error still persists with `1.3.2` in dherges/ng-packaged@e4f5b3a

Build error started when upgrading from `1.3.0-rc.3` to `1.3.0` in dherges/ng-packaged@3c983ae

[History of commits w/ build success anf ailures](https://github.com/dherges/ng-packaged/commits/master)


Updating to `1.4.0-rc.0` does not solve the error in dherges/ng-packaged#29

#### Error message

```
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve '@my/lib' in '/home/ubuntu/ng-packaged/src/app'
resolve '@my/lib' in '/home/ubuntu/ng-packaged/src/app'
  Parsed request is a module
```

#### Configuration

tsconfig.app.json

```json
{
  "extends": "../tsconfig.json",
  "angularCompilerOptions": {
    "paths": {
      "@my/lib": [ "../dist/my-lib" ]
    }
  },
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "baseUrl": "",
    "types": [],
    "paths": {
      "@my/lib": [ "../dist/my-lib" ]
    }
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

.angular-cli.json


```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "ng-packaged"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist/app",
      /* .. */
    }
  ]
}
```

**Comment by GerbenRampaart** [comment]
I have this error too. cli 1.3.2

**Comment by playground** [comment]
I'm still getting this error in 1.4.0-rc.2.  Will this be fixed soon?

**Comment by playground** [comment]
Same errors after upgraded to 1.4.0...
ng build works fine.

it's failing for "ng build -prod", it's not seeing any of my share modules.

ERROR in /Users/angular/proj/src/$$_gendir/app/app.module.ngfactory.ts (38,22): Cannot find module 'module-one'.
ERROR in /Users/angular/proj/src/$$_gendir/app/app.module.ngfactory.ts (57,22): Cannot find module 'module-two'.

**Comment by BlindSleuth** [comment]
Same here - 1.4.0

**Comment by playground** [comment]
I found the answer, it turns out that flatModuleId needs to be set to @scope such as "flatModuleId": "@myscope/my-module.  Thanks to @jdjuan[ #75](https://github.com/jvandemo/generator-angular2-library/issues/75)

**Comment by nishesj** [comment]
Was working until 1.3.0-rc.5. 
"paths" was used for aliasing and overwriting some 3rd party imports but it no longer works

**Comment by hieuxlu** [comment]
Guys, I confirm this have been fixed and merged to 1.3.2 and 1.4.0. Please update & double-check your @angular/cli version with `ng -v` and open another issue if it still persists in your case. This issue has been closed since.

**Comment by dherges** [comment]
@hieuxlu It is not. There are use cases where the paths mapping is not resolved correctly.

**Comment by PierreDuc** [comment]
@dherges Try to create a repo where the mapping still doesn't work. Like I mentioned before, an import like `@angular/src/.../...` will trigger the same error, which is not a bug, but a wrong import

**Comment by nishesj** [comment]
I don't have a public repo but example where it was working but is broken now is 
if some third party script has:

` let a=require('**some-module**');`

 we could alias some-module in paths like 

`"paths": {
      "some-module": ["./different-import.ts"]
    }`

which was working until 1.3.0-rc.5. This now resolves the original **some-module** instead of the alias defined.

**Comment by dherges** [comment]
@PierreDuc 

Repro: https://github.com/dherges/ng-packaged/tree/146323597324337e435ad0f6d6a0fdad876603da

Commit history: https://github.com/dherges/ng-packaged/commits/146323597324337e435ad0f6d6a0fdad876603da

Started breaking in 1.3.0

It never turned back green again even w/ 1.3.2 as seen in Circle CI build 79: https://circleci.com/gh/dherges/ng-packaged/79?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Neither did it in Curcle CI build 92, when upgrading to 1.4.2-rc.2: https://circleci.com/gh/dherges/ng-packaged/93?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Eventually, I changed my configuration. By changing my configuration, the build no works again. Considering that it stopped working in the way it was being used before, there were regressions / breaking changes introduced to tsconfig paths mapping in Angular CLI.

**Comment by dherges** [comment]
Essentially [the same matter from 14 days ago](https://github.com/angular/angular-cli/issues/7341#issuecomment-324839657)

**Comment by hieuxlu** [comment]
@dherges You're correct. It seems like the fix did not cover resolving paths for commonjs module. For the mean time, you should either change reference to `require '../..dist/my-lib'` or change paths to `my-lib`, or downgrade the cli to `1.3.0-rc.5` or `1.2.x`.
@hansl You might want to have a look at this. The repro is not minimal, but clearly this issue only happens since 1.3.0.

**Comment by miguelramos** [comment]
After fighting some days to put an "emulated" type monorepo, i got working and compiling in AOT mode with paths mappings in the current version of the CLI.

So my approach have some config time. First, i'm using multi app support and let's start on angular-cli.json. For the test project, called playground and you can see on the screenshot bellow i've use two configs for the same project, this only to have different tsconfig.app.json for resolving ts path maps.

![image](https://user-images.githubusercontent.com/495720/30404756-fddc64c8-98df-11e7-8d97-449eeb761b4a.png)

![image](https://user-images.githubusercontent.com/495720/30405249-ab75d694-98e2-11e7-8bb9-da8589162afe.png)

I've a shared code on lib, and want to share between the multiple apps. On tsconfig.json in the root my config is like this:

# tsconfig.json

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "paths": {
      "@foursource/*": ["src/lib/*"],
      "@foursource/common": ["src/lib/common/public_api.ts"],
      "@foursource/core": ["src/lib/core/public_api.ts"],
      "@foursource/ui": ["src/lib/ui/public_api.ts"],
      "@foursource/ui/button": ["src/lib/ui/button/public_api.ts"]
    },

    "outDir": "./dist/out-tsc",
    "baseUrl": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "exclude": [
    "tmp"
  ]
}
```
 
Then inside the playground project i have two tsconfig for dev mode and for aot compilation.

# tsconfig.dev.json (DEV)

```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "paths": {
      "@foursource/common": ["../lib/common/public_api.ts"],
      "@foursource/core": ["../lib/core/public_api.ts"],
      "@foursource/ui": ["../lib/ui/public_api.ts"],
      "@foursource/ui/button": ["../lib/ui/button/public_api.ts"]
    },
    "outDir": "../../out-tsc/app",
    "baseUrl": "",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

# tsconfig.play.json (AOT)

```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "paths": {
      "@foursource/common": ["lib/common/public_api.ts"],
      "@foursource/core": ["lib/core/public_api.ts"],
      "@foursource/ui": ["lib/ui/public_api.ts"],
      "@foursource/ui/button": ["lib/ui/button/public_api.ts"]
    },
    "outDir": "../../out-tsc/app",
    "baseUrl": "",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

And for this to work package.json scripts have to done some things before compile it, special on AOT mode. For this i copy folder lib to inside the playground app and that's the action that is needed for resolve paths in path mapping.

# package.json

```
"ng": "node --max_old_space_size=8192 ./node_modules/.bin/ng",
"start:website": "npm run ng serve -- --app=website --aot=false --progress=true --verbose=true --port=3000 --host=www.foursource.dev --sourcemaps=true",
"start:platform": "npm run ng serve -- --app=platform --aot=false --progress=true --verbose=true --port=4000 --host=app.foursource.dev --sourcemaps=true",
"start:play": "npm run ng serve -- --app=playground-dev --aot=false --progress=true --verbose=true --port=5000 --host=www.playground.dev --sourcemaps=true",
"test:play": "ng test --app=playground",
"build": "ng build",
"build:play:aot": "cpr ./src/lib ./src/playground/lib -o && npm run ng build -- --app=playground --aot=true --target=production --environment=prod --sourcemaps=true --vendorChunk=true --output-hashing=all --progress=true  && rimraf ./src/playground/lib",
"test": "ng test",
"lint": "ng lint",
"e2e": "ng e2e"
```

As you can see on `start:play` i call playground-dev to have dev mode and on `build:play:aot` the playground for AOT.

With this configs, i have multi apps like website, b2b app, mobile and so on emulating monorepo, sharing code, components and styles on my company. 

An extensive temporary fix to use path maps of ts. Main value copy my shared lib to the project that i'm compiling.

Cheers.!!

**Comment by nekkon** [comment]
@miguelramos Hey, I noticed you have followed a similar path with me. I have an open source repo https://github.com/nekkon/angular-cli-library which follows a similar logic with yours.

**Comment by miguelramos** [comment]
@nekkon Nice! Thanks for the tip.

**Comment by miguelramos** [comment]
Related to the test error on karma i was able to fix it putting on tsconfig app related the lib as : `"lib": ["es2015", "dom"]`.

Bam! Everything rolling.

**Comment by penghuili** [comment]
I fixed this by removing
`
  "include": [
    "node_modules/@types"
  ]
`
from my tsconfig.json file.

By the way, i added the `"include"`, because i run into [Cannot find name 'expect'](https://github.com/TypeStrong/atom-typescript/issues/1125#issuecomment-273567402) error, but now after i removed it, this error doesn't show, wired.

**Comment by bluea** [comment]
I had this issue which was caused by the following in tsconfig.json:

    "paths": {
      "@angular/*": [
        "./node_modules/@angular/*"
      ]
    }

**Comment by Tahiche** [comment]
Similar to @miguelramos, in my case in tsconfig I had compilerOptions -> "target": "es2015", but compilerOptions -> lib: ["dom", "es2018"] 
This is for a project to be used as a library by other projects.
I kept getting all kinds of "Field ‘browser’ doesn’t contain a valid alias configuration" and module/blabla not found errors when trying production build (no errors on dev)
My very uneducated guess is that is there´s a discrenpancy between "target" and "lib" routes get screwed up. The "host" app is told to look for modules and classes in one place but they are placed / generated elsewhere. 
If this is the case error reporting is not helping at all. I don´t know if its possible, but you should be warned when compiling. It´s just really hard to figure this out when you´re told files are not found (again only in production build) when the files are there,
