### ISSUE TITLE
V1.7.0 Nested routing not working

### ISSUE THREAD

**Issue by kanji-keraliya** [angular/angular-cli#9651]
I updated latest @angular/cli@1.7.0 and now nested routing not work.I created two routing file like app-routing.module.ts and report-route.module.ts.

**report-route.module.ts** used in **app-routing.module.ts**.after updating to latest Angular CLI not working. and its working in V1.6.8

Error is Uncaught (in promise) TypeError: undefined is not a function

**Comment by gremi64** [comment]
Same here, our application was working in 1.6.8 yesterday and now in 1.7.0 we got

> Error: Uncaught (in promise): TypeError: __webpack_require__.e is not a function
> webpackAsyncContext@http://our_url.fr/main.bundle.js:538:21

**Comment by MattMorrisDev** [comment]
+1

This worked in 1.7.0-rc.0, but stops working in (and after) 1.7.0 (Kleene).

Full stack trace:
```
core.js:2086 ERROR Error: Uncaught (in promise): TypeError: undefined is not a function
TypeError: undefined is not a function
    at Array.map (<anonymous>)
    at webpackAsyncContext (eval at ./src/$$_lazy_route_resource lazy recursive (main.bundle.js:13), <anonymous>:10:34)
    at SystemJsNgModuleLoader.loadAndCompile (core.js:6756)
    at SystemJsNgModuleLoader.load (core.js:6740)
    at RouterConfigLoader.loadModuleFactory (router.js:4558)
    at RouterConfigLoader.load (router.js:4538)
    at MergeMapSubscriber.eval [as project] (router.js:2030)
    at MergeMapSubscriber._tryNext (mergeMap.js:128)
    at MergeMapSubscriber._next (mergeMap.js:118)
    at MergeMapSubscriber.Subscriber.next (Subscriber.js:92)
    at Array.map (<anonymous>)
    at webpackAsyncContext (eval at ./src/$$_lazy_route_resource lazy recursive (main.bundle.js:13), <anonymous>:10:34)
    at SystemJsNgModuleLoader.loadAndCompile (core.js:6756)
    at SystemJsNgModuleLoader.load (core.js:6740)
    at RouterConfigLoader.loadModuleFactory (router.js:4558)
    at RouterConfigLoader.load (router.js:4538)
    at MergeMapSubscriber.eval [as project] (router.js:2030)
    at MergeMapSubscriber._tryNext (mergeMap.js:128)
    at MergeMapSubscriber._next (mergeMap.js:118)
    at MergeMapSubscriber.Subscriber.next (Subscriber.js:92)
    at resolvePromise (zone.js:821)
    at resolvePromise (zone.js:785)
    at eval (zone.js:870)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4938)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:594)
```

Versions:
```
Angular CLI: 1.7.0
Node: 8.6.0
OS: darwin x64
Angular: 6.0.0-beta.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.0
@angular/cli: 1.7.0
@angular/material: 5.2.0
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.6.2
webpack-bundle-analyzer: 2.10.0
webpack: 3.11.0
```

**Comment by dewwwald** [comment]
I am having the exact same problem. From my debugging I found that it is because of `webpack 3.11.0`. That version of webpack removed support for `System.import` being called here:
https://github.com/angular/angular/blob/5.2.5/packages/core/src/linker/system_js_ng_module_factory_loader.ts#L67-L71

For now it might be best for us to roll back to the previous version of the angular cli.

**Comment by dewwwald** [comment]
I can also confirm that `angular/cli` version `1.6.8` works when building angular 5.2, however my modules are not being lazy loaded.

**Comment by marcincichocki** [comment]
Same in our case. Downgrading to 1.6.8 with flag -vc works

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by KellyR-STCU** [comment]
I think we are experiencing the same problem I get the same stack trace.

**Comment by KellyR-STCU** [comment]
I was able to make a minimal repro of this. Trying to figure out how to submit it.

**Comment by marcincichocki** [comment]
I've tried to reproduce it, without success, even. But @KellyR-STCU example made me realize that the problem is location of feature module.

When feature module is in `app` directory it works, but when it's below it fails.

*fails*
```
src/
  feature/
  app/
```

*works*
```
src/
  app/
    feature/
```

I have multiple apps, and so I moved some feature modules into libs(nx monorepo style) that are not in `src/app` directory, thus error I'm having. I hope this clarify the problem we are facing @filipesilva

**Comment by elvisfernandes** [comment]
For the record, I'm facing the same issue reported here.

**Comment by blackholegalaxy** [comment]
The same happens to us. We use sibbling modules: app and other imported modules at the same level:

```
src/
  app/
  otherModule/
```

Navigating from app to otherModule breaks on 1.7.0 and 1.7.1. Workaround to move otherModule into map is not possible in all projects.

**Comment by Herzenkin** [comment]
Latest CLI v. 1.7.1 - got the same problem.

> Uncaught (in promise): TypeError: undefined is not a function
TypeError: undefined is not a function
    at Array.map (<anonymous>)
    at webpackAsyncContext ($_lazy_route_resource lazy:19)
    at SystemJsNgModuleLoader.webpackJsonp../node_modules/@angular/core/esm5/core.js.SystemJsNgModuleLoader.loadAndCompile (core.js:6558)
    at SystemJsNgModuleLoader.webpackJsonp../node_modules/@angular/core/esm5/core.js.SystemJsNgModuleLoader.load (core.js:6542)
    at RouterConfigLoader.webpackJsonp../node_modules/@angular/router/esm5/router.js.RouterConfigLoader.loadModuleFactory (router.js:4543)
    at RouterConfigLoader.webpackJsonp../node_modules/@angular/router/esm5/router.js.RouterConfigLoader.load (router.js:4523)

**Comment by emanuelet** [comment]
I had to downgrade to 1.6.8 as well to solve the issue

**Comment by SirAjZellweger** [comment]
same here

**Comment by jfborie** [comment]
Same here

**Comment by macjohnny** [comment]
same here
this seems to a duplicate of https://github.com/angular/angular-cli/issues/9775

**Comment by MattMorrisDev** [comment]
I realized I forgot to remove the lazily loaded module from the imports of my AppModule. I removed that and upgraded to the latest beta (6.0.0-beta.5) and it seems to be fine now for me.

**Comment by piq9117** [comment]
same error. rolled back to `1.6.8` and its working.

**Comment by dewwwald** [comment]
@macjohnny this is actually the original as this thread has an earlier date.

**Comment by ddiebel** [comment]
same for me, moved from 1.7.3 to 1.6.8 and now it works.

**Comment by TobiasBreuer** [comment]
Same issue here with CLI 1.7.2. As it has been mentioned in #9775 compiling with --aot seems to fix the problem which is acceptable workaround in my case until its fixed. Really would like to avoid downgrading :wink:

**Comment by dewwwald** [comment]
I upgraded to 1.7.4, and that version is working.

**Comment by ashitosh31** [comment]
Downgrading to 1.6.8 worked for me as well!

**Comment by CDuPlooy** [comment]
1.7.4 also works with the --aot flag but not without.

**Comment by GeorgeKnap** [comment]
I experience the same error with `@angular/cli: 6.0.0`   dev build succees but runtime error ` Uncaught (in promise): TypeError: undefined is not a function`.

AOT works

**Comment by fuchien** [comment]
Same here, work with AOT

**Comment by GuerrillaCoder** [comment]
I have same issue.  My lazy loaded modules are under `app/` but `ng build --watch` does not work I get same error.  If I do `ng build --prod` then everything works fine but it makes development hard.  I am on cli version 6.0.8.

Anyone know how to fix?

**Comment by martin-g** [comment]
@GuerrillaCoder The workaround with AOT explained above works for everyone. Did you try it ?

**Comment by GuerrillaCoder** [comment]
Ahh sorry I missed it, yes that works.

**Comment by kufre-okon** [comment]
Same issue with angular/cli: 1.7.3, work with aot

**Comment by kevin192291** [comment]
I am working on this issue too. I posted a stackoverflow question about it, but as of now, have no answers:
[angular-load-routes](https://stackoverflow.com/questions/51270428/angular-load-routes-from-api-lazy-route-resource-lazy-recursive-error)
The part that I find most strange is that I have this working on stackblitz just fine: [Lazy Load Routes Dynamically](https://stackblitz.com/edit/angular-dynamic-components-and-routes)
But when I pull it local it fails. I was thinking that it has something to do with the tsconfig.app.json's baseUrl param, but I haven't found the answer yet. Maybe my working stackblitz project could help.

**Comment by hiepxanh** [comment]
@bluecaret  thank you. why the error just only warning that I import lazy module at app.module.ts is wrong?

**Comment by k80oshea** [comment]
I'm still getting that same error sadly, did try with `ng serve --aot` as well. I've messed around with it so many time that I'm losing hope - most solid error is that it can't reach my child routes (although occasionally it will give me the undefined error instead). 
```
Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'parent/child'
Error: Cannot match any routes. URL Segment: 'parent/child'
```
I'm clicking on a link to my child route while operating from the parent route when the error is thrown.
I'm on Angular 5.2 and CLI 1.7.4 - did try downgrading to 1.6.8 but met with same results.

**Comment by jfborie** [comment]
uninstall global and local cli, and reinstall and check that they are identical, check package-lock.json, check that you have the good typescript version. I had a problem a while back and resolve it like this.

**Comment by ashitosh31** [comment]
I would recommended to go for a specific version of cli with other third
party plugins which supports same version, for me 1.6.8 worked perfectly.

**Comment by k80oshea** [comment]
@jfborie @ashitosh31 thanks - it didn't seem to work right off the bat, but I think it helped after I restructured some more after following [this example](https://stackblitz.com/angular/lrgqmndjeag?file=src%2Fapp%2Fapp.module.ts) from the angular docs for my routing
