### ISSUE TITLE
Cannot find module '../../../../@angular/core'

### ISSUE THREAD

**Issue by keyiis** [angular/angular-cli#5961]
### Versions.
node 6.9
npm 3.10.9

### Repro steps.
After I update angular from 2.4 to 4.0,i compiler with @ngtools\webpack get below error:

### The log given by the failure.
```
[1m[31mERROR in D:/myapp/$$_gendir/node_modules/@angular/core/core.ngfactory.ts (1,1): Cannot find module '../../../../@angular/core'.
D:/myapp/$$_gendir/node_modules/@angular/core/core.ngfactory.ts (1,1): Property 'parent' does not exist on type 'ApplicationModuleInjector'.
```

### Mention any other details that might be useful.
package.json
```
"devDependencies": {
    "@angular/compiler-cli": "^4.0.1",
    "@angular/platform-server": "^4.0.1",
    "@ngtools/webpack": "^1.3.0",
    "@types/echarts": "0.0.5",
    "@types/file-saver": "0.0.0",
    "@types/serialport": "^4.0.8",
    "@types/socket.io-client": "^1.4.29",
    "angular2-template-loader": "^0.6.0",
    "awesome-typescript-loader": "^3.0.3",
    "babel-core": "^6.11.4",
    "babel-loader": "^6.2.4",
    "babel-polyfill": "^6.13.0",
    "babel-preset-latest": "^6.16.0",
    "compression-webpack-plugin": "^0.3.1",
    "copy-webpack-plugin": "^3.0.1",
    "css-loader": "^0.23.1",
    "del": "^2.2.1",
    "electron": "^1.4.15",
    "electron-packager": "8.5.1",
    "electron-rebuild": "^1.5.7",
    "extract-text-webpack-plugin": "^2.0.0-beta.4",
    "file-loader": "^0.8.5",
    "gulp": "^3.9.1",
    "gulp-babel": "^6.1.2",
    "gulp-clean": "^0.3.2",
    "gulp-rollup": "^2.10.0",
    "gulp-sequence": "^0.4.6",
    "gulp-uglify": "^2.0.0",
    "gulp-util": "^3.0.7",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.16.1",
    "json-loader": "^0.5.4",
    "lodash": "^4.13.1",
    "ncp": "^2.0.0",
    "nw-builder": "^3.2.0",
    "nw-gyp": "^3.4.0",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.2",
    "source-map-loader": "^0.1.5",
    "style-loader": "^0.13.1",
    "through2": "^2.0.3",
    "ts-loader": "^0.7.2",
    "typescript": "^2.2.2",
    "typings": "^1.1.0",
    "uglify-js": "^2.8.16",
    "uglifyjs-webpack-plugin": "^0.3.1",
    "vinyl-fs": "^2.4.3",
    "webpack": "^2.3.3",
    "webpack-dev-server": "^2.2.0",
    "webpack-merge": "^0.14.0"
  },
  "dependencies": {
    "@angular/common": "^4.0.1",
    "@angular/compiler": "^4.0.1",
    "@angular/core": "^4.0.1",
    "@angular/forms": "^4.0.1",
    "@angular/http": "^4.0.1",
    "@angular/platform-browser": "^4.0.1",
    "@angular/platform-browser-dynamic": "^4.0.1",
    "@angular/router": "^4.0.1",
    "@types/clipboard": "^1.5.31",
    "@types/qrcode-generator": "0.0.15",
    "bootstrap": "^3.3.7",
    "chart.js": "^2.4.0",
    "clipboard": "^1.6.1",
    "core-js": "^2.4.1",
    "crypto-js": "^3.1.7",
    "dragula": "^3.7.2",
    "echarts": "^3.4.0",
    "file-saver": "^1.3.3",
    "get-pixels": "^3.3.0",
    "html2canvas": "^0.5.0-beta4",
    "iconv-lite": "^0.4.15",
    "localforage": "^1.4.3",
    "moment": "^2.15.1",
    "node-rsa": "^0.4.2",
    "pinyin": "^2.8.0",
    "printer": "^0.2.2",
    "qrcode-generator": "^1.0.7",
    "rxjs": "5.0.1",
    "sequelize": "^3.27.0",
    "serialport": "^5.0.0-beta3",
    "socket.io-client": "^1.7.2",
    "sqlite3": "^3.1.8",
    "uuid": "^3.0.1",
    "xml2js": "^0.4.17",
    "zone.js": "^0.7.4"
  }
```

**Comment by diicar** [comment]
import {} from '@angular/core';

**Comment by michaellev** [comment]
Elaborated reproduce steps are missing, so this issue can't be reproduced accurately to get the error.
@keyiis please update the issue so that it could be reproduced.
Thanks :)
#goodnessSquad

**Comment by filipesilva** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
