### ISSUE TITLE
styles.css - Error: (0 , _identifier.getUndoPath) is not a function, after ng server/build with Nx workspace

### ISSUE THREAD

**Issue by AwesomeObserver** [angular/angular-cli#21628]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 12.1.0

### Description
I generate a new Nx workspace (12.7.2) with Angular (12.1.0). 

After updating ng from 12.1.0 to 12.2.2 I'm get the error `Error: (0 , _identifier.getUndoPath) is not a function` after run `ng server` or `ng build`. 

Also, I removed execute `ng` from `nx` and delete `"postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main"` from `package.json`.

## 🔬 Minimal Reproduction
https://github.com/AwesomeObserver/ng-styles-bug

## 🔥 Exception or Error

<pre><code>
// with ng server
styles.css - Error: (0 , _identifier.getUndoPath) is not a function
// with ng build
styles.c331d6dc3ee8f876a7f8.css - Error: (0 , _identifier.getUndoPath) is not a function
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.2
Node: 14.15.0
Package Manager: npm 6.14.8
OS: win32 x64

Angular: 12.2.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.2
@angular-devkit/build-angular   12.2.2
@angular-devkit/core            12.1.4
@angular-devkit/schematics      12.1.4
@schematics/angular             12.1.4
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
Please try removing both the node modules directory and the package lock file and re-installing.  Issues such as this generally are caused by incorrect package hoisting by the package manager.
Alternatively, npm 7 or yarn could be attempted; as they appear to have less of a probability of generating these type of package installation situations.

**Comment by AwesomeObserver** [comment]
@clydin 
I switch to Yarn and fix it. Thank you!
But, with npm 6.14.8 I always got this error (I removed node_modules and package-lock file)

**Comment by clydin** [comment]
You're welcome.  Glad you were able to sort it out.

**Comment by npalacio** [comment]
I am also running into this issue. Upgrading to use npm 7 did not work and I cannot go to Yarn, any other suggestions? I tried out a few different versions of node with no luck (14.15.0, 14.17.5, 16.8.0)

**Comment by npalacio** [comment]
Installing mini-css-extract-plugin@2.2.1 to my dev dependencies fixed this issue for me

**Comment by jagdishjadeja** [comment]
I am running into same problem
any update on this ?

**Comment by errsolve7** [comment]
[[Already Solved] styles.css – Error: (0 , _identifier.getUndoPath) is not a function while upgrading angular](https://exerror.com/styles-css-error-0-_identifier-getundopath-is-not-a-function-while-upgrading-angular/)

**Comment by Burgov** [comment]
> Installing mini-css-extract-plugin@2.2.1 to my dev dependencies fixed this issue for me

This fixed it for me too, thanks!
