### ISSUE TITLE
ng serve running lint in node_modules folder after update from 5.2 to 8.2.14

### ISSUE THREAD

**Issue by kyle-erin** [angular/angular-cli#16600]
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
### Is this a regression?

 Yes, the previous version in which this bug was not present was: 5.2

### Description
I'm using the codelyzer library, when I run the `ng serve` command, it finds linting errors in the node_modules folder (codelyzer). Running `ng lint` works fine.

## 🔬 Minimal Reproduction

I started with Angular 5.2, and updated to Angular 8.2.14.
Afterwards, I simply ran `ng serve`

## 🔥 Exception or Error
<pre><code>
> ng serve

10% building 3/3 modules 0 activei ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 2.02 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 149 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 662 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.8 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 340 kB [initial] [rendered]
Date: 2020-01-09T01:54:23.005Z - Hash: eb2de38d6418364fc4ab - Time: 9011ms

ERROR in ../node_modules/codelyzer/util/function.d.ts:21:9 - error TS1086: An accessor cannot be declared in an ambient context.

21     get isNothing(): boolean;
           ~~~~~~~~~
../node_modules/codelyzer/util/function.d.ts:22:9 - error TS1086: An accessor cannot be declared in an ambient context.

22     get isSomething(): boolean;
</code></pre>


## 🌍 Your Environment
<pre><code>
<!-- run `ng version` and paste output below -->
<!-- ✍️-->
Angular CLI: 8.3.22
Node: 12.13.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.22
@angular-devkit/build-angular     0.803.22
@angular-devkit/build-optimizer   0.803.22
@angular-devkit/build-webpack     0.803.22
@angular-devkit/core              8.3.22
@angular-devkit/schematics        8.3.22
@angular/cli                      8.3.22
@ngtools/webpack                  8.3.22
@schematics/angular               8.3.22
@schematics/update                0.803.22
rxjs                              6.5.4
typescript                        3.4.5
webpack                           4.39.2
</code></pre>

**Anything else relevant?**
Here is my `package.json` dependencies
<pre><code>
  "dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/platform-server": "^8.2.14",
    "@angular/router": "^8.2.14",
    "@clr/angular": "^2.3.4",
    "@clr/icons": "^2.3.4",
    "@clr/ui": "^2.3.4",
    "@webcomponents/custom-elements": "^1.0.0",
    "angular2-text-mask": "^8.0.4",
    "aws-sdk": "^2.597.0",
    "buffer": "^5.4.3",
    "codelyzer": "^5.2.1",
    "core-js": "^2.4.1",
    "file-saver": "^1.3.8",
    "font-awesome": "^4.7.0",
    "ng-toastr": "^1.0.0",
    "ngx-toastr": "^11.2.1",
    "rxjs": "^6.5.4",
    "rxjs-compat": "^6.0.0-rc.0",
    "text-mask-addons": "^3.7.1",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.22",
    "@angular/cli": "^8.3.22",
    "@angular/language-service": "^8.2.14",
    "@types/file-saver": "^1.3.1",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^6.0.96",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "^5.20.1",
    "typescript": "~3.4.1"
  }

</code></pre>

**Comment by alan-agius4** [comment]
That’s actually a compilation error. Somehow in your project `codelyzer` is being included in the compilation, this might be related to either a misconfiguration or your folder structure. 

Can you share your `tsconfig.app.json`?

**Comment by EdricChan03** [comment]
It's probably because they specified `codelyzer` as a `dependency` when it would usually be defined as a `devDependency`.

**Comment by alan-agius4** [comment]
@EdricChan03, doesn't make a difference if it's in `devDependencies` or `dependencies` as the node package will be installed in the same location. 

That said, `codelyzer` should be listed as in `devDependencies`.

**Comment by kyle-erin** [comment]
> That’s actually a compilation error. Somehow in your project `codelyzer` is being included in the compilation, this might be related to either a misconfiguration or your folder structure.
> 
> Can you share your `tsconfig.app.json`?

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "types": ["node"]
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

**Comment by kyle-erin** [comment]
> @EdricChan03, doesn't make a difference if it's in `devDependencies` or `dependencies` as the node package will be installed in the same location.
> 
> That said, `codelyzer` should be listed as in `devDependencies`.

I removed it from deps and have it only in devDeps, I'm not getting an error anymore. But what if I want to use the library in the code?

**Comment by alan-agius4** [comment]
Glad that you fixed it. You cannot use that library in your code because that library is a used to lint Angular code and is meant to be used on Node. There is no use for it a browser application.
