### ISSUE TITLE
Compilation error in Ivy mode with 8.0.0-rc.1

### ISSUE THREAD

**Issue by sergey-morenets** [angular/angular-cli#14294]
# 🐞 Bug report

### Command (mark with an `x`)
ng build --prod

### Is this a regression?
No 

### Description

I have a project with PrimeNg dependency. When I upgraded to 8.0.0-rc.1 my project compiled properly. But if I enable Ivy flag in tsconfig.json:

  "angularCompilerOptions": {
    "enableIvy": true,
    "allowEmptyCodegenFiles": true
  },

I get a lot of error messages about incorrect module usage when I build the project.

## 🔬 Minimal Reproduction

1. Create new project with Angular CLI 8.0.0-rc.1
2. Add Primeng dependency and import its modules into AppModule.

## 🔥 Exception or Error
<pre><code>
ERROR in node_modules/primeng/components/confirmdialog/confirmdialog.d.ts(64,22): error TS-996002: Appears in the NgModule.imports of SharedModule, but could not be resolved to an NgModule class
node_modules/ngx-filter-pipe/src/app/shared/ngx-filter-pipe/ngx-filter.module.d.ts(1,22): error TS-996002: Appears in the NgModule.imports of SharedModule, but could not be resolved to an NgModule class
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.0-rc.1
Node: 11.3.0
OS: win32 x64
Angular: 8.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.1
@angular-devkit/build-angular     0.800.0-rc.1
@angular-devkit/build-optimizer   0.800.0-rc.1
@angular-devkit/build-webpack     0.800.0-rc.1
@angular-devkit/core              8.0.0-rc.1
@angular-devkit/schematics        8.0.0-rc.1
@angular/cdk                      8.0.0-beta.2
@angular/http                     8.0.0-beta.10+1.sha-a28b3e3
@angular/material                 8.0.0-beta.2
@ngtools/webpack                  8.0.0-rc.1
@schematics/angular               8.0.0-rc.1
@schematics/update                0.800.0-rc.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Comment by alan-agius4** [comment]
The above error typically means that ngcc didn’t run.

Will have a look at it in the coming days.

**Comment by JoostK** [comment]
From analyzing other sitatuations where ngcc did not process a package, I see two causes why PrimeNG is not being processed:

1. There's no `typings` key in [its `package.json`](https://unpkg.com/primeng@7.1.2/package.json)
    - Same as https://github.com/angular/angular/issues/28603
    - Still unresolved.
2. Typing files shadow the JavaScript sources
    - Root cause described in https://github.com/angular/angular/issues/29939#issuecomment-485259399
    - PR: https://github.com/angular/angular/pull/30017

**Comment by sergey-morenets** [comment]
Hi @JoostK 

Thank you for the response. Does that mean I can't use Ivy mode if I have PrimeNG dependency?

**Comment by JoostK** [comment]
@sergey-morenets at this moment, I'm afraid you can't yet. We are still experiencing incompatibilities with ngcc for packages that do not follow APF (Angular Package Format), of which PrimeNG is one example. We are working on resolving those incompatibilities in ngcc though.

**Comment by petebacondarwin** [comment]
I'm afraid that ngcc will never work with packages that have no typings files (.d.ts). Does PrimeNG have typings files at all or just no `typings` property in package.json?

**Comment by alan-agius4** [comment]
It seems that ng-prime, relies on deep-imports which is not supported.

Example of usage
```ts
import { InputTextModule } from 'primeng/inputtext';
import { ButtonModule } from 'primeng/button';
```

However these above are not secondary entrypoints, but rather files within the distributed package.

**Comment by petebacondarwin** [comment]
I think that an ngcc config file that will be placed in the project using such a package could solve this issue. The config could specify what typings file to use for a given entry-point path.

**Comment by vytautas-pranskunas-** [comment]
Any updates on this?

**Comment by petebacondarwin** [comment]
I started a design doc https://hackmd.io/qn0asUnzTHWHj8s5Nn5iFA

**Comment by alan-agius4** [comment]
@manughub can we please move this to angular/angular?
