### ISSUE TITLE
v17 uses optional dependency, which causes build to fail (if deps installed with --no-optional)

### ISSUE THREAD

**Issue by cvuorinen** [angular/angular-cli#28572]
### Command

build

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v16

### Description

With previous versions, build used to work even without optional dependencies, after upgrading to v17 it fails when we install dependencies with `npm ci --no-optional` (or `npm install --no-optional`). We are using the --no-optional flag in our CI environment for example.

### Minimal Reproduction

```bash
npx @angular/cli@17 new angular-test --skip-install --interactive=false
cd angular-test
npm install --no-optional
npm run build
```

### Exception or Error

```
An unhandled exception occurred: Cannot find module 'esbuild'
Require stack:
- angular-test/node_modules/@angular-devkit/build-angular/src/tools/esbuild/bundler-context.js
- angular-test/node_modules/@angular-devkit/build-angular/src/builders/application/index.js
- angular-test/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- angular-test/node_modules/@angular-devkit/architect/node/index.js
- angular-test/node_modules/@angular/cli/src/command-builder/architect-base-command-module.js
- angular-test/node_modules/@angular/cli/src/command-builder/architect-command-module.js
- angular-test/node_modules/@angular/cli/src/commands/build/cli.js
- angular-test/node_modules/@angular/cli/src/commands/command-config.js
- angular-test/node_modules/@angular/cli/src/command-builder/command-runner.js
- angular-test/node_modules/@angular/cli/lib/cli/index.js
- angular-test/node_modules/@angular/cli/lib/init.js
```

### Your Environment

```
Angular CLI: 17.3.10
Node: 18.15.0
Package Manager: npm 9.5.0
OS: linux x64

Angular: 17.3.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.10
@angular-devkit/build-angular   17.3.10
@angular-devkit/core            17.3.10
@angular-devkit/schematics      17.3.10
@angular/cli                    17.3.10
@schematics/angular             17.3.10
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.10
```

### Anything else relevant?

Defined as optional dependency here:
https://github.com/angular/angular-cli/blob/b6d1f681efd2c102c987355bf796a971c33433eb/packages/angular_devkit/build_angular/package.json#L73-L75

But used for example here:
https://github.com/angular/angular-cli/blob/b6d1f681efd2c102c987355bf796a971c33433eb/packages/angular_devkit/build_angular/src/tools/esbuild/bundler-context.ts#L9-L19

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by cvuorinen** [comment]
@alan-agius4 Seems new version doesn't work either...

Repro:
```bash
npx @angular/cli@latest new angular-test --interactive=false --skip-install
cd angular-test
npm install --no-optional
npm run build
```

Gives error:
```
An unhandled exception occurred: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
```

**Comment by cvuorinen** [comment]
Shouldn't `ng new` then choose something to install for the current platform? Or is it the users responsibility to manually install something after running `ng new`? Is this documented somewhere?
At least in https://angular.dev/installation it doesn't say anything about it.

Or is it considered just some "special case" that users who use --no-optional should be aware and in that case know that they need to manually install something? Don't really know how common it is to run `npm ci --no-optional` for example in CI environments, but I would expect others do it too...

**Comment by alan-agius4** [comment]
It’s generally recommended not to use `--no-optional` and to allow the package manager to handle dependencies as intended. Tools like `sass`, `rollup`, `esbuild`, and others rely on `optionalDependencies` to ensure platform-specific dependencies are installed appropriately.

While, in theory, a tool should still function without optional dependencies, this can be open to interpretation. For CI, installing optional dependencies is important because it may lead to the installation of native packages, which can significantly improve build times.
