### ISSUE TITLE
MODULE_NOT_FOUND when updating from v12 to v13.

### ISSUE THREAD

**Issue by rhegner** [angular/angular-cli#22331]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

MODULE_NOT_FOUND when updating from v12 to v13.

## 🔬 Minimal Reproduction

```npx @angular/cli@13 update @angular/core@13 @angular/cli@13```

## 🔥 Exception or Error

<pre><code>
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
✔ Package successfully installed.
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Robert\SMR\app\Code\WebApp\ClientApp\'C:\Users\Robert\AppData\Local\Temp\angular-cli-packages-f4G0IA\node_modules\@angular\cli\bin\ng.js''
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
</code></pre>

## 🌍 Your Environment

<pre><code>
Your global Angular CLI version (13.1.0) is greater than your local version (12.0.3). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.3
Node: 16.13.0
Package Manager: npm 8.1.3
OS: win32 x64

Angular: 12.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.3
@angular-devkit/build-angular   12.0.3
@angular-devkit/core            12.0.3
@angular-devkit/schematics      12.0.3
@angular/fire                   6.1.5
@schematics/angular             12.0.3
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Anything else relevant?**

It looks like the module path is concatenated in a weird way (concatenating two absolute paths together).
Why is this happening?

**Comment by rhegner** [comment]
As a workaround I updated my project using the local CLI:
```ng update @angular/core@13 @angular/cli@13```

**Comment by alan-agius4** [comment]
HI @rhegner, 

I tried to replicate this on a newly generated v12 workspace but I wasn't able. Is there anyway you can put a reproduction togather?

```
➜  cli-reproductions npx @angular/cli@12 new twelve
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
CREATE twelve/README.md (1053 bytes)
CREATE twelve/.editorconfig (274 bytes)
CREATE twelve/.gitignore (604 bytes)
CREATE twelve/angular.json (3039 bytes)
CREATE twelve/package.json (1070 bytes)
CREATE twelve/tsconfig.json (783 bytes)
CREATE twelve/.browserslistrc (703 bytes)
CREATE twelve/karma.conf.js (1423 bytes)
CREATE twelve/tsconfig.app.json (287 bytes)
CREATE twelve/tsconfig.spec.json (333 bytes)
CREATE twelve/src/favicon.ico (948 bytes)
CREATE twelve/src/index.html (292 bytes)
CREATE twelve/src/main.ts (372 bytes)
CREATE twelve/src/polyfills.ts (2820 bytes)
CREATE twelve/src/styles.css (80 bytes)
CREATE twelve/src/test.ts (788 bytes)
CREATE twelve/src/assets/.gitkeep (0 bytes)
CREATE twelve/src/environments/environment.prod.ts (51 bytes)
CREATE twelve/src/environments/environment.ts (658 bytes)
CREATE twelve/src/app/app-routing.module.ts (245 bytes)
CREATE twelve/src/app/app.module.ts (393 bytes)
CREATE twelve/src/app/app.component.css (0 bytes)
CREATE twelve/src/app/app.component.html (24617 bytes)
CREATE twelve/src/app/app.component.spec.ts (1073 bytes)
CREATE twelve/src/app/app.component.ts (210 bytes)
✔ Packages installed successfully.
    Successfully initialized git.
➜  cli-reproductions cd twelve
➜  twelve git:(master) npx @angular/cli@13 update @angular/core@13 @angular/cli@13


Using package manager: 'npm'
Collecting installed dependencies...
Found 23 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/build-angular @ "13.1.0" (was "12.2.14")...
    Updating package.json with dependency @angular/cli @ "13.1.0" (was "12.2.14")...
    Updating package.json with dependency @angular/compiler-cli @ "13.1.0" (was "12.2.14")...
    Updating package.json with dependency typescript @ "4.5.3" (was "4.3.5")...
    Updating package.json with dependency @angular/animations @ "13.1.0" (was "12.2.14")...
    Updating package.json with dependency @angular/common @ "13.1.0" (was "12.2.14")...
    Updating package.json with dependency @angular/compiler @ "13.1.0" (was "12.2.14")...
    Updating package.json with dependency @angular/core @ "13.1.0" (was "12.2.14")...
    Updating package.json with dependency @angular/forms @ "13.1.0" (was "12.2.14")...
    Updating package.json with dependency @angular/platform-browser @ "13.1.0" (was "12.2.14")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "13.1.0" (was "12.2.14")...
    Updating package.json with dependency @angular/router @ "13.1.0" (was "12.2.14")...
  UPDATE package.json (1067 bytes)
```

**Comment by rhegner** [comment]
I can't reproduce it anymore, since I'm now on v13 (using the workaround above).

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by ebussa** [comment]
Just an FYI, I am seeing this exact concatenation problem.
