### ISSUE TITLE
ng build -prod errors with 1.7.0-RC.0

### ISSUE THREAD

**Issue by nakahparis** [angular/angular-cli#9551]
### Versions
Angular CLI: 1.7.0-rc.0
Node: 9.5.0
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.1.0
@angular/cli: 1.7.0-rc.0
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material-moment-adapter: 5.1.0
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0-rc.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.4.2
webpack: 3.10.0

### Repro steps
* ng build -prod

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
..\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:40
                callbacks[i](err, result);
                            ^

TypeError: callbacks[i] is not a function

### Desired behavior
Application compiled without any error


### Mention any other details that might be useful (optional)
It was working fine with 1.7.0-beta.3

**Comment by zhekaus** [comment]
I am the same. The same problem with 1.6.8 too

**Comment by RafaPegorari** [comment]
I have the same problem.

```
.../node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40
		callbacks[i](err, result);
		            ^
TypeError: callbacks[i] is not a function
```

## Versions
@angular/core": "^5.2.4
@angular/cli": "^1.6.8
Node 9.4.0

### Dependencies
"webpack": "3.10.0",
"enhanced-resolve": "3.4.1",

**Comment by RafaPegorari** [comment]
Duplicate of  #9550

**Comment by surajjadhav720** [comment]
npm install copy-webpack-plugin@4.3.0 is solved the problem

**Comment by amitkumar-adeptia** [comment]
npm install copy-webpack-plugin@4.3.0 is solved the problem

not working form me

**Comment by nakahparis** [comment]
npm install copy-webpack-plugin@4.3.0 also worked for me
