### ISSUE TITLE
error: Module "mymodule" has no exported member "mycomponent"  after upgrading to angular 16

### ISSUE THREAD

**Issue by graphicsxp** [angular/angular-cli#25647]
### Which @angular/* package(s) are the source of the bug?

core, Don't known / other

### Is this a regression?

Yes

### Description

i am using an angular workspace with a blend of applications and libraries of my own which are used by these applications. My workspace configuration/structure is the same since i started the project with angular 10 (some changes along the way at each upgrade but nothing major).

but today after migrating to 16, one and only of my libraries failed to be imported in my application, the other libraries are imported just fine. I can't find any differences in the way they are configured though, particularly in angular.json.

this is how it is imported :  `import { DesignerComponent } from 'process'; `
I get the error below.

If I import it like this :  
`import { DesignerComponent } from '../../../../../process/src/lib/designer/designer.component';`

then it compiles just fine

### Please provide the exception or error you saw

```true
error TS2305: Module '"process
"' has no exported member 'DesignerComponent'.

15 import { DesignerComponent } from 'process';
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.7
Node: 16.16.0
Package Manager: npm 8.11.0
OS: win32 x64

Angular: 16.1.8
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.7
@angular-devkit/build-angular   16.1.7
@angular-devkit/core            16.1.7
@angular-devkit/schematics      16.1.7
@angular/cdk                    16.1.7
@angular/cli                    16.1.7
@schematics/angular             16.1.7
ng-packagr                      16.1.0
rxjs                            7.8.1
typescript                      4.9.5
zone.js                         0.13.1
```

**Comment by JoostK** [comment]
`process` is a builtin Node module, which is likely confusing the module resolver. I would _highly_ recommend to avoid using builtin modules as name of your own packages. The typical approach of avoiding name conflicts is to make use of a scoped  package name, e.g. `@my-scope/process`.

**Comment by graphicsxp** [comment]
really ? is it a new module in angular 16 ? because i never had this issue before

my package is called indeed @my-scope/process and this is how it is imported when used in applications that are outside my workspace
however for applications inside the same workspace i import it as 'process'.   will try to rename to see if it makes a difference

**Comment by JoostK** [comment]
It is a builtin Node module since forever. It could be that module resolution or project configuration changed in subtle ways that has resulted in a change of behavior.

**Comment by graphicsxp** [comment]
@JoostK  Thanks man ! this was it 👍   I renamed it to process-designer and now it compiles just fine. Funny this has never occured before this upgrade.
