### ISSUE TITLE
newly scaffolded 1.7 app doesn't serve after migration to 6.0.0-rc.4

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#10317]
### Versions

`ng new` project with 1.7.4 
then updated to

```
Angular CLI: 6.0.0-rc.4
Node: 9.9.0
OS: linux x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.5.6
@angular-devkit/build-angular   0.5.6
@angular-devkit/core            0.5.6 (cli-only)
@angular-devkit/schematics      0.5.6 (cli-only)
@angular/cli                    6.0.0-rc.4
@ngtools/json-schema            1.2.0
@schematics/angular             0.5.6 (cli-only)
@schematics/update              0.5.6
rxjs                            5.5.10
typescript                      2.5.3
```

### Repro steps
yarn global add @angular/cli@1.7.4
ng new my-app
cd my-app
yarn add @angular/cli@6.0.0-rc.4
ng update @angular/cli --migrate-only --from=1.7.0
ng serve

### Observed behavior
```
$ ng serve
Cannot find module 'webpack/lib/RequestShortener'
Error: Cannot find module 'webpack/lib/RequestShortener'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/super/workspace/stephenfluin/test/rxjs-repro/node_modules/uglifyjs-webpack-plugin/dist/index.js:24:25)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/super/workspace/stephenfluin/test/rxjs-repro/node_modules/uglifyjs-webpack-plugin/dist/cjs.js:3:18)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
```

### Desired behavior
ng serve works :)

**Comment by StephenFluin** [comment]
Workaround that works:
`yarn add @angular/cli@6.0.0-rc.3`
`ng serve`

This fixes it. And frustratingly, updating back to rc.4 then `ng serves` just fine. :(

**Comment by filipesilva** [comment]
I just tested a 1.7 app updated to 6.0.0-rc.4 and didn't see this error.

It sounds like a dependency problem that went away after reinstalling the node_modules.

**Comment by StephenFluin** [comment]
I followed the steps above twice last night on one computer with the same result. 

Just tried again with a different computer and it doesn't repro. Closing.
