### ISSUE TITLE
Error "Tree type is not supported." when generating new module in v6.1.1

### ISSUE THREAD

**Issue by MainaWycliffe** [angular/angular-cli#11683]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ X ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Angular CLI 6.1.1
Windows 10
Node 10.7.0
Yarn 1.9.2

### Repro steps
Upgrade to the latest version of Angular 6.1.1 **(Works okay on 6.1.0)**
run  `ng g module modules/test2 --flat` 
or just `ng g module modules/test2`
or just  `ng g module test2`
or just  `ng g m test2`

**Interestingly, it works when generating modules with routing flag, but haven't had any success with any other flags**

**`ng g module modules/test2 --flat -routing `or `ng g module test2 --routing `works.**
 
### The log given by the failure
I am getting a simple message without any other details attached:

`Tree type is not supported.`

**Not enough information to help me troubleshoot where the problem is. I tried this on two of my projects.**
 
### Desired functionality
Should generate a new module in the specified location.

**UPDATE**

I also deleted the entire `node_modules` folder and re installed the packages without success. Downgrading back to 6.1.0 works as expected.

**Comment by darrenmothersele** [comment]
Clean install of latest Angular CLI this morning. v6.1.1

I also get this message when running:

    ng new --style=scss --routing --skip-tests --skip-git example

I also tried 6.1.0 same error. I had to downgrade CLI version to 6.0.7 in order for `ng new` to work.

**Comment by MainaWycliffe** [comment]
@darrenmothersele That's interesting, because I tried to run the above command on my v6.1.1 and it was successfully executed. I also went ahead and created a new project and run the commands that could not executed earlier successfully without any issues. On my part, it seems to be an issue with upgrading to Angular 6.1.1 from 6.1.0.

**Comment by Akshay-Kumar-Singh** [comment]
**Versions**
Angular CLI: 6.1.1
Node: 8.11.3
OS: linux x64
I got the same problem and unable to downgrade the version of angular/cli. Removed node, npm and angular and again install them with the angular version 6.1.0. But it still shows the above versions.
The issue is not resolved. Can anyone help me to find the root cause of the issue.

**Comment by hansl** [comment]
Hi,

Could you run `npm ls @angular-devkit/schematics` on your command line and paste the output here?

Also, as a way to try to fix this, could you try getting rid of you `node_modules` folder and reinstalling your project packages?

**Comment by MainaWycliffe** [comment]
Here is the output of the `npm ls @angular-devkit/schematics`
```
hades@0.0.0 C:\Users\maina\Projects\hades
+-- @angular/cli@6.1.1
| +-- @angular-devkit/schematics@0.7.1
| +-- @schematics/angular@0.7.1
| | `-- @angular-devkit/schematics@0.7.1  deduped
| `-- @schematics/update@0.7.1
|   `-- @angular-devkit/schematics@0.7.1  deduped
`-- @angular/pwa@0.7.0
  +-- @angular-devkit/schematics@0.7.0
  `-- @schematics/angular@0.7.0
    `-- @angular-devkit/schematics@0.7.0
```

I already tried to remove the entire `node_modules` folder and reinstalling the packages without success.

**Comment by adnanebrahimi** [comment]
Upgrade from 6.0.7 to 6.1.0 has the same issue with 'generate' command.
Output:
```
ng g service ExampleService
newTree.optimize is not a function
```

**Comment by MainaWycliffe** [comment]
@adnanebrahimi Am also getting the same error on both 6.1.0 and 6.1.1. 

`newTree.optimize is not a function`

**Comment by ArielGueta** [comment]
Any news on this? I was getting `newTree.optimize is not a function`, then, after updating my custom schematics to 0.7, I'm getting `Tree type is not supported.`

**Comment by ArielGueta** [comment]
@MainaWycliffe I don't think there is v6.1.1.

**Comment by odahcam** [comment]
I ran `yarn install` and `yarn upgrade` and then it worked.

**Comment by MainaWycliffe** [comment]
@odahcam Thanks. I can confirm that works. I first removed the node_modules directory, then ran yarn install and then ran yarn upgrade.

**Comment by MainaWycliffe** [comment]
It seems like `ng update` is not updating some schematics packages. Some were still stack at 0.7.0 but after `yarn upgrade`, all are updated to 0.7.1

**Before:**

```
+-- @angular/cli@6.1.1
| +-- @angular-devkit/schematics@0.7.1
| +-- @schematics/angular@0.7.1
| | `-- @angular-devkit/schematics@0.7.1  deduped
| `-- @schematics/update@0.7.1
|   `-- @angular-devkit/schematics@0.7.1  deduped
`-- @angular/pwa@0.7.0
  +-- @angular-devkit/schematics@0.7.0
  `-- @schematics/angular@0.7.0
    `-- @angular-devkit/schematics@0.7.0
```

**After:**
```
+-- @angular/cli@6.1.1
| +-- @angular-devkit/schematics@0.7.1
| +-- @schematics/angular@0.7.1
| | `-- @angular-devkit/schematics@0.7.1  deduped
| `-- @schematics/update@0.7.1
|   `-- @angular-devkit/schematics@0.7.1  deduped
`-- @angular/pwa@0.7.1
  `-- @angular-devkit/schematics@0.7.1  deduped
```

**Comment by NetanelBasal** [comment]
+1

**Comment by hansl** [comment]
`Tree.optimizer is not a function` was fixed in https://github.com/angular/angular-cli/pull/11693 (which isn't released yet but will be in 6.1.2 this Wednesday).

I'm keeping this issue open as we need to figure out forward compatibility in Schematics for people who have multiple version of a library.

**Comment by ArielGueta** [comment]
6.1.2 will also support backward compatibility?

**Comment by snebjorn** [comment]
Got similar issues

```
> ng g c compName
Tree type is not supported.
```

Here's the schematic versions
```
> npm ls @angular-devkit/schematics
`-- @angular/cli@6.1.1
  +-- @angular-devkit/schematics@0.7.1
  +-- @schematics/angular@0.7.1
  | `-- @angular-devkit/schematics@0.7.1
  `-- @schematics/update@0.7.1
    `-- @angular-devkit/schematics@0.7.1
```

```
> ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.1.1
Node: 9.10.1
OS: win32 x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.1
@angular-devkit/build-angular     0.7.1
@angular-devkit/build-optimizer   0.7.1
@angular-devkit/build-webpack     0.7.1
@angular-devkit/core              0.7.1
@angular-devkit/schematics        0.7.1
@angular/cdk                      6.4.2
@angular/cli                      6.1.1
@angular/flex-layout              6.0.0-beta.17
@angular/material                 6.4.2
@ngtools/webpack                  6.1.1
@schematics/angular               0.7.1
@schematics/update                0.7.1
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.9.2
```

**Comment by ArielGueta** [comment]
Updating my custom schematic to:

```
"@angular-devkit/architect": "0.7.2",
"@angular-devkit/core": "0.7.2",
"@angular-devkit/schematics": "0.7.2",
```

And Angular CLI:
```
"@angular-devkit/build-angular": "0.7.2",
"@angular/cli": "~6.1.2",
```

Still gives the error:

> Tree type is not supported.

Am I missing something else?

**Comment by MainaWycliffe** [comment]
Here too, the problem still exists. I have to run `yarn upgrade` after upgrading to `6.2.2` for everything to work as expected.

**Comment by ArielGueta** [comment]
Something new about this? I can't publish a new release of my custom schematics.

**Comment by adnanebrahimi** [comment]
I solved this issue by updating all cli packages individually that listed in readme

**Comment by toddwseattle** [comment]
Having this same problem.  `ng g module shared -d` returns ***Tree Type Not Supported*** error.

`npm ls @angular-devkit/schematics` returns:
```
+-- @angular/cli@6.1.2
| +-- @angular-devkit/schematics@0.7.2
| +-- @schematics/angular@0.7.2
| | `-- @angular-devkit/schematics@0.7.2  deduped
| `-- @schematics/update@0.7.2
|   `-- @angular-devkit/schematics@0.7.2
`-- @angular/pwa@0.7.2
  +-- @angular-devkit/schematics@0.7.2
  `-- @schematics/angular@0.7.2
    `-- @angular-devkit/schematics@0.7.2  deduped
```
and `ng -v` returns:
```
Angular CLI: 6.1.2
Node: 8.9.3
OS: win32 x64
Angular: 6.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.2
@angular-devkit/build-angular     0.7.2
@angular-devkit/build-optimizer   0.7.2
@angular-devkit/build-webpack     0.7.2
@angular-devkit/core              0.7.2
@angular-devkit/schematics        0.7.2
@angular/cdk                      6.4.2
@angular/cli                      6.1.2
@angular/material                 6.4.2
@angular/pwa                      0.7.2
@ngtools/webpack                  6.1.2
@schematics/angular               0.7.2
@schematics/update                0.7.2
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2
```

like @MainaWycliffe said in the first report, seems to work if you do --module flag.

will try re-installing cli globally as @StephenFluin  did to see if it helps.

I'm using npm not yarn.

**Comment by toddwseattle** [comment]
nope, global reinstall did not help.  I guess I want routing!

**Comment by MainaWycliffe** [comment]
@toddwseattle try updating your packages using npm (`npm update`). That's how i solved the issue, although am using yarn but I am guessing it should work for npm too.

**Comment by ArielGueta** [comment]
There is something wrong with the filter function, when I removed it, it works fine.

```ts
    const templateSource = apply(url('./files'), [
      options.spec ? noop() : filter(path => !path.endsWith('.spec.ts')),
      template({
        ...stringUtils,
        ...options
      }),
      move(parsedPath.path)
    ]);
```

This works:
```ts
    const templateSource = apply(url('./files'), [
      template({
        ...stringUtils,
        ...options
      }),
      move(parsedPath.path)
    ]);
```

**Comment by nisimjoseph** [comment]
As @StephenFluin  note in another post. 
I reinstall @angular/cli from **global** and **project itself**. It solved the issue.

**Comment by Alekshar** [comment]
I get the same problem with @angular/cli@6.1.2
impossible to get rid of this error. I tried both npm update and delete/reinstall both my project's node_modules and the global angular/cli installation without success.

**Comment by isaacplmann** [comment]
Thank you @nisimjoseph .  That saved me some pain.

**Comment by webcat12345** [comment]
Same issue **Tree type is not supporteed** but generating ngrx action. any workaround for this?

**Comment by inthegarage** [comment]
Same again here, my command line:
ng generate action Bookings --group

Any suggestions?

**Comment by webcat12345** [comment]
@inthegarage please refer this [issue](https://github.com/angular/angular-cli/issues/11707)

**Comment by JoepKockelkorn** [comment]
I'm having the same issue. Bumped into it when writing my own schematic. My tests work fine, but when I run the actual schematic using the schematics-cli I got the error. Turns out the angular-cli itself gives the error, not my schematic.
```
Angular CLI: 6.1.3
Node: 8.11.3
OS: win32 x64
Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.3 (cli-only)
@angular-devkit/core         0.7.3
@angular-devkit/schematics   0.7.3
@schematics/angular          0.7.3
@schematics/update           0.7.3 (cli-only)
rxjs                         6.2.2
typescript                   2.9.2
```

**Comment by fmavdb** [comment]
I'm also experiencing this issue.

Seems to have something to do with this commit: https://github.com/angular/angular-cli/commit/9582b84603182d43dbb9f0e6a8db600e83921f8a

**Comment by JackRus** [comment]
@nisimjoseph thx  - that helped. I am using angularcli 6.1.4. Solution: Delete node-modules folder and package-lock file. then run npm install.

**Comment by will0684** [comment]
Why is this issue closed? This is still a problem in this version. Uninstalling and reinstalling does not work. It is also not fixed with downgrading.

**Comment by JackRus** [comment]
@will0684 I just posted above your comment. Please try it.

**Comment by alexeagle** [comment]
The issue is closed automatically when the PR is merged that fixes it. You can get the fixed version from our snapshot build now
https://github.com/angular/cli-builds
or wait for a release that includes the fix if you want to verify it from an npm install.
