### ISSUE TITLE
[Bug] Can't run code coverage and do a single run

### ISSUE THREAD

**Issue by BustyLoli-Chan** [angular/angular-cli#6392]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
1.1.0-rc.0

### Repro steps.
`ng test --watch=false --code-coverage=true`

### Desired functionality.
`ng test --watch=false --code-coverage=true` should allow you to do a _single run_ with _code coverage_ 

### Additional Information
I was having some Karma compilation errors, but heard that 1.1.0-rc.0 had updates to the test framework that would fix them. It turns out that 1.1.0-rc.0 actually _did_ fix my original issue, but had some changes made to flags that were overwriting karma.conf.js configurations.

I have noticed as a side effect of this I can't seem to get both autowatch turned off (single builds) and code coverage being checked/generated at the same time

ng test --watch=false will do a single run *but*
ng test --code-coverage=true --watch=false will still run as if files are being watched.
I've also tried `ng test --single-run --code-coverage=true` no avail. 

Please advise.

**Comment by Meligy** [comment]
Looks like it might be broken by https://github.com/angular/angular-cli/commit/1cd0a0811df2b7a45cbffb413dd56e3ac21a96e4, but I can't see how from just looking at the commit.

Do you still have the coverage reporter in your karma config from previous CLI version? Have you tried adding / removing it?

**Comment by filipesilva** [comment]
Heya, I tried this right now with a new project and couldn't repro. Can you show me a project where this happens?

**Comment by BustyLoli-Chan** [comment]
I should have closed this issue, but I've since managed to get
`ng test --code-coverage=true --watch=false`
working. I'd hope it wasn't the case at the time but perhaps I had forgotten to run `npm install` and had some issues or outdated versions of something or other. 

I am hugely sorry for the inconvenience and not since updating this issue.

**Comment by filipesilva** [comment]
No problem at all, glad you got it sorted!
