### ISSUE TITLE
Need to add instructions to remove package-lock.json when updating?

### ISSUE THREAD

**Issue by aleshh** [angular/angular-cli#9467]
I just updated angular cli from 1.4.9 to 1.6.7 globally and in my project per the instructions and got an error:

`Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'`

Fixed by deleting `package-lock.json` and re-running `npm install`.

**Comment by viliks** [comment]
A had to do the same (delete package-lock.json) when updating from 1.6.8 to 1.7.1
