### ISSUE TITLE
beta 24 angular 2.4.0 this.host.isSourceFile is not a function

### ISSUE THREAD

**Issue by philjones88** [angular/angular-cli#3670]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

OSX Sierra 10.12.1 (16B2657)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

Node v7.2.1
NPM v3.10.10
Angular 2.4.0
@ngtools/webpack 1.2.1

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Worked on Angular 2.3.1 and @ngtools/webpack 1.1.9
`ngc -p tsconfig.aot.json`

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "es2015",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "outDir": "./aot/build",
        "rootDir": "./",
        "lib": [
            "es2015",
            "dom"
        ],
        "noImplicitAny": false,
        "suppressImplicitAnyIndexErrors": true,
        "typeRoots": [
            "./node_modules/@types"
        ],
        "types": [
            "jasmine",
            "lodash",
            "localforage",
            "node",
            "source-map",
            "uglify-js",
            "webpack"
        ]
    },
    "angularCompilerOptions": {
        "genDir": "aot",
        "entryModule": "src/app/app.module.ts#AppModule",
        "skipMetadataEmit": true,
        "debug": false
    },
    "compileOnSave": false,
  "exclude": [
    "node_modules",
    "dist",
    "**/*.ngfactory.ts",
    "**/*.shim.ts",
    "**/*.spec.ts",
    "src/app/test"
  ]
}
```

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
$ yarn run ngc
yarn run v0.17.10
$ rimraf -- aot
$ ngc -p tsconfig.aot.json
TypeError: this.host.isSourceFile is not a function
    at AotSummaryResolver._loadSummaryFile (/Users/phil/Documents/Projects/node_modules/@angular/compiler/bundles/compiler.umd.js:26253:26)
    at AotSummaryResolver.resolveSummary (/Users/phil/Documents/Projects/node_modules/@angular/compiler/bundles/compiler.umd.js:26230:20)
    at StaticSymbolResolver._resolveSymbolFromSummary (/Users/phil/Documents/Projects/node_modules/@angular/compiler/bundles/compiler.umd.js:25966:63)
    at StaticSymbolResolver.resolveSymbol (/Users/phil/Documents/Projects/node_modules/@angular/compiler/bundles/compiler.umd.js:25923:46)
    at StaticReflector.findSymbolDeclaration (/Users/phil/Documents/Projects/node_modules/@angular/compiler/bundles/compiler.umd.js:25182:69)
    at StaticReflector.findDeclaration (/Users/phil/Documents/Projects/node_modules/@angular/compiler/bundles/compiler.umd.js:25175:23)
    at StaticReflector.initializeConversionMap (/Users/phil/Documents/Projects/node_modules/@angular/compiler/bundles/compiler.umd.js:25364:35)
    at new StaticReflector (/Users/phil/Documents/Projects/node_modules/@angular/compiler/bundles/compiler.umd.js:25148:16)
    at Object.createAotCompiler (/Users/phil/Documents/Projects/node_modules/@angular/compiler/bundles/compiler.umd.js:26284:46)
    at Function.CodeGenerator.create (/Users/phil/Documents/Projects/node_modules/@angular/compiler-cli/src/codegen.js:81:36)
Compilation failed
error Command failed with exit code 1.
```

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by philjones88** [comment]
Closed. Missed a few package upgrades.

**Comment by dsm0880** [comment]
I had the exact same issue, just wanted to make a comment that for me I missed the @angular/compiler in the dev dependencies. Make sure you upgrade that along with all your other @angular packages.
