### ISSUE TITLE
ng generate directive error

### ISSUE THREAD

**Issue by nitz88** [angular/angular-cli#9351]
### Versions
Angular CLI: 1.6.5
Node: 6.11.2
OS: win32 ia32
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-otimizer: 0.0.41
@angular-devkit/core- 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.4.2
webpack: 3.10.0

After updating to angular cli version to 1.6.5, we are getting below error while using below command.

### Repro steps
ng g directive stylevalidator

Error:
Error: dryRunSink.commit(...).ignoreElements is not a function.
dryRunkSink.commit(...).ignoreElements is not a function.

### Desired behavior
Should generate new directive named "stylevalidator"

**Comment by wehrstedt** [comment]
Same for me, had this error with version 1.5.3, then upgraded to 1.6.5, but the error is still the same
Angular CLI: (1.5.3) 1.6.5
Node: 8.9.1
OS: Windows 10

**Comment by michael-letcher** [comment]
`ng generate service <name>` dose not work either

```
Angular CLI: 1.6.5
Node: 6.11.2
OS: darwin x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.6.2
webpack: 3.10.0
```

**Comment by DGmip** [comment]
Error: dryRunSink.commit(...).ignoreElements is not a function
dryRunSink.commit(...).ignoreElements is not a function

updated my cli just a few hours ago

**Comment by ondrejsv** [comment]
ng generate component the same.

**Comment by raydawg2000** [comment]
ng generate module has the same error

**Comment by atiruveedhi** [comment]
Does any one have solution for this, i too have same problem ?

Angular CLI: 1.6.5
Node: 9.4.0
OS: win32 x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/schematics: 0.0.45
@ngtools/json-schema: 1.1.0
typescript: 2.4.2
webpack: 3.10.0

ng generate component routes/contacts

Error: dryRunSink.commit(...).ignoreElements is not a function
dryRunSink.commit(...).ignoreElements is not a function

**Comment by zdsantos** [comment]
I had this error with version 1.6.0 and now with 1.6.5 still the same.
.

**Comment by Brocco** [comment]
This issue has been resolved, please see this comment: https://github.com/angular/angular-cli/issues/9194#issuecomment-360615868

I am closing and locking this issue to consolidate the conversation in the other issue.
