### ISSUE TITLE
1.5.1 build-optimizer "TypeError: candidate.value.definition is not a function"

### ISSUE THREAD

**Issue by mfrro** [angular/angular-cli#8571]
### Versions
```
Angular CLI: 1.5.1
Node: 6.11.4
OS: win32 x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.1
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.1
@schematics/angular: 0.1.5
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps
* run ng build --prod
* don't know what this could be related to, since my project is quite large

### Observed behavior
```
ERROR in main.c625bf1271eaaf6ccac7.bundle.js from UglifyJs
TypeError: candidate.value.definition is not a function
    at collapse (eval at <anonymous> (C:\github\web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:8275:61)
    at tighten_body (eval at <anonymous> (C:\github\web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:8110:17)
    at eval (eval at <anonymous> (C:\github\web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:12402:9)
    at AST_Node.eval [as optimize] (eval at <anonymous> (C:\github\web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:7481:23)
    at Object.before (eval at <anonymous> (C:\github\web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:7464:24)
    at AST_Node.eval [as transform] (eval at <anonymous> (C:\github\web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4559:35)
    at eval (eval at <anonymous> (C:\github\web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4688:43)
    at Object.before (eval at <anonymous> (C:\github\web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:7459:9)
    at AST_Node.eval [as transform] (eval at <anonymous> (C:\github\web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4559:35)
    at eval (eval at <anonymous> (C:\github\web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4679:43)
    at Object.before (eval at <anonymous> (C:\github\web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:7459:9)
    at AST_Node.eval [as transform] (eval at <anonymous> (C:\github\web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4559:35)
    at eval (eval at <anonymous> (C:\github\web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4590:31)
    at Object.before (eval at <anonymous> (C:\github\web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:7459:9)
    at AST_Node.eval [as transform] (eval at <anonymous> (C:\github\web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4559:35)
    at eval (eval at <anonymous> (C:\github\web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4578:25)
```
It worked with 1.5.0 with --build-optimizer and works with 1.5.1 when specifying --build-optimizer=false.

**Comment by sgibson53** [comment]
Having the same issue here using angular-cli 1.5.3
```ERROR in main.29fd47e17e9f3c8dea25.bundle.js from UglifyJs
TypeError: candidate.value.definition is not a function
    at collapse (eval at <anonymous> (C:\dev\Web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:8275:61)
    at tighten_body (eval at <anonymous> (C:\dev\Web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:8110:17)
    at eval (eval at <anonymous> (C:\dev\Web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:9710:9)
    at AST_BlockStatement.eval [as optimize] (eval at <anonymous> (C:\dev\Web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:7481:23)
    at Compressor.before (eval at <anonymous> (C:\dev\Web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:7464:24)
    at AST_BlockStatement.eval [as transform] (eval at <anonymous> (C:\dev\Web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:4559:35)
    at eval (eval at <anonymous> (C:\dev\Web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:4606:31)
    at Compressor.before (eval at <anonymous> (C:\dev\Web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:7459:9)
    at AST_For.eval [as transform] (eval at <anonymous> (C:\dev\Web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:4559:35)
    at eval (eval at <anonymous> (C:\dev\Web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:4578:25)
    at doit (eval at <anonymous> (C:\dev\Web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:134:23)
    at MAP (eval at <anonymous> (C:\dev\Web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:160:52)
    at do_list (eval at <anonymous> (C:\dev\Web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:4577:16)
    at eval (eval at <anonymous> (C:\dev\Web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:4674:25)
    at Compressor.before (eval at <anonymous> (C:\dev\Web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:7459:9)
    at AST_Function.eval [as transform] (eval at <anonymous> (C:\dev\Web\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:4559:35)```

**Comment by kzc** [comment]
This is an uglify bug: https://github.com/mishoo/UglifyJS2/issues/2497

**Comment by sgibson53** [comment]
Thanks @kzc for letting us know! Do you know how we might implement a workaround for angular cli? Doesn't look like it's straightforward (or even possible?) to pass uglify js options into the build process

**Comment by kzc** [comment]
As a temporary workaround for this bug you could add `collapse_vars: false` to the [uglify plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/README.md)'s [`compress` options](https://github.com/mishoo/UglifyJS2/tree/harmony#compress-options) in your webpack config.

In the case of `angular-cli` it would use a different syntax due to the way its webpack config file is structured. Try adding the following line after [this](https://github.com/angular/angular-cli/blob/7b4b2c78d4d4fa62d87777be55c8a123b6ab13a1/packages/%40angular/cli/models/webpack-configs/production.ts#L128):
```js
    uglifyCompressOptions.collapse_vars = false;
```
I'm not an Angular user. @filipesilva Could you please confirm this is the right place for this setting?

**Comment by filipesilva** [comment]
Hey @kzc, than you for letting us know! We don't expose Uglify options so this is hard to work around... The file you found is indeed the right place. 

For users that want a more CI friendly workaround, you can downgrade from 1.5.x to 1.4.x, since the latter uses `uglify-js` instead of `uglify-es` (I assume this bug is only on `uglify-es`).

**Comment by kzc** [comment]
The bug is present in both branches - latest `uglify-es@3` and `uglify-js@3`.

You might try using an older version of `uglify-es` in your npm or yarn lock file.

**Comment by pcwa-ahendricks** [comment]
@filipesilva it would be handy if the uglify options were exposed; we are already tweaking the `production.js` config for compatibility with another popular web mapping library.

**Comment by phihonhu** [comment]
I got this issue too on CLI 1.5.0.
How to override the **uglifyCompressOptions.collapse_vars** from cli project without webpack.config.js?

**Comment by poulad-rbc** [comment]
I am downgrading to `1.4.x`. :disappointed:

**Comment by kzc** [comment]
`uglify-es@3.2.0` was released with a fix for this issue. Please try it out.

**Comment by filipesilva** [comment]
@kzc awesome, thank you!

For users affected by this problem, here is how you can force your dependencies to use the `uglify-es@3.2.0`.

You can't just add it as a dependency with a new version since the `uglify-es` is not a direct dependency.

To see what version you have, run `npm list uglify-es`:
```
$ npm list uglify-es
master-project@0.0.0 D:\sandbox\master-project
`-- @angular/cli@1.5.3
  `-- uglifyjs-webpack-plugin@1.0.0
    `-- uglify-es@3.1.5
```

To force an indirect dependency to use a new version, you'll have to update your cache and remove the any package-locks you have. This series of commands should do it:
```
// Force update your cache
npm install uglify-es@3.2.0
npm uninstall uglify-es@3.2.0
// Remove node modules and package locks
rm -rf node_modules package-lock.json yarn.lock
// Reinstall dependencies
npm install
```

After all of this, you should be able to see the new version:
```
$ npm list uglify-es
master-project@0.0.0 D:\sandbox\master-project
`-- @angular/cli@1.5.3
  `-- uglifyjs-webpack-plugin@1.0.0
    `-- uglify-es@3.2.0
```

I realize this process is cumbersome. NPM does not offer a good way to force update indirect dependencies.

I've submitted a PR to update our direct dependency (`uglifyjs-webpack-plugin`): https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/176.

Then Angular CLI can update to that version and everyone gets the new version of `uglify-es` by default.
