### PR TITLE
fix(build): use baseUrl and paths from tsconfig

### PR DESCRIPTION
**Pull request by filipesilva**
Supersedes https://github.com/angular/angular-cli/pull/2210 https://github.com/angular/angular-cli/pull/2392 https://github.com/angular/angular-cli/pull/2428.

Uses same base mechanism as @abner's https://github.com/angular/angular-cli/pull/2210, but edits the new `webpack-build-typescript.ts` and adds tests.

Does NOT currently work for `--aot` (/cc @hansl).

### CODE REVIEW

**Comment by glipecki** [comment]
That's awesome ;) Thanks!

**Comment by abner** [comment]
Awesome!!!!

**Comment by MennoVS** [comment]
Great! However when I try to `ng serve`, it throws an error in `webpack-build-typescript.ts:5:17`:
```
Error: Cannot find module '@ngtools/webpack'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    ...
```
Has anyone else encountered this problem?

**Comment by arlowhite** [comment]
@filipesilva What issue can I follow that tracks support for --aot with `@app` tsconfig paths?

I use `@app` paths and `ng build -prod` is broken.

**Comment by altschuler** [comment]
@filipesilva Would you have any pointers as to what could be done as a workaround for aot support? Thanks!

**Comment by filipesilva** [comment]
@arlowhite @altschuler I'm not sure what the problem you are describing is, AFAIK TS paths work for aot. Can you open a new issue with a repro of what you're experiencing?

**Comment by arlowhite** [comment]
@filipesilva I'm not sure custom paths are the root cause. You can ignore my comment.

Just FYI...

My AOT build with `-prod` broke a while back ~1.0.0. At the time, the error message made me think it was related to my `@app` path in tsconfig.json. But I think it is unrelated. The `-prod` aot build seems to have become much more strict since **1.0.0**

I started to work on fixing the `-prod` build and made some progress. One issue was

```typescript
  animations: [
    trigger('fade', [
      state('hide' as FadeState, style({
```
The `as FadeState` cast doesn't work with AOT. The error was cryptic and I thought it was an issue with importing my `FadeState` type. Removing the cast fixes the import error I was seeing.

After fixing that, I got hundreds of errors reporting that Component fields were private that needed to be public for AOT. I haven't had time to work through those issues yet, so don't know if the build will actually work now.

**Comment by altschuler** [comment]
@filipesilva Please ignore, problem turned out to be something completely different, baseUrl and paths work great with aot :)

**Comment by filipesilva** [comment]
@arlowhite there was a bug pre-1.0 that was hiding a lot of AOT errors (like the private members), and was discussed https://github.com/angular/angular-cli/issues/5623. This did result in a lot more AOT errors being reported in 1.0. They were mostly 'real' AOT errors though, and a few that weren't were fixed.
