### ISSUE TITLE
Adding `includePaths` in the `stylePreprocessorOptions` seems to have no effect

### ISSUE THREAD

**Issue by vmasek** [angular/angular-cli#5798]
- [X] bug report
# Description
Adding `includePaths` in the `stylePreprocessorOptions` entry in `angular-cli.json`'s `apps` object seems to have no effect.

# Versions.
```
@angular/cli: 1.0.0
node: 6.10.0
os: linux x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1
@angular/language-service: 4.0.1
```
# Repro steps.
- ng new new-project --style=scss
- cd new-project
- create new `_variables.scss` in `src/styles`
- add the following to `src/styles/_variables.scss`: 
```scss
$some-variable: #fff;
```
- add the following to `src/app/app.component.scss`: 
```scss
@import 'variables';

h1 {
  color: $some-variable;
}
```
- add the following to `.angular-cli.json`'s `apps` property: 
```json
      "stylePreprocessorOptions": {
        "includePaths": [
          "styles"
        ]
      },
```
- run `ng serve`

## The error log 
```bash
ERROR in ./src/app/app.component.scss
Module build failed: 
@import 'variables';
^
      File to import not found or unreadable: variables.
Parent style sheet: stdin
      in ~/PROJECTS/new-project/src/app/app.component.scss (line 1, column 1)
 @ ./src/app/app.component.ts 56:17-48
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

# Desired functionality
https://github.com/angular/angular-cli/blob/5b1668f9ba39175e0f57fe23df6672ec40c3b745/docs/documentation/stories/global-styles.md

**Comment by efriandika** [comment]
it works for me..

**Comment by jgatjens** [comment]
it doesn't work for me :

```
angular/cli: 1.0.1
node: 6.9.5
os: darwin x64
@angular/animations: 4.1.0
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0
```

**Comment by procload** [comment]
I can reproduce the OP's problem. No matter how simple (I tried both with the `node_modules` folder and a folder inside my app) I try to make the `includePaths` property inside of `stylePreprocessorOptions`, I can't get it to work and it will always throw the `File to import not found or unreadable:` error.

**Comment by AlejandroMAL** [comment]
@jgatjens I still have the same issue, can you show us you angular-cli.json with the `stylePreprocessorOptions` to see how your configuration.

**Comment by jgatjens** [comment]
@AlejandroMAL it didn't work for me.

**Comment by tomchinery** [comment]
I'm having this issue as well, heres my the relevant part in angular-cli.json:
```
  "stylePreprocessorOptions": {
    "includePaths": [
      "./src/Assets/Scss/bourbon/bourbon",
      "Assets/Scss/neat/"
    ]
  }```

Note: Not sure if it was a relative or full path so tried both.

**Comment by realappie** [comment]
Im having the same issue, its really annoying. @filipesilva Any updates on this bug?

**Comment by vmasek** [comment]
@filipesilva I have updated the Angular CLI, tested on the new clean project and everything seems working for me now.

This is the project and commit that adds desired functionality.
https://github.com/vmasek/example-angular-cli-include-paths/commit/06b1731c59e794d2ff0921e4bde3bcd23717d5c5

I've also tested the `src` (`.`) and `styles` include paths. Both of them are working.

**Comment by filipesilva** [comment]
Closing then, thanks for getting back to me @vmasek.

**Comment by gdheller42** [comment]
I followed @filipesilva  example at https://github.com/vmasek/example-angular-cli-include-paths/commit/06b1731c59e794d2ff0921e4bde3bcd23717d5c5. srestarted ng serve it worked. Does not work if you do not restart ng serve

**Comment by realappie** [comment]
@filipesilva This doesn't want to work with a multi app setup :(

**Comment by filipesilva** [comment]
@realappie can you open a new issue with a reproduction so we can investigate?

**Comment by Jrubzjeknf** [comment]
@gdheller42 's comment is important here. You **must restart ng serve** after changing the .angular-cli.json, or you'll keep getting the compilation error.

**Comment by MickL** [comment]
@filipesilva Unfortunately this is not working on Angular CLI v1.3.0-rc.3. I copied your code with no success. Could you please retest? 

src/styles/_variables.scss
```
$grid-gutter-width-base: 30px;
```

.angular-cli.json
```
"stylePreprocessorOptions": {
        "includePaths": [
          ".",
          "styles"
        ]
      },
```

src/app.component.scss
```
.container-fluid {
	margin-bottom: $grid-gutter-width-base;
}
```

Webpack:
```
Module build failed: 
        margin-bottom: $grid-gutter-width-base;
               ^
Undefined variable: "$grid-gutter-width-base".
```

**Comment by Jrubzjeknf** [comment]
@MickL Did you import the _variables.scss with `@import '_variables';`?

**Comment by MickL** [comment]
Oh! So even when setting includePaths we have to import the files anyway?

**Comment by Splaktar** [comment]
@MickL correct.

**Comment by nhack** [comment]
@vmasek is it possible to put the code on github again? I'm struggling with angular-cli and sass and an example would be great.

Thanks!

**Comment by Jrubzjeknf** [comment]
MickL's example should be sufficient. Are you missing anything?

**Comment by nhack** [comment]
it seems to be working :) I've realized that it's a problem with IDEA, it doesn't recognize the imported file but if I do ng serve everything works fine.
