### ISSUE TITLE
broken imports (undefined) with update to CLI 1.5.0

### ISSUE THREAD

**Issue by jorgeucano** [angular/angular-cli#8389]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Angular CLI: 1.5.0
Node: 6.11.3
OS: darwin x64
Angular: 4.4.3
npm: 3.10.10

macOS High Sierra

### Repro steps.

update the CLI to 1.5.0

<pre>
npm uninstall --save-dev angular-cli
rm -rf node_modules dist
npm install --save-dev @angular/cli@latest
npm install
</pre>

### The log given by the failure.

I'm use <code> "auth0-js": "9.0.0-beta.5" </code> and work fine with "1.4.3", when update to 1.5.0

this import <code> import auth0 from 'auth0-js'; </code> it stops working, the code that worked now throws undefined.

<error>
core.es5.js:1020 ERROR TypeError: Cannot read property 'WebAuth' of undefined
</error>
When I use <code>new auth0.WebAuth(...)</code>

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by jorgeucano** [comment]
Hey @filipesilva sorry for the delay ... in the new version work fine ( after check and recheck the problem are the plugin) I close the issue thanks for all =)
