### ISSUE TITLE
Error: Cannot find module 'node-sass' after update "@angular-devkit/build-angular" from 0.7.3 to 0.7.4

### ISSUE THREAD

**Issue by DmitriyIvanko** [angular/angular-cli#11947]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Node.js: 8.11.4
npm: 5.6.0

### Repro steps

Just update "@angular-devkit/build-angular"  to 0.7.4;

### The log given by the failure

For any scss file:
ERROR in ./src/app/user/user-shared/data-map/data-map.component.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Projects\cli\cli-temp\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at loadLoader (C:\Projects\cli\cli-temp\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Projects\cli\cli-temp\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Projects\cli\cli-temp\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Projects\cli\cli-temp\node_modules\loader-runner\lib\LoaderRunner.js:173:18

### Desired functionality

No errors;
