### ISSUE TITLE
build prod command not working with 9.0.0-rc.1

### ISSUE THREAD

**Issue by elvirdolic** [angular/angular-cli#16132]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
 Yes, the previous version in which this bug was not present was: ....

### Description

After updating to --next with ng update @angular/core and @angular/cli I tried to run build prod

yarn ng build --project=x --prod

## 🔥 Exception or Error
<pre><code>
[error] TypeError: context.getProjectMetadata is not a function
    at Object.configureI18nBuild (C:\node_modules\@angular-devkit\build-angular\src\utils\i18n-options.js:70:36)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-rc.1
Node: 12.3.1
OS: win32 x64
Angular: 9.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.3
@angular-devkit/build-angular      0.900.0-rc.1
@angular-devkit/build-optimizer    0.900.0-rc.1
@angular-devkit/build-webpack      0.900.0-rc.1
@angular-devkit/core               9.0.0-rc.1
@angular-devkit/schematics         8.3.3
@angular/cdk                       9.0.0-rc.0
@angular/flex-layout               8.0.0-beta.26
@angular/material                  9.0.0-rc.0
@angular/material-moment-adapter   9.0.0-rc.0
@angular/pwa                       0.801.3
@ngtools/webpack                   9.0.0-rc.1
@schematics/angular                8.1.3
@schematics/update                 0.900.0-rc.1
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2
</code></pre>

**Anything else relevant?**
ng serve is working but there I got an different error after migration

we don't use angular i18n

**Comment by clydin** [comment]
The architect and schematic packages appear to be incorrect and outdated.

Are these present directly in the project?  These should generally not be present within the project’s package.json.

**Comment by elvirdolic** [comment]
There is no direct entry in package.json

**Comment by alan-agius4** [comment]
Can you please provide the output of:

```
npm ls @angular-devkit/architect
```

and also share you package.json?

Thanks.

**Comment by elvirdolic** [comment]
npm ls @angular-devkit/architect
![image](https://user-images.githubusercontent.com/17769458/68591196-6be20e00-0490-11ea-8a31-418e1c40a8f0.png)

package.json


```
 "dependencies": {
    "@angular/animations": "9.0.0-rc.1",
    "@angular/cdk": "9.0.0-rc.0",
    "@angular/common": "9.0.0-rc.1",
    "@angular/core": "9.0.0-rc.1",
    "@angular/flex-layout": "8.0.0-beta.26",
    "@angular/forms": "9.0.0-rc.1",
    "@angular/material": "9.0.0-rc.0",
    "@angular/material-moment-adapter": "9.0.0-rc.0",
    "@angular/platform-browser": "9.0.0-rc.1",
    "@angular/platform-browser-dynamic": "9.0.0-rc.1",
    "@angular/pwa": "^0.801.1",
    "@angular/router": "9.0.0-rc.1",
    "@angular/service-worker": "9.0.0-rc.1",
    "@ngrx/effects": "8.4.0",
    "@ngrx/entity": "8.4.0",
    "@ngrx/router-store": "8.4.0",
    "@ngrx/store": "8.4.0",
    "@ngrx/store-devtools": "8.4.0",
    "@ngui/map": "0.30.3",
    "@ngx-pwa/local-storage": "^8.0.0",
    "@ngx-translate/core": "11.0.1",
    "@ngx-translate/http-loader": "4.0.0",
    "@nrwl/angular": "8.7.0",
    "@swimlane/ngx-charts": "12.0.1",
    "angular-auth-oidc-client": "^10.0.8",
    "angulartics2": "7.5.2",
    "applicationinsights-js": "1.0.20",
    "base64-js": "^1.3.0",
    "canvg": "^2.0.0",
    "classlist.js": "1.1.20150312",
    "clipboard": "2.0.1",
    "core-js": "2.5.3",
    "d3": "5.7.0",
    "deep-equal": "1.0.1",
    "es6-promise": "^4.2.8",
    "file-saver": "1.3.8",
    "hammerjs": "2.0.8",
    "immer": "^3.1.1",
    "isomorphic-fetch": "^2.2.1",
    "lcov-result-merger": "^3.1.0",
    "lighthouse": "^4.0.0",
    "lodash": "^4.17.11",
    "marked": "^0.6.0",
    "mdn-polyfills": "5.5.0",
    "moment": "2.24.0",
    "ngx-cookie": "4.0.2",
    "ngx-gallery2-core": "3.3.1",
    "ngx-gallery2-lightbox": "3.3.1",
    "ngx-tinymce": "2.1.1",
    "ngx-toastr": "10.0.4",
    "normalizr": "3.2.4",
    "rxjs": "^6.5.3",
    "rxjs-tslint-rules": "4.7.2",
    "save-svg-as-png": "^1.4.7",
    "svg.js": "^2.6.5",
    "three": "^0.105.2",
    "tslib": "^1.10.0",
    "url-polyfill": "1.0.11",
    "zone.js": "0.10.2"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "8.2.0",
    "@angular-devkit/build-angular": "^0.900.0-rc.1",
    "@angular/cli": "9.0.0-rc.1",
    "@angular/compiler": "9.0.0-rc.1",
    "@angular/compiler-cli": "9.0.0-rc.1",
    "@angular/language-service": "9.0.0-rc.1",
    "@ngrx/schematics": "8.4.0",
    "@nrwl/cypress": "8.7.0",
    "@nrwl/jest": "8.7.0",
    "@nrwl/workspace": "8.7.0",
    "@types/applicationinsights-js": "1.0.7",
    "@types/base64-js": "^1.2.5",
    "@types/clipboard": "2.0.1",
    "@types/deep-equal": "1.0.1",
    "@types/file-saver": "2.0.0",
    "@types/googlemaps": "3.30.16",
    "@types/hammerjs": "2.0.36",
    "@types/jasmine": "~3.3.0",
    "@types/jasminewd2": "2.0.6",
    "@types/jest": "24.0.9",
    "@types/jquery": "3.3.6",
    "@types/lodash": "^4.14.42",
    "@types/marked": "^0.6.0",
    "@types/node": "^10.12.10",
    "@types/request": "^2.48.2",
    "@types/three": "^0.103.2",
    "argparse": "^1.0.10",
    "axios": "^0.18.0",
    "azure-devops-node-api": "^9.0.1",
    "codelyzer": "5.1.0",
    "cypress": "3.4.1",
    "cypress-file-upload": "3.3.2",
    "dotenv": "6.2.0",
    "htmlhint": "^0.11.0",
    "husky": "2.2.0",
    "jasmine-core": "~3.3.0",
    "jasmine-marbles": "^0.6.0",
    "jasmine-reporters": "^2.3.2",
    "jasmine-spec-reporter": "~4.2.1",
    "jest": "24.1.0",
    "jest-preset-angular": "7.0.0",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-cli": "2.0.0",
    "karma-coverage-istanbul-reporter": "~2.0.4",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "karma-junit-reporter": "^1.2.0",
    "karma-trx-reporter": "0.4.3",
    "lighthouse": "^4.0.0",
    "lint-staged": "^8.1.6",
    "ng-bullet": "^1.0.3",
    "prettier": "1.16.4",
    "prettier-stylelint": "0.4.2",
    "pretty-quick": "1.8.0",
    "stylelint": "^9.9.0",
    "stylelint-declaration-use-variable": "^1.7.0",
    "stylelint-regex": "^1.2.0",
    "stylelint-restrict": "^1.0.0",
    "stylelint-scss": "^3.4.0",
    "to-string-loader": "1.1.5",
    "ts-jest": "24.0.0",
    "ts-mocks": "^2.5.0",
    "ts-node": "~7.0.1",
    "tslint": "5.18.0",
    "tslint-config-prettier": "1.18.0",
    "tslint-sonarts": "1.9.0",
    "typescript": "3.6.4",
    "web-animations-js": "2.3.1",
    "webfont": "^8.2.0",
    "webpack-bundle-analyzer": "^3.3.2",
    "webpack-cli": "^3.0.8",
    "yauzl": "^2.10.0"
  }
}
```

**Comment by filipesilva** [comment]
If I had to bet, it's related to `@angular-builders/custom-webpack`. Are you using it for `ng build`? It might not support version 9 yet.

**Comment by elvirdolic** [comment]
Yes it's related to this, when I replace it with:  "builder": "@angular-devkit/build-angular:browser" build is running

**Comment by just-jeb** [comment]
Hi there, version 9 is not officially supported yet, but as far as I know there are no breaking changes in Architect v9, are they @alan-agius4 @clydin ? We ran a few sanity checks and `@angular-builders@8.x.x` worked with Angular 9 just well.
In any case I created an issue for tracking https://github.com/just-jeb/angular-builders/issues/624.
