### ISSUE TITLE
Cannot perform ng new after upgrade to 1.4.5 - Error: tree.branch is not a function

### ISSUE THREAD

**Issue by bniedermeyer** [angular/angular-cli#7979]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.5
node: 8.5.0
os: linux x64
```

### Repro steps.
- npm uninstall -g @angular/cli
- npm cache verify
- npm install -g @angular/cli@latest
- ng new my-project

### The log given by the failure.

Error: tree.branch is not a function
tree.branch is not a function

### Desired functionality.
After updating to v1.4.5 the user should be able to generate a new project.

**Comment by bniedermeyer** [comment]
Closing as restarting my terminal fixed the problem.
