### ISSUE TITLE
ng build fails after updating Angular Core to 12.0.4

### ISSUE THREAD

**Issue by CodeLiam** [angular/angular-cli#21101]
I just updated to Angular Core 12.0.4 but did not see an update for the CLI as of yet, but running ng build on a project that works with 12.0.3 it doesn't even attempt to build, here is the output.  I tried both PowerShell and Command Prompt on Windows 10

`C:\learn\duckr>ng build
An unhandled exception occurred: Cannot find module '@angular-devkit/build-webpack'
Require stack:
- C:\learn\duckr\node_modules\@angular-devkit\build-angular\src\browser\index.js
- C:\learn\duckr\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\learn\duckr\node_modules\@angular-devkit\architect\node\index.js
- C:\learn\duckr\node_modules\@angular\cli\models\architect-command.js
- C:\learn\duckr\node_modules\@angular\cli\commands\build-impl.js
- C:\learn\duckr\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\learn\duckr\node_modules\@angular-devkit\schematics\tools\index.js
- C:\learn\duckr\node_modules\@angular\cli\utilities\json-schema.js
- C:\learn\duckr\node_modules\@angular\cli\models\command-runner.js
- C:\learn\duckr\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\me\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\me\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
See "C:\Users\me\AppData\Local\Temp\ng-iZbOvE\angular-errors.log" for further details.

C:\learn\duckr>`

I wasn't sure if this was because of only having the Core updated, as the release to CLI 12.0.4 was not out when I ran the Core update.  I apologize if I filed this in the wrong section and it should have went in the Angular/Angular rather than CLI as I thought maybe it was more related to CLI

Here is a copy of the error log it mentions to see above

[error] Error: Cannot find module '@angular-devkit/build-webpack'
Require stack:
- C:\learn\duckr\node_modules\@angular-devkit\build-angular\src\browser\index.js
- C:\learn\duckr\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\learn\duckr\node_modules\@angular-devkit\architect\node\index.js
- C:\learn\duckr\node_modules\@angular\cli\models\architect-command.js
- C:\learn\duckr\node_modules\@angular\cli\commands\build-impl.js
- C:\learn\duckr\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\learn\duckr\node_modules\@angular-devkit\schematics\tools\index.js
- C:\learn\duckr\node_modules\@angular\cli\utilities\json-schema.js
- C:\learn\duckr\node_modules\@angular\cli\models\command-runner.js
- C:\learn\duckr\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\me\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\me\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\learn\duckr\node_modules\@angular-devkit\build-angular\src\browser\index.js:12:25)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)

**Comment by CodeLiam** [comment]
For the core, I ran
"ng update @angular/core"


     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 12.0.3
Node: 14.17.0
Package Manager: npm 7.16.0
OS: win32 x64

Angular: 12.0.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.3
@angular-devkit/build-angular   12.0.3
@angular-devkit/core            12.0.3
@angular-devkit/schematics      12.0.3
@angular/cli                    12.0.3
@schematics/angular             12.0.3
rxjs                            6.6.7
typescript                      4.2.4

**Comment by alan-agius4** [comment]
Can you please try to delete the `package-lock.json` and `node_modules` and do a fresh `npm install`?

**Comment by CodeLiam** [comment]
I just did as what you stated and it now serves and builds without issue.

I also ran "ng v" again and this is what it states for that

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 12.0.3
Node: 14.17.0
Package Manager: npm 7.16.0
OS: win32 x64

Angular: 12.0.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.3
@angular-devkit/build-angular   12.0.3
@angular-devkit/core            12.0.3
@angular-devkit/schematics      12.0.3
@angular/cli                    12.0.3
@schematics/angular             12.0.3
rxjs                            6.6.7
typescript                      4.2.4


I also had tested "ng update" just to check for a CLI update and it stated 

Using package manager: 'npm'
Collecting installed dependencies...
Found 27 dependencies.
    We analyzed your package.json and everything seems to be in order. Good work!
