### ISSUE TITLE
Cannot find module @angular/compiler/bundles/compiler.umd.js during migration after update to v12 using yarn

### ISSUE THREAD

**Issue by kasaharu** [angular/angular-cli#20837]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

Cannot find module '/path/to/node_modules/@angular/compiler/bundles/compiler.umd.js' during migration after update to v12 using yarn.
This issue does not appear if use npm instead of yarn.

## 🔬 Minimal Reproduction

```shell
$ yarn -v
1.22.10

$ npx @angular/cli@11 new ng-sample --package-manager yarn --strict --routing --style scss

$ cd ng-sample/

$ yarn ng update @angular/cli @angular/core
.....
❯ Updates Web Worker consumer usage to use the new syntax supported directly by Webpack 5.
  Migration completed.

An unhandled exception occurred: Cannot find module '/path/to/node_modules/@angular/compiler/bundles/compiler.umd.js'. Please verify that the package.json has a valid "main" entry
See "/private/var/folders/97/60cgj9ld76d3_kbq79bzqzj40000gn/T/ng-omlRzj/angular-errors.log" for further details.
error Command failed with exit code 127.
```

## 🔥 Exception or Error

<pre><code>
An unhandled exception occurred: Cannot find module '/path/to/node_modules/@angular/compiler/bundles/compiler.umd.js'.
</code></pre>

## 🌍 Your Environment

<pre><code>
yarn ng version
yarn run v1.22.10
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.0.0
Node: 14.15.1
Package Manager: yarn 1.22.10
OS: darwin x64

Angular: 12.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@schematics/angular             12.0.0
rxjs                            6.6.7
typescript                      4.2.4

✨  Done in 0.67s.
</code></pre>

**Anything else relevant?**

**Comment by janousek** [comment]
@kasaharu it is not bug. It is feature. Please read changelog: https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes

**Comment by alan-agius4** [comment]
> @kasaharu it is not bug. It is feature. Please read changelog: https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes

This is something different, the UMD bundle is still present, just the minified was removed.

**Comment by alan-agius4** [comment]
Hi @kasaharu, 

I tried the exact same steps you mentioned above, but I wasn't able to reproduce.

```
yarn ng update @angular/cli @angular/core
yarn run v1.22.10
$ ng update @angular/cli @angular/core
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via yarn.
Installed packages for tooling via yarn.
Using package manager: 'yarn'
Collecting installed dependencies...
Found 28 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/build-angular @ "12.0.0" (was "0.1102.13")...
    Updating package.json with dependency @angular/cli @ "12.0.0" (was "11.2.13")...
    Updating package.json with dependency @angular/compiler-cli @ "12.0.0" (was "11.2.14")...
    Updating package.json with dependency karma @ "6.3.2" (was "6.1.2")...
    Updating package.json with dependency typescript @ "4.2.4" (was "4.1.5")...
    Updating package.json with dependency @angular/animations @ "12.0.0" (was "11.2.14")...
    Updating package.json with dependency @angular/common @ "12.0.0" (was "11.2.14")...
    Updating package.json with dependency @angular/compiler @ "12.0.0" (was "11.2.14")...
    Updating package.json with dependency @angular/core @ "12.0.0" (was "11.2.14")...
    Updating package.json with dependency @angular/forms @ "12.0.0" (was "11.2.14")...
    Updating package.json with dependency @angular/platform-browser @ "12.0.0" (was "11.2.14")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "12.0.0" (was "11.2.14")...
    Updating package.json with dependency @angular/router @ "12.0.0" (was "11.2.14")...
  UPDATE package.json (1196 bytes)
✔ Packages installed successfully.
** Executing migrations of package '@angular/cli' **

❯ Remove deprecated options from 'angular.json' that are no longer present in v12.
  UPDATE angular.json (3956 bytes)
  Migration completed.

❯ Update 'zone.js' to version 0.11.x.
  Read more about this here: https://github.com/angular/angular/blob/master/packages/zone.js/CHANGELOG.md#breaking-changes-since-zonejs-v0111
  UPDATE package.json (1196 bytes)
  UPDATE src/polyfills.ts (2820 bytes)
  UPDATE src/test.ts (743 bytes)
  UPDATE src/environments/environment.ts (665 bytes)
✔ Packages installed successfully.
  Migration completed.

❯ Remove 'emitDecoratorMetadata' TypeScript compiler option.
  Decorator metadata is no longer needed by Angular.
  Read more about this here: https://www.typescriptlang.org/docs/handbook/decorators.html#metadata
  Migration completed.

❯ Lazy loading syntax migration.
  Update lazy loading string syntax to use dynamic imports.
  Migration completed.

❯ Remove deprecated ViewEngine-based i18n build and extract options.
  Options present in the configuration will be converted to use non-deprecated options.
  Migration completed.

❯ Updates Web Worker consumer usage to use the new syntax supported directly by Webpack 5.
  Migration completed.

** Executing migrations of package '@angular/core' **

❯ In Angular version 12, the type of ActivatedRouteSnapshot.fragment is nullable.
  This migration automatically adds non-null assertions to it.
  Migration completed.

❯ `XhrFactory` has been moved from `@angular/common/http` to `@angular/common`.
  Migration completed.

✨  Done in 52.14s.
```

**Comment by kasaharu** [comment]
Thank you for your confirmation!
I tried it on the another machine.
I wasn't able to reproduce on the another machine. hmm...

**Comment by kasaharu** [comment]
I tried updating to v12.0.1. The update to v12.0.1 was successful!
My problem has been resolved.
Thanks.
