### ISSUE TITLE
Compilation error after migrating from Angular 13 to 15

### ISSUE THREAD

**Issue by anandlingaraj** [angular/angular-cli#24972]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13

### Description

   > ng serve --proxy-config proxy.conf.json

****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
One or more browsers which are configured in the project's Browserslist configuration will be ignored as ES5 output is not supported by the Angular CLI.
Ignored browsers: kaios 2.5, op_mini all
✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size | Estimated Transfer Size
styles.css, styles.js | styles        | 398.39 kB |                57.87 kB
main.js               | main          | 118.77 kB |                29.05 kB
polyfills.js          | polyfills     | 118.77 kB |                29.04 kB
runtime.js            | runtime       |   1.25 kB |               681 bytes

                      | Initial Total | 637.17 kB |               116.61 kB

Build at: 2023-04-06T23:33:20.264Z - Hash: d96d42fe7f3c7221 - Time: 2443ms

Warning: 1 rules skipped due to selector errors:
  legend+* -> Cannot read properties of undefined (reading 'type')

./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.

./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.

Error: Failed to initialize Angular compilation - The target entry-point "angular-persistence" has missing dependencies:
 - rxjs/Rx

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

✖ Failed to compile.

### Minimal Reproduction

Angular 13 project , yarn upgrade angular to 15.

> ng serve --proxy-config proxy.conf.json

****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
One or more browsers which are configured in the project's Browserslist configuration will be ignored as ES5 output is not supported by the Angular CLI.
Ignored browsers: kaios 2.5, op_mini all
✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size | Estimated Transfer Size
styles.css, styles.js | styles        | 398.39 kB |                57.87 kB
main.js               | main          | 118.77 kB |                29.05 kB
polyfills.js          | polyfills     | 118.77 kB |                29.04 kB
runtime.js            | runtime       |   1.25 kB |               681 bytes

                      | Initial Total | 637.17 kB |               116.61 kB

Build at: 2023-04-06T23:33:20.264Z - Hash: d96d42fe7f3c7221 - Time: 2443ms

Warning: 1 rules skipped due to selector errors:
  legend+* -> Cannot read properties of undefined (reading 'type')

./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.

./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.

Error: Failed to initialize Angular compilation - The target entry-point "angular-persistence" has missing dependencies:
 - rxjs/Rx

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

✖ Failed to compile.

### Your Environment

```text
grumpysage > ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.2.5
Node: 14.21.1
Package Manager: yarn 1.22.19
OS: darwin x64

Angular: 15.2.6
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.5
@angular-devkit/build-angular   15.2.5
@angular-devkit/core            15.2.5
@angular-devkit/schematics      15.2.5
@angular/cli                    15.2.5
@ngtools/webpack                15.2.5
@schematics/angular             15.2.5
rxjs                            7.5.0
typescript                      4.8.2
```

**Comment by JoostK** [comment]
This particular line stands out to me:

> Error: Failed to initialize Angular compilation - The target entry-point "angular-persistence" has missing dependencies:
>
> rxjs/Rx

Note that `angular-persistence` was last released in 2017, whereas Angular 15 only officially supports libraries that have been built using Angular 13 to 15. I'd recommend to find an alternative for this dependency if it has gone unmaintained.

**Comment by alan-agius4** [comment]
Closing as per above.
