### ISSUE TITLE
Facing this issue while running ng serve  "core_1.Version is not a function"

### ISSUE THREAD

**Issue by abhinaypandey** [angular/angular-cli#3665]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by abhinaypandey** [comment]
Here is the cmd log after running ng serve 

core_1.Version is not a function
TypeError: core_1.Version is not a function
    at Object.<anonymous> (E:\kronos-timesheet\kronos-timesheet-front\node_modules\@angular\compiler-cli\src\version.js:18:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\kronos-timesheet\kronos-timesheet-front\node_modules\@angular\compiler-cli\index.js:24:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\kronos-timesheet\kronos-timesheet-front\node_modules\@ngtools\webpack\src\plugin.js:6:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\kronos-timesheet\kronos-timesheet-front\node_modules\@ngtools\webpack\src\index.js:6:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\kronos-timesheet\kronos-timesheet-front\node_modules\angular-cli\models\webpack-build-typescript.js:5:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\kronos-timesheet\kronos-timesheet-front\node_modules\angular-cli\models\webpack-config.js:2:34)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\kronos-timesheet\kronos-timesheet-front\node_modules\angular-cli\tasks\build-webpack.js:6:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\kronos-timesheet\kronos-timesheet-front\node_modules\angular-cli\commands\build.js:3:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Class.module.exports.includedCommands (E:\kronos-timesheet\kronos-timesheet-front\node_modules\angular-cli\addon\index.js:21:16)
    at E:\kronos-timesheet\kronos-timesheet-front\node_modules\angular-cli\lib\models\project.js:392:61
    at Array.forEach (native)
    at Project.addonCommands (E:\kronos-timesheet\kronos-timesheet-front\node_modules\angular-cli\lib\models\project.js:391:15)
    at Project.eachAddonCommand (E:\kronos-timesheet\kronos-timesheet-front\node_modules\angular-cli\lib\models\project.js:426:30)
    at module.exports (E:\kronos-timesheet\kronos-timesheet-front\node_modules\angular-cli\lib\cli\lookup-command.js:33:13)
    at CLI.<anonymous> (E:\kronos-timesheet\kronos-timesheet-front\node_modules\angular-cli\lib\cli\cli.js:34:26)
    at tryCatch (E:\kronos-timesheet\kronos-timesheet-front\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (E:\kronos-timesheet\kronos-timesheet-front\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (E:\kronos-timesheet\kronos-timesheet-front\node_modules\rsvp\dist\rsvp.js:521:7)
    at flush (E:\kronos-timesheet\kronos-timesheet-front\node_modules\rsvp\dist\rsvp.js:2373:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

**Comment by scttcper** [comment]
Lock your `@angular` packages to "2.3.1"

**Comment by abhinaypandey** [comment]
did that but after that getting Unmet peer dependency issues

+-- UNMET PEER DEPENDENCY @angular/common@2.3.1
+-- @angular/compiler@2.3.1
+-- UNMET PEER DEPENDENCY @angular/core@2.3.1
+-- @angular/http@2.3.1
+-- UNMET PEER DEPENDENCY @angular/platform-browser@2.3.1
+-- @angular/platform-browser-dynamic@2.3.1
+-- angular-cli@1.0.0-beta.19-3
| +-- @angular/common@2.1.2
| +-- @angular/compiler@2.1.2
| +-- UNMET PEER DEPENDENCY @angular/compiler-cli@2.1.2
| +-- UNMET PEER DEPENDENCY @angular/core@2.1.2
| `-- @angular/platform-browser@2.1.2
+-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
`-- UNMET PEER DEPENDENCY zone.js@0.6.26

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/core@2.3.1 requires a peer of rxjs@5.0.0-rc.4 but none was installed.
npm WARN @angular/core@2.3.1 requires a peer of zone.js@^0.7.2 but none was installed.
npm WARN @angular/http@2.3.1 requires a peer of rxjs@5.0.0-rc.4 but none was installed.
npm WARN @angular/router@3.1.2 requires a peer of @angular/core@2.1.2 but none was installed.
npm WARN @angular/router@3.1.2 requires a peer of @angular/common@2.1.2 but none was installed.
npm WARN @angular/router@3.1.2 requires a peer of @angular/platform-browser@2.1.2 but none was installed.
npm WARN @ngtools/webpack@1.1.9 requires a peer of @angular/compiler-cli@2.2.3 but none was installed.
npm WARN @ngtools/webpack@1.1.9 requires a peer of @angular/core@2.2.3 but none was installed.
npm WARN angular2-dynamic-component@0.0.50 requires a peer of @angular/core@~2.0.0 but none was installed.
npm WARN angular2-dynamic-component@0.0.50 requires a peer of @angular/common@~2.0.0 but none was installed.
npm WARN angular2-dynamic-component@0.0.50 requires a peer of @angular/compiler@~2.0.0 but none was installed.
npm WARN angular2-dynamic-component@0.0.50 requires a peer of @angular/platform-browser@~2.0.0 but none was installed.
npm WARN angular2-dynamic-component@0.0.50 requires a peer of @angular/http@~2.0.0 but none was installed.

**Comment by scttcper** [comment]
You're using "angular-cli@1.0.0-beta.19-3" which won't work with angular 2.3.x

**Comment by abhinaypandey** [comment]
thanks @scttcper . That worked like charm.

**Comment by bruno-serfe** [comment]
Hey guys I'm facing same issue with Angular 2.4.9.. any ideas?

`/modules/@angular/compiler-cli/src/version.ts:19
export const VERSION = new Version('2.4.9');
                       ^
TypeError: core_1.Version is not a function
    at Object.<anonymous> (/modules/@angular/compiler-cli/src/version.ts:19:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/modules/@angular/compiler-cli/index.ts:13:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/node_modules/src/main.ts:7:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/node_modules/src/plugin.ts:3:1)
`
