### ISSUE TITLE
Upgrade to typings 1.0.x

### ISSUE THREAD

**Issue by juergenzimmermann** [angular/angular-cli#816]
typings 1.0.x is available and has a different Directory structure compared with typings 0.9.x

**Comment by krimple** [comment]
Looks like the Angular CLI uses ^0.8.4...  So I guess ng will set it up right to start. But to install a typing for Markdown I had to install the typings tool.  

So I did an npm install -g typings and got the 1.0.4.  Once I figured out what was going on, I fixed temporarily by doing npm install -g typings@0.8.1 for now...  

Man JS development moves too fast. Was this something that everyone knew about or did it catch everyone out there by surprise?  My grey beard hairs are longing for a stable dependency management platform like Maven :)

I vote instead of Broccoli we move to a new build tool, BrusselsSprouts.

**Comment by vance** [comment]
yeah, need to change the default deps generator from `ambient` to `global`. 

{
 //change to "globalDevDependencies" 
  "ambientDevDependencies": {
    "angular-protractor": "registry:dt/angular-protractor#1.5.0+20160425143459",
    "jasmine": "registry:dt/jasmine#2.2.0+20160412134438",
    "selenium-webdriver": "registry:dt/selenium-webdriver#2.44.0+20160317120654"
  },
 //change to "globalDependencies" 
  "ambientDependencies": {
    "es6-shim": "registry:dt/es6-shim#0.31.2+20160317120654"
  }
}

**Comment by tomwanzek** [comment]
+1 for updating the generator for use with typings 1.x.x .

Note that, the changes for the generator should also cover impacts on `tsconfig.json`, as necessary. I.e. any `exclude` or `files` entry would now have to reference folders `typings/globals` and `typings/modules` and `index.d.ts.` as the main/browser related naming has been dropped.

`<reference path='...' />` statements would also have to change, if they are inserted by the generator into specific file templates.

**Comment by filipesilva** [comment]
Definitely needed. I'll take it on soon.

**Comment by juergenzimmermann** [comment]
Please consider also that typescript@next provides the new `@types` mechanism as an alternative to the fragile `typings 1.0` vs `typings 0.8` vs `tsd`.
Using typescript@next you can install e.g. the .d.ts file for lodash: `npm install --save-dev @types/lodash`
https://www.npmjs.com/~types

**Comment by kylecordes** [comment]
Adding on to the above, I noticed that Angular itself is also moving to the new "@types" mechanism, so I think it is important for the CLI to follow along as soon as practical.

By the way, there is remarkably little easily findable information about how to consume the new mechanism yet. Someone has been hard at work pushing lots of typings into the new mechanism, it's not yet clear how to consume them back out as conveniently as the old mechanism would.

**Comment by tomwanzek** [comment]
@kylecordes your point about consumption of "@types" definitions seems to be related to the now closed issue [Built-in support for UMD module definitions #7125](https://github.com/Microsoft/TypeScript/issues/7125) for the typescript 2.0 milestone.

**Comment by juergenzimmermann** [comment]
Using "*@types*" is pretty easy: you just use npm like ` npm install --save-dev @types/lodash`. When you you also use `typescript@next` then you are done.

**Comment by filipesilva** [comment]
We're actually holding off on the typing 1.0 upgrade for now, because we're aiming at moving directly to `@types` and don't want to do two typings related breaking changes in a row.

**Comment by filipesilva** [comment]
I recently tried updating the CLI directly to `@types/`, and turns out that can't really be done right now for typings that have dependencies. So I'm reopening this issue for action.

**Comment by MarkPieszak** [comment]
Hey @filipesilva how've you been? 
Where can I find some info on @types, was going to upgrade universal to typings 1.x but might wait to go to @types if that's what you guys are doing for the CLI

**Comment by filipesilva** [comment]
@MarkPieszak I couldn't find any specific info on using `@types/` *right now* (TS1.0), but rather just tried to do `npm install @types/lib-name` and work with that. 

On the CLI projects specifically, I edited `src/typings.d.ts` (a file we keep to list all typings), removed `/// <reference path="../typings/browser.d.ts" />` and added in direct imports like `/// <reference path="../../node_modules/@types/lib-name/index.d.ts" />`. 

This worked to a certain extend, but on libs that depended on other libs (like protractor), there is some new syntax and compilation failed.

A couple days go https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/ came out, which talks a bit about how it would work with TS2.0.

**Comment by filipesilva** [comment]
Made obsolete by #1455, which includes `@types/*` support.
