### ISSUE TITLE
`ng help generate` does not work in 1.0.0-beta.14

### ISSUE THREAD

**Issue by denofevil** [angular/angular-cli#2142]
1. OS: OS X, 10.11.6

2. Versions: angular-cli: 1.0.0-beta.14
node: 6.5.0

3. STR: Generate a new application, cd in the application folder, run `ng help generate`

4. I'm getting `You cannot use the help command inside an angular-cli project.` instead of the available blueprints list

**Comment by hansl** [comment]
Confirmed it's a bug, fixing right now. SHouldn't take long.

**Comment by bougnat12** [comment]
'ng help' does not work too with this message :
Cannot find module './build.d'
Error: Cannot find module './build.d'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/angular-cli/commands/help.js:28:33
    at Array.reduce (native)
    at Class.run (/usr/local/lib/node_modules/angular-cli/commands/help.js:26:39)
    at Class.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/asap.js:82:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by hansl** [comment]
Fixed by #2146

**Comment by denofevil** [comment]
@hansl I've checked 1.0.0-beta.14 and help works better indeed. However `ng help generate` used to provide a list of available blueprints, now it doesn't. Should I file another issue?
