### ISSUE TITLE
Clarify node version requirement

### ISSUE THREAD

**Issue by kylecordes** [angular/angular-cli#1918]
Currently, the README says a few things about Node and NPM versions:

"The generated project has dependencies that require Node 4.x.x and NPM 3.x.x."
"When you ng serve remember that the generated project has dependencies that require Node 4 or greater."

It would be helpful if this were clarified in several ways:
- The two statements above disagree. Do they require specifically 4.x? Or do they work with 4.0.0 or greater? How much greater?
- Is there a recommendation, beyond these mere requirements?
- The statements in the README appear to pertain only to the generated project. This leaves a bit of vagueness as to what requirements might pertain to Angular-CLI itself.

Possibly helpful info:

I work at "Angular Boot Camp" where we field questions about this stuff from a new batch of developers coming into Angular for the first time, very frequently. They commonly ask things like:
- "I'm still using Node 0.12, because we never upgrade anything ever, are you sure it won't work? Can I try it and see how far I get?" Because of this kind of question, I suggest enforcing requirements as part of running the tool, not only mentioning them in the README.
- "We just finally got everything upgraded to Node 6, are you saying I need to downgrade to use CLI?"
- "I am on 6.0.0, does it work?"  (I happen to know the answer is no, or at least, not unless you want to work around some other problems. Likewise, I suspect but have not tested that CLI does not work with any 4.x.x, but rather it requires 4.something.something or higher)

**Comment by christiandreher** [comment]
Since `x` is a variable, 4.x.x could also be 4.0.0 with `x=0`, couldn't it? I personally didn't find this information misleading

**Comment by kylecordes** [comment]
@christiandreher  Yes, I believe it is misleading because it implies that 4.0.0  will work, and I believe that is not actually the case. He would be one way to clarify it. Find out what node version or versions CLI is put through its test suite on, and publish that as a list of known okay versions.

**Comment by christiandreher** [comment]
Sorry, I kind of misread your question, I edited my first post. Well, I have not tried 4.0.0, but if you say that it doesn't work, then it is misleading of course and should be fixed

**Comment by SeekingMonkey** [comment]
I had no luck until I moved Node to 6.5 and Typescript 2.0.  Good to know that Node 6.3 will work.  My assumption is that the README will be updated once these first few hiccups are worked out.

**Comment by christiandreher** [comment]
I should note that I am actually working on node 6.3.1. I couldn't recall the point release when I was writing this comment. My server runs on node 6.4.0, and it also works by the way.

**Comment by chalin** [comment]
FYI, as I just pointed out in https://github.com/angular/angular-cli/issues/1873#issuecomment-244624725, I'm able to side step the `Cannot find module './models/config'` issue using v5 (5.12.0) by invoking `ng` commands via npm scripts.

cc @ericjim

**Comment by filipesilva** [comment]
Would you be willing to make a PR that updates the README requirements?

**Comment by CarreraPHP** [comment]
Fixed in #2534.
