### ISSUE TITLE
After upgrade to v12.2.5 and removal of node-sass ng test fails 

### ISSUE THREAD

**Issue by GabeRivera** [angular/angular-cli#21752]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

After updating to version 12.2.5, when i run ng test, it fails as it cannot find node-sass. Which i had removed because the CLI was warning me it was going to be removed and i should migrate to Sass (dart-sass), which I did. 

## 🔬 Minimal Reproduction
Upgrade to version 12.2.5
ng test
ERROR

I made no other changes to the test code or anything, just upgraded. Everything was working fine before hand.

## 🔥 Exception or Error

<pre><code>
An unhandled exception occurred: Error in config file!
 Error: Cannot find module 'node-sass'
Require stack:
- /Users/gabriel.rivera/Projects/fcskyui-library/node_modules/karma-scss-preprocessor/dist/lib/index.js
- /Users/gabriel.rivera/Projects/fcskyui-library/projects/fcsky-shared-library/karma.conf.js
- /Users/gabriel.rivera/Projects/fcskyui-library/node_modules/karma/lib/config.js
- /Users/gabriel.rivera/Projects/fcskyui-library/node_modules/karma/lib/server.js
- /Users/gabriel.rivera/Projects/fcskyui-library/node_modules/karma/lib/index.js
- /Users/gabriel.rivera/Projects/fcskyui-library/node_modules/@angular-devkit/build-angular/src/karma/index.js
- /Users/gabriel.rivera/Projects/fcskyui-library/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /Users/gabriel.rivera/Projects/fcskyui-library/node_modules/@angular-devkit/architect/node/index.js
- /Users/gabriel.rivera/Projects/fcskyui-library/node_modules/@angular/cli/models/architect-command.js
- /Users/gabriel.rivera/Projects/fcskyui-library/node_modules/@angular/cli/commands/test-impl.js
- /Users/gabriel.rivera/Projects/fcskyui-library/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/gabriel.rivera/Projects/fcskyui-library/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/gabriel.rivera/Projects/fcskyui-library/node_modules/@angular/cli/utilities/json-schema.js
- /Users/gabriel.rivera/Projects/fcskyui-library/node_modules/@angular/cli/models/command-runner.js
- /Users/gabriel.rivera/Projects/fcskyui-library/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng
See "/private/var/folders/lp/96kny5n10sxfygnzkywk0sth0000gq/T/ng-bE04ow/angular-errors.log" for further details.

</code></pre>

## 🌍 Your Environment

<pre><code>
{
  "name": "fcsky-shared-library",
  "version": "0.0.0",
  "scripts": {
    "preinstall": "npx npm-force-resolutions",
    "ng": "ng",
    "start": "npm run get-lib-version && ng serve -o",
    "serve-mac": "npm run get-lib-version && node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng serve",
    "serve-mac-ngrok": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng serve --disable-host-check",
    "build-lib": "ng build fcsky-shared-library",
    "build-tester": "ng build fcskyui-tester --prod",
    "build-watch": "ng build fcsky-shared-library --watch",
    "test": "ng test --browsers Chrome --code-coverage",
    "test-ci": "ng test  --browsers ChromeHeadlessCI --code-coverage --watch=false",
    "test-watch": "ng test --watch",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "npm-pack": "cd dist/fcsky-shared-library && npm pack",
    "package": "npm run get-lib-version && npm run build-lib && npm run npm-pack",
    "build-pack": "npm run package && npm run build-tester",
    "all": "npm run package && npm run start",
    "get-lib-version": "./replace-lib-version",
    "precommit": "run-s format:fix lint && ng test --watch=false",
    "format:fix": "pretty-quick --staged",
    "format:check": "prettier --config ./.prettierrc --list-different \"projects/fcsky-shared-library/src/lib/**/*{.ts,.js,.json,.scss,.html,.scss}\"",
    "format:lib": "prettier --config ./.prettierrc --write \"projects/fcsky-shared-library/src/lib/**/*{.ts,.js,.json,.scss,.html,.scss}\"",
    "sonar": "sonar-scanner"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.2.5",
    "@angular/cdk": "^12.2.5",
    "@angular/common": "~12.2.5",
    "@angular/compiler": "~12.2.5",
    "@angular/core": "~12.2.5",
    "@angular/flex-layout": "^12.0.0-beta.34",
    "@angular/forms": "~12.2.5",
    "@angular/localize": "^12.2.5",
    "@angular/material": "^12.2.5",
    "@angular/material-moment-adapter": "^12.2.5",
    "@angular/platform-browser": "~12.2.5",
    "@angular/platform-browser-dynamic": "~12.2.5",
    "@angular/router": "~12.2.5",
    "@cloudinary/angular-5.x": "^1.3.3",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@tinymce/tinymce-angular": "^4.2.0",
    "@types/file-saver": "^2.0.1",
    "angular-resize-event": "^2.1.0",
    "bootstrap": "^4.5.3",
    "chart.js": "^2.9.4",
    "cloudinary-core": "^2.11.3",
    "core-js": "^2.5.4",
    "dhtmlx-gantt": "file:packages/gantt_7.0.1_ultimate",
    "file-saver": "^2.0.2",
    "fp-ts": "^2.9.5",
    "googleapis": "^64.0.0",
    "jquery": "^3.4.1",
    "leaflet": "^1.7.1",
    "leaflet.markercluster": "^1.4.1",
    "lodash-es": "^4.17.21",
    "moment": "^2.29.1",
    "ng2-pdf-viewer": "7.0.1",
    "ngx-ui-switch": "^11.0.1",
    "popper.js": "^1.16.0",
    "postcss-loader": "^4.0.4",
    "rxjs": "~6.6.3",
    "scroll-into-view-if-needed": "^2.2.24",
    "smoothscroll-polyfill": "^0.4.4",
    "tinymce": "5.0.15",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.2.5",
    "@angular/cli": "~12.2.5",
    "@angular/compiler-cli": "~12.2.5",
    "@angular/language-service": "~12.2.5",
    "@types/jasmine": "^3.6.1",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "husky": "^2.2.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.4",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "karma-scss-preprocessor": "^4.0.0",
    "ng-packagr": "^12.2.1",
    "node-sass-tilde-importer": "^1.0.2",
    "npm-force-resolutions": "0.0.3",
    "npm-run-all": "^4.1.5",
    "prettier": "^1.17.0",
    "pretty-quick": "^1.10.0",
    "protractor": "~7.0.0",
    "sonar-scanner": "^3.1.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.1.0",
    "typescript": "~4.3.5"
  },
  "resolutions": {
    "webpack": "^5.0.0"
  }
}
</code></pre>

<pre><code>
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "fcsky-shared-library": {
      "root": "projects/fcsky-shared-library",
      "sourceRoot": "projects/fcsky-shared-library/src",
      "projectType": "library",
      "prefix": "fcsky-shared",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:build",
          "options": {
            "tsConfig": "projects/fcsky-shared-library/tsconfig.lib.json",
            "project": "projects/fcsky-shared-library/ng-package.json",
            "assets": [
              "src/assets",
              {
                "glob": "*/*",
                "input": "src/assets",
                "output": "assets/"
              }
            ]
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/fcsky-shared-library/src/test.ts",
            "tsConfig": "projects/fcsky-shared-library/tsconfig.spec.json",
            "karmaConfig": "projects/fcsky-shared-library/karma.conf.js"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "projects/fcsky-shared-library/tsconfig.lib.json",
              "projects/fcsky-shared-library/tsconfig.spec.json"
            ],
            "exclude": ["**/node_modules/**"]
          }
        }
      }
    },
    "fcskyui-tester": {
      "root": "projects/fcskyui-tester/",
      "sourceRoot": "projects/fcskyui-tester/src/",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/fcskyui-tester",
            "index": "projects/fcskyui-tester/src/index.html",
            "main": "projects/fcskyui-tester/src/main.ts",
            "polyfills": "projects/fcskyui-tester/src/polyfills.ts",
            "tsConfig": "projects/fcskyui-tester/tsconfig.app.json",
            "allowedCommonJsDependencies": [
              "fp-ts/lib/pipeable",
              "fp-ts/lib/Option",
              "cloudinary-core",
              "chart.js",
              "css-element-queries",
              "ng2-pdf-viewer",
              "file-saver"
            ],
            "assets": [
              "projects/fcskyui-tester/src/favicon.ico",
              "projects/fcskyui-tester/src/assets",
              {
                "glob": "**/*",
                "input": "projects/fcsky-shared-library/src/assets",
                "output": "./assets"
              },
              {
                "glob": "**/*",
                "input": "node_modules/tinymce/skins",
                "output": "/tinymce/skins/"
              },
              {
                "glob": "**/*",
                "input": "node_modules/tinymce/themes",
                "output": "/tinymce/themes/"
              },
              {
                "glob": "**/*",
                "input": "node_modules/tinymce/plugins",
                "output": "/tinymce/plugins/"
              }
            ],
            "styles": [
              "node_modules/bootstrap/scss/bootstrap.scss",
              "projects/fcskyui-tester/src/styles.scss",
              "node_modules/dhtmlx-gantt/codebase/dhtmlxgantt.css",
              {
                "input": "projects/fcsky-shared-library/src/assets/css/styles.scss"
              }
            ],
            "scripts": ["node_modules/jquery/dist/jquery.js"]
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "projects/fcskyui-tester/src/environments/environment.ts",
                  "with": "projects/fcskyui-tester/src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "8mb",
                  "maximumError": "15mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ]
            },
            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
          },
          "defaultConfiguration": "production"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "aot": true
          },
          "configurations": {
            "production": {
              "browserTarget": "fcskyui-tester:build:production"
            },
            "development": {
              "browserTarget": "fcskyui-tester:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "fcskyui-tester:build"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": ["projects/fcskyui-tester/tsconfig.app.json", "projects/fcskyui-tester/tsconfig.spec.json"],
            "exclude": ["**/node_modules/**"]
          }
        }
      }
    },
    "fcskyui-tester-e2e": {
      "root": "projects/fcskyui-tester-e2e/",
      "projectType": "application",
      "prefix": "",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "projects/fcskyui-tester-e2e/protractor.conf.js"
          },
          "configurations": {
            "production": {
              "devServerTarget": "fcskyui-tester:serve:production"
            },
            "development": {
              "devServerTarget": "fcskyui-tester:serve:development"
            }
          },
          "defaultConfiguration": "development"
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "projects/fcskyui-tester-e2e/tsconfig.e2e.json",
            "exclude": ["**/node_modules/**"]
          }
        }
      }
    }
  },
  "defaultProject": "fcsky-shared-library",
  "schematics": {
    "@schematics/angular:component": {
      "style": "scss"
    }
  }
}

</code></pre>

Thank you in advance for your time! Much appreciated.

**Comment by alan-agius4** [comment]
It seems like you are using `karma-scss-preprocessor`, this is not needed with the Angular CLI. Removing this should solve the issue.
