### ISSUE TITLE
Using AWS cognito with 1.4.x does not work

### ISSUE THREAD

**Issue by wolfpaq** [angular/angular-cli#7794]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

Starting with the 1.4.x versions of angular-cli, I am not able to use the AWS cognito libraries. It has worked with all the 1.2.x and 1.3.x versions.

### Versions.
@angular/cli: 1.4.3
node: 6.11.1
os: linux x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4

### Repro steps.
`$ ng new aws-ng-cli-test`
`$ cd aws-ng-cli-test`
`$ npm install --save aws-sdk amazon-cognito-identity-js`

Add the following to the "apps" section of .angular-cli.json

```
      "scripts": [
        "../node_modules/aws-sdk/dist/aws-sdk.js",
        "../node_modules/amazon-cognito-identity-js/dist/aws-cognito-sdk.js",
        "../node_modules/amazon-cognito-identity-js/dist/amazon-cognito-identity.js"
      ],
```

`$ ng serve`

Open the page in the browser and see the following error message in the console:

> scripts.bundle.js:126805 Uncaught Error: Cannot find module 'function webpackUniversalModuleDefinition(root, factory) {
> 	if(typeof exports === 'object' && typeof module === 'object')
> 		module.exports = factory(require("aws-sdk/global"), require("aws-sdk/clients/cognitoidentityserviceprovider"));
> 	else if(typeof define === 'function' && define.amd)
> 		define(["aws-sdk/global", "aws-sdk/clients/cognitoidentityserviceprovider"], factory);
> 	else if(typeof exports === 'object')
> 		exports["AmazonCognitoIdentity"] = factory(require("aws-sdk/global"), require("aws-sdk/clients/cognitoidentityserviceprovider"));
> 	else
> 		root["AmazonCognitoIdentity"] = factory(root["AWSCognito"], root["AWSCognito"]["CognitoIdentityServiceProvider"]);
> }'
>     at s (scripts.bundle.js:126805)
>     at scripts.bundle.js:145560

Because of that error, none of the cognito functionality is available.

**Comment by sandangel** [comment]
do not include like that. take a look at this example from aws lab [aws-cognito-angular2-quickstart](https://github.com/awslabs/aws-cognito-angular2-quickstart)

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
