### ISSUE TITLE
AOT build produces applications unable to lazy load modules

### ISSUE THREAD

**Issue by slmyers** [angular/angular-cli#2452]
```
angular-cli: 1.0.0-beta.16
node: 6.0.0
os: linux x64
```

reproduction repo can be found [here](https://github.com/slmyers/test-lazy-aot)
### The log given by the failure.

```
main.cfeed71….bundle.js:547 EXCEPTION: Uncaught (in promise): Error: Cannot find module 
'app/lazy/lazy.module.ngfactory'.
```

It seems that `aot` option can not build project that lazily loads modules. I would hope that one could use the patterns in the official documentation -- which I believe I'm doing -- and use the `-- aot` option to compile your app easily. I would appreciate any clarification as to whether this is an issue with the `CLI` or with the compiler. Thanks.

**Comment by slmyers** [comment]
###update 

I think the LazyModule may not have been compiled, because there is a `0.map` but no `0.chunk.js` in the dist folder. 

![lazy_no_chunk](https://cloud.githubusercontent.com/assets/6344732/19018159/02f5c0b8-8814-11e6-93ba-ea72aac5b081.png)

**Comment by Delagen** [comment]
#2112 seems aot process does not polished. I issue system_js_loader in ngfactory ((

**Comment by splintercode** [comment]
I have this same issue as well. I dont have a repo to show yet but I get the same error as above.

```
angular-cli: 1.0.0-beta.16
node: 6.4.0
os: win32 x64
```

```
main.166efb8….bundle.js:1494 Unhandled Promise rejection: Cannot find module 'app/account/account.module.ngfactory'. ; Zone: angular ; Task: Promise.then ; Value: Error: Cannot find module 'app/account/account.module.ngfactory'.(…) Error: Cannot find module 'app/account/account.module.ngfactory'.
```

**Comment by achimha** [comment]
I have the same problem and also don't see compiled code for the lazy modules, only the .ngfactory.ts file.

**Comment by filipesilva** [comment]
In `beta.16` the `--aot` flag was still experimental. Can you repro in `beta.17`?

**Comment by Delagen** [comment]
@filipesilva the same error. No changes in the main function in beta16->beta17 upgrade. 
The only changes is NgcWebpackPlugin -> AotPlugin rename and some cleanup in plugin arguments.

**Comment by achimha** [comment]
With b17 I still don't get the lazy route modules compiled by `ng build --prod --aot`. There isn't even an ngfactory file, just a main bundle. For some reason the `loadChildren` does not trigger the compilation.

I have a file `app/src/lazy/lazy.routes.ts`:
```
export const lazyRoutes: Routes = [
    {
        path: 'signup',
        loadChildren: 'app/lazy/signup/signup.module#SignupModule'
    }
];
```
This route definition is part of the main route definition in `app/app-routing.module.ts`:
```
const routes: Routes = [
    {
        path: '',
        component: FrontpageComponent
    },
    {
        path: 'login',
        component: LoginComponent
    },
    ...lazyRoutes,
    {
        path: '**',
        component: NotFoundComponent
    },
];

@NgModule({
    imports: [RouterModule.forRoot(routes)],
    exports: [RouterModule],
    providers: []
})
export class FrontendRoutingModule {
}
```
I tried changing the `loadChildren` paths to be relative but then the JIT version throws as well, it has to start with `app/`.

**Comment by tomwanzek** [comment]
Just tested a project with beta.17. Build/serve without `--aot` work without issues w.r.t. lazy-loading, regardless of whether `prod` is used or not.

When I use `ng serve --aot`:
Upon initial load the error message below appears in chrome debugger:
![error_1](https://cloud.githubusercontent.com/assets/16323903/19253778/a8a01082-8f1b-11e6-9bb9-7a37297aad3c.PNG)

While the initial screens seem to work regardless, hitting the lazy-loaded route throws an error, because the module ngFactory cannot be found.

One additional note, when I build with `--aot` the code chunk is not generated for the lazy route in the dist folder, however, there is a `map` file which seems to correspond to it.

**Comment by mattlewis92** [comment]
This error is also present in the [demo app](https://github.com/angular/angular-cli/tree/master/tests/e2e/assets/webpack/test-app) - webpack builds the project ok, but as soon as you click the `lazy` link, this error is thrown: 

```Uncaught (in promise): Error: Cannot find module './lazy.module.ngfactory'.```

**Comment by drejohnson** [comment]
I get the error `HomeModule is not an NgModule`

`home.module.ts`
```
const HomeRoutes: Routes = [
  {
    path: '',
    component: HomeComponent,
    pathMatch: 'full'
  }
];

@NgModule({
  imports: [
    CommonModule,
    RouterModule.forChild(HomeRoutes)
  ],
  declarations: [HomeComponent]
})
export class HomeModule { }
```

`app.module.ts`
```
export const Routes = [
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: 'home', loadChildren: 'app/home/home.module#HomeModule' },
  { path: 'about', loadChildren: 'app/about/about.module#AboutModule' }
];

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    RouterModule.forRoot(Routes)
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by Rosseyn** [comment]
v1.0.0-beta-16 wouldn't let me compile, but beta-17 completed successfully.
I'm able to serve dev with great improvement in speed, but can't `ng serve --prod --aot` after `ng build --prod --aot` and still have the app fully load. Currently it only loads as far as the initial Loading... splash, and doesn't go any further, no errors in console.

**Comment by tony-fanbeat** [comment]
Any updates on this issue?

We have a large app that was originally written against beta-17.  I recently moved it over to the Angular2 release and hooked up the ng compiler to take advantage of AoT compilation, but as of now I haven't found a way to leverage both AoT and lazy loading.  As mentioned above, it will compile fine but when navigating to the lazy route it throws an error that 'lazy.module.ngfactory' could not be found

AoT is a killer feature and made a noticeable difference in our boot time, but at this point our --prod build still send down ~2.2mb all at once and we would love to cut that down by lazy loading some of our lesser-used routes

**Comment by tomwanzek** [comment]
I just upgraded the project I tested with `beta.17` to `beta.18`. As mentioned above, I am encountering the same failure modes:
* project build and serve are fine _without_ `--aot` (regardless of `dev` or `prod`)
* project compiles without errors _with_ `--aot`. However, the chunks for the lazy modules are not emitted in `js`. There is, oddly enough, again a partial `0.map` without any corresponding `js` file.

**Comment by Rajat421** [comment]
same error anybody with solution please comment

**Comment by naveedahmed1** [comment]
Any update on this?

**Comment by MrCroft** [comment]
Very strange... I've just tried `ng build --aot` with cli beta.18 on the last 3 releases of Angular:
On 2.1.0 I get: `Cannot read property 'parse' of undefined`
On 2.1.1 I get: `this.compiler.compileModules is not a function`
On 2.1.2 I get: `Cannot read property 'transitiveModules' of undefined`

This is unrelated to lazy loading (doesn't matter if I have a lazy module or not).
Just `ng new` and then:
1. change angular version in package.json
2. delete node_modules/@angular
3. `npm cache clean` (maybe not necessary, but it's kind of a reflex already)
4. npm install
5. `ng build --aot`

In fact, even on the same example I gave in my post above (https://github.com/MrCroft/lazy) with the same Angular version (2.1.0) and same node/cli versions, I don't get `LazyModule is not an NgModule` anymore :| I get `Cannot read property 'parse' of undefined` now. Without changing anything, except uninstalling/installing different versions of Angular before going back to 2.1.0 again (but removed node_modules/@angular and running npm cache clean every time).

```
angular-cli: 1.0.0-beta.18
node: 6.9.1
os: win32 x64
```

**Comment by Delagen** [comment]
@MrCroft  transitiveModules is the options of codegen function, if options does not provided then it undefined and cause this error
source code from compiler-cli part
https://github.com/angular/angular/blob/master/modules/%40angular/compiler-cli/src/main.ts#L23

**Comment by MrCroft** [comment]
@Delagen Alright. I was expecting that `ng new` + `ng build --aot` would simply **just work** with some defaults, without any extra options... Since I didn't do anything else myself and no 3rd party or anything else... An aot guide would be useful, maybe there actually is one, I just didn't search for one yet. I will do that next.

**Comment by sgybas** [comment]
I have created a new project using angular-cli beta.19-3 and just added a lazy route to reproduce the problem: https://github.com/sgybas/angular-cli-2452

`ng serve` works fine, `ng serve --aot` does not. The browser console shows
`Error: Cannot find module './lazy/lazy.module.ngfactory'.`

`ng build --prod` works fine, two bundles are created. `ng build --prod --aot` creates the main bundle but the second chunk is not created.

Is there anything I can do the help resolve the issue?

**Comment by achimha** [comment]
Could the maintainers provide us with some feedback regarding the AOT/lazy issues please? It'd be very helpful to know what we should expect.

**Comment by filipesilva** [comment]
@achimha all I can say is that we're working as fast as possible to get it fixed. It's our top priority atm really.

**Comment by naveedahmed1** [comment]
@filipesilva can you please confirm, when fixed should it also help overcome the memory errors that we encounter when compiling large project without lazy loading? Such the one referenced here https://github.com/angular/angular/issues/12184

**Comment by tony-fanbeat** [comment]
Thanks for the update @achimha. I'm sure this is no small issue to work on and look forward to being able to leverage both AoT and lazy loading in our production app

**Comment by unsafecode** [comment]
Is there a way to leverage lazy-load routes with AoT today? I'm using `@ngtools/webpack` and lazy routes are not recognized unless I also use `angular2-router-loader`. In this case, components are not precompiled anyway...

**Comment by JohannesRudolph** [comment]
A big shout out to @hansl  and @filipesilva for making this work in angular-cli 1.0.0-beta.20-4. You guys rock! I appreciate all the effort that goes into fixing the tooling so that angular devs can focus on building applications, not build infrastructure 👍

**Comment by ctrl-brk** [comment]
I'm still getting `AppModule is not an NgModule` in beta.20-4 using ng build -prod -aot

**Comment by Dunos** [comment]
Me too (well, not AppModule but the lazy module name instead), dunno how to solve it

**Comment by MrCroft** [comment]
Yes, same thing here `MyLazyLoadedModule is not and NgModule`

```
@angular: 2.2.1
angular-cli: 1.0.0-beta.20-4
node: 6.9.1
os: win32 x64
```

**Comment by naveedahmed1** [comment]
I can confirm Lazyloading with AoT is working properly in latest release of Angular-Cli

Those having issues could try creating routing module and add to imports of AppModule.
```

import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';

@NgModule({
    imports: [
        RouterModule.forRoot([
            { path: '', loadChildren: 'app/home/home.module#HomeModule' },
            { path: 'lazyLoadedFeature', loadChildren: 'app/lazyLoadedFeature/lazy-loaded-feature.module#LazyLoadedFeatureModule' },
        ]
        )
    ],
    exports: [
        RouterModule
    ]
})
export class AppRoutingModule { }

```

**In Lazy loaded module define its routing as a separate module and import in the child module.**

```
import { FeatureListComponent } from './feature-list.component';
import { FeatureDetailsComponent } from './feature-details.component';

@NgModule({
    imports: [
        RouterModule.forChild([
            {
                path: '', component: FeatureListComponent,
                children: [
                    { path: 'details/:id', component: FeatureDetailsComponent },
                ]
            }
        ])
    ],
    exports: [
        RouterModule
    ]
})
export class LazyLoadedFeatureRoutingModule { }
```

**Comment by MrCroft** [comment]
Thank you @naveedahmed1 
With that change in my code, `ng build --aot` works, no more errors in the build process.

**But** when browsing through the app, as soon as I try to access a link that needs to load a lazy module, I get:
EXCEPTION: Uncaught (in promise): Error: Cannot find module 'app/user/user.module.ngfactory'.
Error: Cannot find module 'app/user/user.module.ngfactory'.
Maybe I'll try StackOverflow, hopefully it's not a bug, but just something I'm doing wrong.

**Comment by naveedahmed1** [comment]
Make sure you are using latest version of cli. Can you try generating a new project using latest version of cli, then copy code in your src folder to the new project's src folder, compile and check if it works.

**Comment by MrCroft** [comment]
@naveedahmed1 
My bad... I didn't think there was any difference between previous version and the latest (except only under the hood). I did an `ng init` now, overwrote all the files and then put back from history whatever needed to have my old app back. The simple one (the repo) works now! Thank you!
The other app - I still don't know what that error means and what I'm doing wrong. I've tried on gitter, hopefully someone knows.

**Comment by jvitor83** [comment]
@MrCroft and @naveedahmed1, the key change was the
```
    "baseUrl": "",
```
inside the `tsconfig.json`.
The packages updates + this line solve the `LazyModule is not an NgModule` error at build.

**Comment by maxime1992** [comment]
I can confirm that I've just upgraded to **angular-cli 1.0.0-beta.20-4** and lazy loading is working with AOT <3 ! Big shout out for the team :) !!

**Comment by maxime1992** [comment]
I found a problem when running `--prod` without `--aot` : Lazy loaded modules are no longer lazy loaded. Am I the only one to have that problem ? https://github.com/angular/angular-cli/issues/3267

**Comment by tomwanzek** [comment]
@maxime1992 my lazy loading works fine with `ng serve --prod` with beta.21. Unfortunately, I can only partially validate with `--aot`. It compiles and serves the first lazy route without issues :smile: Then I run into the first `@Effect` custom decorator which is stripped out due to #2799  :cry:

Theory of Constraints in action :wink:

**Comment by maxime1992** [comment]
Hi @tomwanzek ! Today is your lucky day :) 
I had exactly the same problem and I made a fork (like 5h ago)  of angular-cli that doesn't strip out decorators! Just take a look at the end of #2799 ;) I tried it and it's working fine for me. I also added a bundle size comparison and it's way better than I could imagine. Only +7kb on main bundle. I thought keeping decorators would have a huge impact on bundle size.

**Comment by unsafecode** [comment]
HTH, I set up a demo repo to summarize how to make lazy routes work with `@ngtools/webpack`

https://github.com/unsafecode/ng2-aot

**Comment by born2net** [comment]
I am also getting the same error of:
```
Error: No module factory available for dependency type: ContextElementDependency
```
and also using lazy loaded modules...
any ideas?

```
angular-cli: 1.0.0-beta.26
node: 6.9.4
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/language-service: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.2.1
@angular/compiler-cli: 2.4.5
```


Regards,

Checkout the Ultimate Angular 2 Boorstrap App: @ http://ng2.javascriptninja.io
Source@ https://github.com/born2net/ng2Boilerplate

**Comment by filipesilva** [comment]
@born2net I haven't seen that `ContextElementDependency` error in a few months now, I didn't think we had it anymore. 

Can you open a new issue with a repo I can debug in?

**Comment by born2net** [comment]
I cleared node_modules, rebuilt project and some clean ups and now gone, so ok so far
thanks,
Sean

**Comment by imVinayPandya** [comment]
i have faced same issue but i solved it by doing following 2 things:

i have added `./` as prefix of html and css in every component file.

i am also using lazy loaded modules, so was exporting module class as default i removed default from
`export default class AdminModule`
and i have added 

`{ path: 'dashboard',
            loadChildren: 'app/admin/dashboard/dashboard.module#DashboardModule' },` 

and its working for me.

**Comment by IAMtheIAM** [comment]
No solution???

**Comment by Rosseyn** [comment]
This has been fixed for quite some time now. Update angular and angular
cli. Don't have to mess with the generator anymore either.

**Comment by wbhob** [comment]
I'm experiencing a regression with Angular 5.0.0-rc.9 and CLI v1.5.0-rc.8

**Comment by Rosseyn** [comment]
Could you give more info?

Are you getting an error? Is it completing without issue but not lazy
loading?

One thing you do need to make sure of when lazy loading prod builds now is
to include @Component({ moduleId: module.id }) in all of your components.

**Comment by wbhob** [comment]
Woah what is that @Rosseyn I have never seen the moduleId thing

**Comment by Rosseyn** [comment]
It's been around for a long while but doesn't seem to show up much in
documentation. Recently set up a new project and after enabling lazy load,
had to find this out the hard way for myself.

Does it solve the issue you're encountering?

**Comment by andresmino** [comment]
Hi all! Do you have any update on this issue? I've tried all workaround suggested but none of those worked for me.

**Comment by wbhob** [comment]
In Angular v5, what I've found is you can't terminate the file name with `.ts`.

So if your RoutingModule is AuthRoutingModule in `./auth/auth-routing.module.ts`, your `loadChildren` would be `'./auth/auth-routing.module#AuthRoutingModule`.

**Comment by michaelkrone** [comment]
When updating to from Angular 4 to Angular 5 i kept getting
```
ERROR in Error: Could not resolve module [module path] relative to [routing module path]
```
for lazy loaded modules. Removing the `.ts` suffix as @wbhob suggested works.

**Comment by ctaepper** [comment]
@wbhob you are my hero! was that mentioned anywhere in breaking changes???

**Comment by MrCroft** [comment]
I had no idea it ever worked **with** the extension. I've never put the extension, as far as I can remember (at least since they've moved the CLI to webpack, so way back before even ending v2 releases and moving to Angular v3 I think). And I don't remember even seeing an example with the extension in the official docs, so there would be no deprecation to be mentioned.
But I could be wrong, if my memory isn't as good as I think it is.
