### ISSUE TITLE
Build is not kicking off in a browser on save

### ISSUE THREAD

**Issue by kuncevic** [angular/angular-cli#4338]
### OS
Windows 10.

### Versions.
```
angular-cli: 1.0.0-beta.28.3
node: 6.9.2
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/flex-layout: 2.0.0-beta.4
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
```

### Repro steps.

Migrate from beta.24 to beta.28.3
Modify any file
Click save
Chrome dev console saying:
```
[WDS] App updated. Recompiling...
[WDS] Nothing changed.
```
The new build is not kicking off

So had to stop and reastart `ng serve` manually

**Comment by BondiGeek** [comment]
Same issue here.

**Comment by idc1407** [comment]
same issue here

**Comment by jwuliger** [comment]
Hello. I am having the same problem. Every change I make to ANY file causes me to end the command and do `ng serve` just to see the changes.

**Comment by ramesh-yadav** [comment]
Same issue. Recompile is not working properly.

**Comment by clement-jacquet** [comment]
Hello, I have the same issue but ONLY with pipes, version beta 26

**Comment by abeagley** [comment]
Same issue here on Win 10

**Comment by MTechDE** [comment]
Beta 28 is broken af...

**Comment by WouterSpaak** [comment]
This issue seems to affect new .ts files or changes in any .ts files as well. Template changes in .html files update, but underlying script files do not.

**Comment by idc1407** [comment]
when i tried to save with visual studio 2015 community edition,   It is working.    But working with VS Code there is a problem.

**Comment by liongoncalves** [comment]
im having this same issue in win10

**Comment by legit** [comment]
Same issue here...

**Comment by Meligy** [comment]
Anybody tried beta 29?

**Comment by Meligy** [comment]
Note that beta 29 comes with a new package name `@angular/cli` instead of `angular-cli`.

**Comment by PierreDuc** [comment]
`@angular/cli` has the same problem. Changes are not detected. Especially difficult when a full rebuild takes more than 30 seconds

**Comment by PierreDuc** [comment]
Anybody else having a hard time reverting back to beta 26? I've gotten so far as to remove all node_modules global, local and cache and reverting to what I know was a working state of my project, but still no changes are detected when I run `ng serve`.

**Comment by Meligy** [comment]
hmm..

On Mac OS latest and NPM 6.x latest, I was able to get a new beta.29 project to detect changes to:

- A pipe used in `app.component.html`
- `app.component.html` itself
- The title property in `app.component.ts`

Could this be OS related or upgrade related?

Any concrete steps to reproduce on a new project?

**Comment by legit** [comment]
`npm install --save @ngtools/webpack@1.2.4 `
seems to have fixed it for me.
thanks to @beeman for his solution in #4329.

**Comment by Meligy** [comment]
That explains why it works for me. The version I get on a new project is `@ngtools/webpack@1.2.6`.

**Comment by intellix** [comment]
Yep. There was an issue previously with webpack 1.2.5 which was fixed in 1.2.6 a couple of hours ago. A new angular-cli wasn't released, just a new version of @ngtools/webpack, so make sure you've got that guys

**Comment by PierreDuc** [comment]
Well, that explains why reverting to an old version doesn't work. Older cli versions will still download the new webpack version

**Comment by aprades** [comment]
It still doesn't work for me. Started new project, and still same issue.

angular-cli: 1.0.0-beta.28.3
node: 6.9.5
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
@ngtools/webpack: 1.2.6

**Comment by legit** [comment]
@aprades cd to your project and run `npm install --save @ngtools/webpack@1.2.4` in that directory

**Comment by oberoivarun** [comment]
@aprades Delete @ngtools/webpack from node_modules. Then

`npm install --save @ngtools/webpack@1.2.4` as @legit posted a little above.

**Comment by MTechDE** [comment]
He did, as you can se in his ng --version log `@ngtools/webpack: 1.2.6`

**Comment by oberoivarun** [comment]
@MTechDE we are telling him to go back to an earlier version of the module. 1.2.6 is the latest. Go back to 1.2.4!!

**Comment by aprades** [comment]
Ok, it doesn't work with @ngtools/webpack@1.2.6

With @ngtools/webpack@1.2.4 it works fine.

**Comment by legit** [comment]
Great @aprades!

**Comment by niklas-dahl** [comment]
I freshly installed angular-cli `npm uninstall -g angular-cli && npm i -g angular-cli` and im getting the following warnings:
```
npm WARN optional Skipping failed optional dependency /angular-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.17
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/compiler@2.0.2 but none was installed.
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/platform-server@2.0.2 but none was installed.
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/core@2.0.2 but none was installed.
npm WARN @angular/core@2.4.5 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/core@2.4.5 requires a peer of zone.js@^0.7.2 but none was installed.
```

Trying `ng --version` gives me a lot of `Cannot find module 'reflect-metadata'` Errors.
Is this related to the restructuring of the cli packages?

Previously it worked just fine.

**Comment by RicardoVaranda** [comment]
@niklas-dahl The new npm name for the project is @angular/cli try:

npm install -g @angular/cli

**Comment by lukichev** [comment]
Thanks, @aprades. Installing @ngtools/webpack@1.2.4 resolved my issue.

**Comment by niklas-dahl** [comment]
@RicardoVaranda that worked, but installing `angular-cli` should still work I guess,,

**Comment by RicardoVaranda** [comment]
@niklas-dahl I believe it installs beta 28.3 instead of 29 if you use angular-cli.

**Comment by emazv72** [comment]
Same as #4355 but replacing  angular-cli: 1.0.0-beta.28.3 with @angular/cli: 1.0.0-beta.29 

>$ npm show @ngtools/webpack version
>1.2.6

**Comment by MickL** [comment]
I don't see any release for beta 29. Latest is 28. How can this work?

**Comment by hneuer** [comment]
@MickL try this: https://www.npmjs.com/package/@angular/cli

**Comment by MickL** [comment]
Is this issue fixed for beta 29?

**Comment by hneuer** [comment]
I dont know, I just wanted to point you to the current beta

**Comment by aprades** [comment]
I don't have the issue with beta 29.
The install procedure has changed a bit:
npm install -g @angular/cli@latest

**Comment by jloosli** [comment]
For what it's worth, it still doesn't work in beta 29 for me, but reverting to @ngtools/webpack@1.2.4 does work

**Comment by web-dave** [comment]
`ng v`
--
angular-cli: 1.0.0-beta.28.3
node: 6.9.2
os: win32 x64
--
`npm uninstall -g angular-cli`
`npm cache clean`
`npm i -g @angular/cli@latest`
...
`ng v`
--
@angular/cli: 1.0.0-beta.29
node: 6.9.2
os: win32 x64
--
ng new multimodule --routing--style=scss
--
cd multimodule
--
npm i -S @ngtools/webpack@1.2.4
--
Works fine!

**Comment by kuncevic** [comment]
just got `@angular/cli: 1.0.0-beta.29` in current project locally installed:
`npm run ng build` stuck at 16%

after `npm i -S @ngtools/webpack@1.2.4` `ng build` getting stuck at 47%

Any thoughts?

dependencies": {
    "@angular/common": "2.4.5",
    "@angular/compiler": "2.4.5",
    "@angular/core": "2.4.5",
    "@angular/flex-layout": "2.0.0-beta.4",
    "@angular/forms": "2.4.5",
    "@angular/http": "2.4.5",
    "@angular/material": "2.0.0-beta.1",
    "@angular/platform-browser": "2.4.5",
    "@angular/platform-browser-dynamic": "2.4.5",
    "@angular/router": "3.4.5",
    "@ngrx/core": "1.2.0",
    "@ngrx/effects": "2.0.0",
    "@ngrx/router-store": "1.2.5",
    "@ngrx/store": "2.2.1",
    "@ngrx/store-devtools": "3.2.2",
    "@ngtools/webpack": "^1.2.4",
    "@swimlane/ngx-datatable": "5.0.0",
    "@types/lodash": "4.14.44",
    "core-js": "2.4.1",
    "hammerjs": "2.0.8",
    "lodash": "4.17.2",
    "material-design-icons": "3.0.1",
    "moment": "^2.17.1",
    "ng2-adal": "0.2.6",
    "ngrx-store-freeze": "0.1.6",
    "powerbi-client": "^2.2.3",
    "reselect": "2.5.4",
    "rxjs": "5.1.0",
    "ts-helpers": "1.1.2",
    "whatwg-fetch": "^2.0.2",
    "zone.js": "0.7.6"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-beta.29",
    "@angular/compiler-cli": "2.4.5",
    "@types/jasmine": "2.5.38",
    "@types/node": "6.0.62",
    "@types/whatwg-fetch": "0.0.33",
    "codelyzer": "2.0.0-beta.4",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-remap-istanbul": "0.2.2",
    "protractor": "4.0.14",
    "ts-node": "1.2.1",
    "tslint": "4.4.2",
    "typescript": "2.0.10"
  }

**Comment by kuncevic** [comment]
I've got in another trouble using beta.29 https://github.com/angular/angular-cli/issues/4380
So I just rolled back to beta.28.3 for now + `npm install @ngtools/webpack@1.2.6` on top of it

**Comment by kuncevic** [comment]
I can confrim that the recent beta.30 fixing the issue

rimraf node_modules 
npm install @angular/cli@latest

**Comment by emazv72** [comment]
@kuncevic same issue here, npm clean,  reinstalled beta.30 and tested on a new blank project.
Major issue, I'm going to revert to beta.28.3
Too bad because performance improved a lot in the last cycle.

**Comment by raducostea** [comment]
For me, right now it only works with "@angular/cli@1.0.0-beta.30" and @ngtools/webpack@1.2.4

**Comment by MarkWilsoncom** [comment]
@web-dave: tried your fix and now get the following on calling ng serve:

Cannot find module 'rxjs/symbol/observable'
Error: Cannot find module 'rxjs/symbol/observable'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at globalScope (C:\Users\Media\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular\core\bundles\core.umd.js:7:85)
    at Object.<anonymous> (C:\Users\Media\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular\core\bundles\core.umd.js:10:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

Output from ng v:

@angular/cli: 1.0.0-beta.30
node: 6.9.4
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/compiler-cli: 2.4.6
@ngtools/webpack: 1.2.4

**Comment by grunk** [comment]
@MarkWilsoncom did you update your package.json with the modified name ?
"angular-cli": "^1.0.0-beta.28.3", becomes "@angular/cli": "1.0.0-beta.30",

**Comment by cassianomon** [comment]
`"@ngtools/webpack": "1.2.4"` worked here

**Comment by MarkWilsoncom** [comment]
@grunk: no - good point.
Just updated and still get the same error.

Dependencies in package.json:

"dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "@ngtools/webpack": "^1.2.4",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.30",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }

Just trying to get a really basic example up and running...

**Comment by raducostea** [comment]
@MarkWilsoncom 
npm uninstall angular-cli --save
npm install @angular/cli@lastest --save
npm install @ngtools/webpack@1.2.4 --save

This worked for me.

**Comment by RicardoVaranda** [comment]
Make sure you delete your node_modules folder within your projects also, this step is often overlooked.

**Comment by kuncevic** [comment]
@MarkWilsoncom `"angular-cli": "1.0.0-beta.30",` should be `"@angular/cli": "1.0.0-beta.30"`,

**Comment by MarkWilsoncom** [comment]
@raducostea : thx - works!
@kuncevic: hmm - only thing I thought manually changed was "30"... thx anyway

Just getting started with angular 2 - great to see a helpful and responsive community - thx people :-)

**Comment by cassianomon** [comment]
It need to be `"@ngtools/webpack": "1.2.4"` at package.json and **NOT** "@ngtools/webpack": "^1.2.4"

**Comment by emazv72** [comment]
package.json temporary fix for beta.30
 
 "devDependencies": {
    "@angular/cli": "1.0.0-beta.30",
...
    "@ngtools/webpack" : "1.2.4"
}

Looks like something is broken after 1.2.4

**Comment by rkajbaf** [comment]
Downgrading @ngtools/webpack to 1.2.4 works for me as well.

**Comment by web-dave** [comment]
beside all the error confimations. Compiling is damn fast!!!
💋

**Comment by JiriBalcar** [comment]
@web-dave Maybe it is damn fast because it does not compile any typescript ;-)

**Comment by web-dave** [comment]
i mean with the fixed compiluing!!

**Comment by JiriBalcar** [comment]
Yes but with @ngtools/webpack@1.2.4 the lazyloaded bundles are not generated if you use `import * as ` somewhere in your code (even in node_modules).

**Comment by ctrl-brk** [comment]
I haven't noticed any significant speed increase.

**Comment by raducostea** [comment]
I can see an about 2s improvement. I get a 2-3 seconds build time on save. Previously i was getting 4-5 seconds before.

**Comment by MickL** [comment]
When will there be a release? Im waiting for this every day :)

**Comment by raducostea** [comment]
This was already fixed for me in the latest @angular/cli

**Comment by MickL** [comment]
In beta 30? I didn't see it in the changelog tho.

**Comment by raducostea** [comment]
https://github.com/angular/angular-cli/commit/9fcf10a89b0995c2da606fbbe5a341d42044654b 

I removed node_modules, i've ran npm install and https://github.com/angular/angular-cli/commit/9fcf10a89b0995c2da606fbbe5a341d42044654b  is present in the build already.

**Comment by MickL** [comment]
In master, but not in beta 30 :/

**Comment by JiriBalcar** [comment]
It is in latest @ngtools/webpack. And I think, that @angular/cli always
install the latest version.

**Comment by abdo0** [comment]
Thanks @legit for solving my issue

**Comment by slubowsky** [comment]
Seems to be fixed for dev mode but still broken if use ng --aot --prod (didnt' try just one).

Using a number that I keep incrementing to see what gets displayed it looks like somehow its serving up what was two compilations behind. i.e. starting at 0 at incrementing by 1, I see 1 when last saved and compiled change was 3, and 2 when last change was 4, etc..

**Comment by ulymor** [comment]
I faced with the same problem on **Ubuntu 16.04** and angular CLI **1.0.0-beta.30**

The problem was related with Inotify Watches Limit on Linux.
To solve to issue I increased  the watches limit to 512K
```
sudo sysctl fs.inotify.max_user_watches=524288
sudo sysctl -p --system
```
After that I restarted my IDE (WebStorm in my case) and after that the change detection started to work.

**Comment by AlainD-** [comment]
@ulymor you'd probably be interested in this comment https://github.com/angular/angular-cli/issues/2389#issuecomment-278913860 :-), as apparently modifying the inotify settings as so would use a large amount of RAM for nothing.

**Comment by lihaibh** [comment]
installing "@ngtools/webpack": "1.2.4" does work but the compilation is extreamly slow, why?

**Comment by chebum** [comment]
@lihaibh No wonder since you installed older version. That's probably #1980. That version had problems that were fixed later. Please try that instead:
To revert webpack back to 1.2.12:
`npm install -D @ngtools/webpack@latest`

Installing angular-cli locally for the project solved the problem for me.
`npm install -D @angular/cli@latest`

This should solve both problems.

**Comment by crosma** [comment]
I'm still experiencing this issue. I'm building an a freshly updated Rasberry Pi 3 Model B.

@angular/cli: 1.0.0
node: 7.8.0
os: linux arm
@angular/cli: 1.0.0
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/compiler-cli: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@ngtools/webpack: 1.3.0

It always catches that a file changes and rebuilds and sometimes works but eventually stops reflecting changes browser side. Once it stops working, it requires restarting ng serve to fix it.

**Comment by sandangel** [comment]
same issue here:
OS: Arch Linux
@angular/cli: 1.0.0
```package.json
{
  "name": "client",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}
```

**Comment by themroc5** [comment]
I had the same issue but got it working!

My setup: A virtual machine running Linux with shared folders to Windows, coding in PhpStorm.
My solution: Disabling the option _Use "safe write"_ under _Appearance / System Settings_

**Comment by aaronhoffman** [comment]
Thought I should add this here. This is an open PR linked to by other issues similar to this one. It may contain a resolution for others still having this issue. https://github.com/angular/angular-cli/pull/4009

**Comment by abalad** [comment]
@themroc5 Thank you. It was well this problem that was also happening through WebStorm, now it worked.

**Comment by Bsujeet** [comment]
hey i am new to angular just created new project as told in quick start.
But ng serve is not recompiling.
i tried all the things that are mentioned above.
but still not working,
My current version of @angular/cli is 1.1.1 and webpack is 1.4.

when i install webpack 1.2.4 it gives error while compiling.

**Comment by nitinshk1111** [comment]
I am also facing the same issue. ng serve is not getting reloaded when changes made in a particular directory Model. Apart from those Model classes it is detecting the changes..
I ran the command ng --version and got this result..

@angular/cli: 1.3.2
node: 6.11.2
os: win32 x64
@angular/animations: 4.4.3
@angular/cdk: 2.0.0-beta.11
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/material: 2.0.0-beta.11
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.3.2
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3

Please help me to fix this issue..

**Comment by mhyeganeh** [comment]
@themroc5 Thank you very much! After two days spending on this problem, finally solved and I had no idea it was all about phpStrom !

**Comment by web-dave** [comment]
@mhyeganeh I find this issue very often in my workshops.

**Comment by chapultepec** [comment]
`sudo ng serve` works for me!

**Comment by clydin** [comment]
@chapultepec Please do not repeatedly cross-post the same message.

Also, advocating running a command as root as a general solution opens up the user to potential security implications.  `sudo` should only be used when root permissions are absolutely required.

**Comment by chapultepec** [comment]
@clydin sorry i was trying to help because the issue is repeated.
So if using sudo is not the best solution wich could be the solution?
