### ISSUE TITLE
after upgrade to 20 tests fail

### ISSUE THREAD

**Issue by sysmat** [angular/angular-cli#30413]
### Command

update

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

19

### Description

1. After running `ng update @angular/core@20 @angular/cli@20` 
2. Then `npm run test` I get error

```
 Error: Cannot find module '@angular-devkit/build-angular/plugins/karma'
```

### Minimal Reproduction

npm run test

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI: 20.0.0
Node: 22.15.1
Package Manager: npm 10.9.2
OS: win32 x64

Angular: 20.0.0
... animations, build, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1902.13
@angular-devkit/core         19.2.13
@angular-devkit/schematics   19.2.13
@schematics/angular          20.0.0
ng-packagr                   20.0.0
rxjs                         7.8.2
typescript                   5.8.3
zone.js                      0.15.1
```

### Anything else relevant?

I'm using karma.conf.js `frameworks: ['jasmine', '@angular-devkit/build-angular'],
`
