### ISSUE TITLE
Error: Cannot find module 'internal/util/types'

### ISSUE THREAD

**Issue by Devansh3790** [angular/angular-cli#11700]
### ng help throw error (mark with an `ng help`)
```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at evalmachine.<anonymous>:44:26
    at Object.<anonymous> (/usr/lib/node_modules/angular-cli/node_modules/yam/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [x] help
- [ ] version
- [ ] doc
```

### Versions

 `node --version`
v10.6.0

`npm --version`
6.2.0

`ng --version`

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at evalmachine.<anonymous>:44:26
    at Object.<anonymous> (/usr/lib/node_modules/angular-cli/node_modules/yam/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```

Currently, I am using Ubuntu 14.04 LTS, I tried to start working on Angular 6 so for that i follow the steps to upgrade angular-cli and after updating that getting this error while trying to running any angular-cli command on terminal.

Note - Previously I had node - v8.2.1 which I also upgraded to v10.6.0.

I did only these things.

Thanks in advance.

**Comment by Devansh3790** [comment]
Issue resolved when I installed node v8.9.0. It seems like the issue with the v10.x.x.

**Comment by bhemeswararao** [comment]
how to change the node version on windows

**Comment by DaSchTour** [comment]
For me this doesn't work with v8.9.0
