### ISSUE TITLE
Ng13 upgrade -> build issue

### ISSUE THREAD

**Issue by spock123** [angular/angular-cli#22185]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

After upgrading from v12 to v13, I'm getting errors when making a build.

### Please provide the exception or error you saw

```true
[error] Error: Cannot find module 'webpack-sources'
Require stack:
- /Users/lrj/project/fastorder/admin/node_modules/license-webpack-plugin/dist/WebpackAssetManager.js
- /Users/lrj/project/fastorder/admin/node_modules/license-webpack-plugin/dist/LicenseWebpackPlugin.js
- /Users/lrj/project/fastorder/admin/node_modules/license-webpack-plugin/dist/index.js
- /Users/lrj/project/fastorder/admin/node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js
- /Users/lrj/project/fastorder/admin/node_modules/@angular-devkit/build-angular/src/webpack/configs/index.js
- /Users/lrj/project/fastorder/admin/node_modules/@angular-devkit/build-angular/src/builders/browser/index.js
- /Users/lrj/project/fastorder/admin/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /Users/lrj/project/fastorder/admin/node_modules/@angular-devkit/architect/node/index.js
- /Users/lrj/project/fastorder/admin/node_modules/@angular/cli/models/architect-command.js
- /Users/lrj/project/fastorder/admin/node_modules/@angular/cli/commands/build-impl.js
- /Users/lrj/project/fastorder/admin/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/lrj/project/fastorder/admin/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/lrj/project/fastorder/admin/node_modules/@angular/cli/utilities/json-schema.js
- /Users/lrj/project/fastorder/admin/node_modules/@angular/cli/models/command-runner.js
- /Users/lrj/project/fastorder/admin/node_modules/@angular/cli/lib/cli/index.js
- /Users/lrj/project/fastorder/admin/node_modules/@angular/cli/lib/init.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/lrj/project/fastorder/admin/node_modules/license-webpack-plugin/dist/WebpackAssetManager.js:4:25)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/lrj/project/fastorder/admin/node_modules/license-webpack-plugin/dist/LicenseWebpackPlugin.js:12:29)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
```

### Please provide the environment you discovered this bug in

```true
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2
@angular-devkit/build-angular   13.0.2
@angular-devkit/core            13.0.2
@angular-devkit/schematics      13.0.2
@angular/cli                    13.0.2
@angular/fire                   6.1.5
@schematics/angular             13.0.2
rxjs                            6.5.5
typescript                      4.4.4
```

### Anything else?

Upgrade process seemed to work fine and went without apparent issues.
I've also re-installed all node_modules
