### ISSUE TITLE
Update @angular-devkit node-sass 4.10.0

### ISSUE THREAD

**Issue by Toso82** [angular/angular-cli#12909]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

`
Angular CLI: 7.0.5
Node: 11.1.0
OS: win32 x64
Angular: 7.0.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.5
@angular-devkit/build-angular     0.10.5
@angular-devkit/build-optimizer   0.10.5
@angular-devkit/build-webpack     0.10.5
@angular-devkit/core              7.0.5
@angular-devkit/schematics        7.0.5
@angular/cli                      7.0.5
@angular/flex-layout              7.0.0-beta.19
@angular/pwa                      0.10.5
@ngtools/webpack                  7.0.5
@schematics/angular               7.0.5
@schematics/update                0.10.5
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
`

### Repro steps
`npm update`

### The log given by the failure
> node-sass@4.9.3 postinstall C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\test\t\node_modules\@angular-devkit\build-angular\node_modules\node-sass
> node scripts/build.js

### Desired functionality

Please update dipendency to work well on Node 11.1.0

### Mention any other details that might be useful

Temporary solve install package manual

`npm install node-sass  --save `

**Comment by tatsujb** [comment]
@alan-agius4 hi!

how do I use `dart-sass` with an Angular project ?

I did `npm remove node-sass`, `npm install dart-sass` and then `npm start` but my project doesn't start anymore it says this for every file :  
```
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
```

**Comment by clydin** [comment]
@tatsujb  The project name is `dart-sass` but the official package name is `sass`.

**Comment by n-po** [comment]
I see this fix was merged into master, and npm has the last published date as yesterday, but the package they are distributing does not have the move from 4.9.3 to 4.10.0 for node-sass optional dependency. Perhaps merged to master but not the build branch?
