### ISSUE TITLE
Promise does not work in Angular CLI 1.0.0-beta.16

### ISSUE THREAD

**Issue by duongvu89** [angular/angular-cli#2545]
When I try to use Promise and start app I get this error. IDEA tells that "Corresponding file is not included in tsconfig.json" as well. Please help! Thank you!
> Console log:
ERROR in [default] /Users/duongvu/projects/cosmo/product-designer/frontend2/pd/src/app/services/authentication.service.ts:2:17 
Identifier 'Q' must be imported from a module
ERROR in [default] /Users/duongvu/projects/cosmo/product-designer/frontend2/pd/src/app/services/authentication.service.ts:11:21 
Property 'resolve' does not exist on type '<T>(resolver: (resolve: (val: T | IPromise<T>) => void, reject: (reason: any) => void, notify: (p...'.
ERROR in [default] /Users/duongvu/projects/cosmo/product-designer/frontend2/pd/src/app/services/authentication.service.ts:13:21 
Property 'resolve' does not exist on type '<T>(resolver: (resolve: (val: T | IPromise<T>) => void, reject: (reason: any) => void, notify: (p...'.
> ---------------------------------------------------------------

**Comment by neilhem** [comment]
Looks like support question? Have your tried to ask in [Stackoverflow](http://stackoverflow.com/) ?

**Comment by duongvu89** [comment]
Thank you. I figured it out. Problem came from IDEA settings only.
