### ISSUE TITLE
AOT import * error: ERROR in Illegal state: symbol without members expected, but got

### ISSUE THREAD

**Issue by MaklaCof** [angular/angular-cli#6443]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```
[ I did and search suggested to open new issue.](https://github.com/angular/angular-cli/issues/4821#issuecomment-286188155)

### Versions.
node --version: v7.10.0
npm --version: 4.2.0
window 10 - 64bit

### Repro steps.
Running command: `webpack --env.aot --env.client & webpack --env.aot --env.server` from [aspnetcore-angular2-universal](https://github.com/MarkPieszak/aspnetcore-angular2-universal).
When importing components/services with * I get error if any import also includes *.
**For example this works:**
```
//lazy.module.ts
import * as components from "./components/all";

//all.ts
import {SomeComponent} from "./some";
export {SomeComponent};
```

**And this is not working:**
```
//lazy.module.ts
import * as components from "./components/all";

//all.ts
import * as childs from "./childs";                 //I THINK THIS CAUSE ERROR
import {SomeComponent} from "./some";
export {childs, SomeComponent};

//childs.ts
import {OtherComponent} from "./other";
export {OtherComponent};
```

### The log given by the failure.
`ERROR in Illegal state: symbol without members expected, but got {"filePath":"E:/test-project/trunk/test-project/Client/app/modules/lazy/components/all.ts","name":"childs","members":["OtherComponent"]}.
`
### Desired functionality.
AOT compiles successfully.

### Full error
```
 ERROR in Illegal state: symbol without members expected, but got {"filePath":"E:/test-project/trunk/test-project/Client/app/modules/lazy/components/all.ts","name":"childs","members":["OtherComponent"]}.

    ERROR in E:/test-project/trunk/test-project/Client/main.server.aot.ts (11,42): Cannot find module './ngfactory/app/server-app.module.ngfactory'.

    ERROR in ./Client/main.server.aot.ts
    Module not found: Error: Can't resolve './ngfactory/app/server-app.module.ngfactory' in 'E:\test-project\trunk\test-project\Client'
     @ ./Client/main.server.aot.ts 7:0-87
```

**Comment by delasteve** [comment]
Looking at the repository you linked, I'm sorry, but this issue is not caused by Angular CLI as I don't see the CLI being used anywhere. Please contact the author(s) of the project https://github.com/MarkPieszak/aspnetcore-angular2-universal or file issue on their issue tracker.

**Comment by MaklaCof** [comment]
If it helps I experience another interesting error inside nested lazy module.
```

    ERROR in Unexpected value 'Category in e:/OpPISWeb/trunk/OpPISWeb/Client/app/modules/var-design/modules/admin/components/components.ts' declared by the module 'VarDesignAdminModule in e:/OpPISWeb/trunk/OpPISWeb/Client/app/modules/var-design/modules/admin/admin.module.ts'. Please add a @Pipe/@Directive/@Component annotation.

    ERROR in e:/OpPISWeb/trunk/OpPISWeb/Client/main.server.aot.ts (11,42): Cannot find module './ngfactory/app/server-app.module.ngfactory'.

    ERROR in ./Client/main.server.aot.ts
    Module not found: Error: Can't resolve './ngfactory/app/server-app.module.ngfactory' in 'e:\OpPISWeb\trunk\OpPISWeb\Client'
     @ ./Client/main.server.aot.ts 7:0-87

```
Components.ts:
```
import * as Category from "./category/category";

export { Category };
```

**Comment by mscu** [comment]
same issue here using constants like

```typescript
export const Constants = {
  foo = 'bar'
  // ...
};
```
provided by a shared "util" module and used in various (lazy-loaded) modules, including routing modules

**Comment by sherlock1982** [comment]
Is it the same?

Error: Illegal state: symbol without members expected, but got {"filePath":"skipped/call-history/data/call-history-type.ts","name":"CallHistoryType","members":["AllCalls"]}.

And callhistory-type.ts contains:

    export enum CallHistoryType {
        AllCalls = 0,
        Missed = 1,
        Received = 2,
        Outgoing = 3,
        Abandoned = 4
    }

Appeared when I moved from 4.1.3 to 4.3.1

**Comment by mscu** [comment]
@sherlock1982: yes, i think so, i had/have the same issue after upgrading from 4.1.3 to 4.3

**Comment by rafiwardak2003** [comment]
I tried upgrading from 4.1.3 to 4.3.2, and got this issue. I had to go back to 4.1.3. Mine is caused by re-exporting Enums, but I assume that's the first stop, and then it will complain about all re-exports.

**Comment by brentwilton** [comment]
We encountered the same issue in Angular 4.3.3 when referencing an enum in our NgModule Route data.

Our workaround is to default export the enum, which in our case allows the Angular 4.3.3 build to complete successfully.

**Before (fails on AoT compile):**
```
export enum ExampleEnum {
    foo,
    bar
}
```
```
import { ExampleEnum } from './example.enum.ts';

const exampleRoutes: Routes = [
    {
        path: '',
        component: ExampleComponent,
        data: {
            foo: ExampleEnum.foo
        }
    }
];
```

**After (works on AoT compile):**

```
export enum ExampleEnum {
    foo,
    bar
}

// add a default export of the enum
export default ExampleEnum;
```
```
// import without { }
import ExampleEnum from './example.enum.ts';

const exampleRoutes: Routes = [
    {
        path: '',
        component: ExampleComponent,
        data: {
            foo: ExampleEnum.foo
        }
    }
];
```
We only needed to default export the enums included in the route data

**Comment by mattscu** [comment]
@brentwilton: tried your solution and it compiled with aot, but unfortunately the compiled code had null values while the non aot code worked - so the workaround didn't really work for me :(

(i' not using enums but constants like mentioned above)

**Comment by junglebarry** [comment]
I may be confusing things here, but is this related to https://github.com/angular/angular/issues/18170?

**Comment by GeorgeKnap** [comment]
just getting this error during CLI AOT prod build.
```
ERROR in Error: Illegal state: symbol without members expected, but got {"filePath":"C:/Development/Intens.eCall/trunk/Intens.eCall.Website/src/app/shared/models/roles.enum.ts","name":"Role","members":["eCallUserAdministrator"]}.
    at StaticSymbol.assertNoMembers (C:\Development\Intens.eCall\trunk\Intens.eCall.Website\node_modules\@angular\compiler\bundles\compiler.umd.js:794:19)
    at AotSummaryResolver.resolveSummary (C:\Development\Intens.eCall\trunk\Intens.eCall.Website\node_modules\@angular\compiler\bundles\compiler.umd.js:18948:22)
    at CompileMetadataResolver._loadSummary (C:\Development\Intens.eCall\trunk\Intens.eCall.Website\node_modules\@angular\compiler\bundles\compiler.umd.js:8822:49)
    at CompileMetadataResolver._getEntryComponentMetadata (C:\Development\Intens.eCall\trunk\Intens.eCall.Website\node_modules\@angular\compiler\bundles\compiler.umd.js:9529:31)
    at C:\Development\Intens.eCall\trunk\Intens.eCall.Website\node_modules\@angular\compiler\bundles\compiler.umd.js:9516:31
    at Array.forEach (native)
    at CompileMetadataResolver._getEntryComponentsFromProvider (C:\Development\Intens.eCall\trunk\Intens.eCall.Website\node_modules\@angular\compiler\bundles\compiler.umd.js:9515:30)
    at C:\Development\Intens.eCall\trunk\Intens.eCall.Website\node_modules\@angular\compiler\bundles\compiler.umd.js:9488:83
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (C:\Development\Intens.eCall\trunk\Intens.eCall.Website\node_modules\@angular\compiler\bundles\compiler.umd.js:9451:19)
    at C:\Development\Intens.eCall\trunk\Intens.eCall.Website\node_modules\@angular\compiler\bundles\compiler.umd.js:9453:23
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (C:\Development\Intens.eCall\trunk\Intens.eCall.Website\node_modules\@angular\compiler\bundles\compiler.umd.js:9451:19)
    at C:\Development\Intens.eCall\trunk\Intens.eCall.Website\node_modules\@angular\compiler\bundles\compiler.umd.js:9099:63
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Development\Intens.eCall\trunk\Intens.eCall.Website\node_modules\@angular\compiler\bundles\compiler.umd.js:9090:49)
    at CompileMetadataResolver.getNgModuleSummary (C:\Development\Intens.eCall\trunk\Intens.eCall.Website\node_modules\@angular\compiler\bundles\compiler.umd.js:9035:35)
    at C:\Development\Intens.eCall\trunk\Intens.eCall.Website\node_modules\@angular\compiler\bundles\compiler.umd.js:9105:55
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Development\Intens.eCall\trunk\Intens.eCall.Website\node_modules\@angular\compiler\bundles\compiler.umd.js:9090:49)
    at CompileMetadataResolver.getNgModuleSummary (C:\Development\Intens.eCall\trunk\Intens.eCall.Website\node_modules\@angular\compiler\bundles\compiler.umd.js:9035:35)
    at C:\Development\Intens.eCall\trunk\Intens.eCall.Website\node_modules\@angular\compiler\bundles\compiler.umd.js:9105:55
npm ERR! Windows_NT 10.0.15063
```
at enum: 
```
export enum Role {
    eCallUserAdministrator,
    MSD,
    IVS,
    PSAP
}
```


packages:
```
  "dependencies": {
    "@angular/core": "5.0.0-beta.7",
    "@angular/common": "5.0.0-beta.7",
    "@angular/animations": "5.0.0-beta.7",
    "@angular/platform-browser": "5.0.0-beta.7",
    "@angular/platform-browser-dynamic": "5.0.0-beta.7",
    "@angular/compiler": "5.0.0-beta.7",
    "@angular/flex-layout": "git+https://github.com/angular/flex-layout-builds.git",
    "@angular/forms": "5.0.0-beta.7",
    "@angular/http": "5.0.0-beta.7",
    "@angular/router": "5.0.0-beta.7",
    "@angular/material": "2.0.0-beta.11",
    "@angular/cdk": "2.0.0-beta.11",
    "core-js": "2.4.1",
    "jquery": "3.2.1",
    "rxjs": "5.4.0",
    "zone.js": "0.8.17",
    "servicestack-client": "0.0.39",
    "event-source-polyfill": "0.0.9"
  },
  "devDependencies": {
    "@types/node": "*",
    "@types/lodash": "*",
    "@types/service_worker_api": "*",
    "@types/arcgis-js-api": "4.4.0",
    "@angular/cli": "1.4.4",
    "@angularclass/hmr": "2.1.3",
    "@angular/compiler-cli": "5.0.0-beta.7",
    "@angular/service-worker": "1.0.0-beta.16",
    "codelyzer": "3.2.0",
    "node-sass": "4.5.3",
    "ts-node": "3.3.0",
    "tslint": "5.7.0",
    "typescript": "2.5.3",
    "webpack-bundle-analyzer": "2.9.0"
  }
```

is this a problem related to cli or angular itself?

**Comment by marioese** [comment]
I ran into the exact same problem today, while passing an enum value as route data (similar to what @GeorgeKnap described).

My route example:
`  { path: "item/:itemId", component: ItemComponent, data: { foo: someEnum.EnumValueX } }`

My enum example:
```
  export someEnum {
    _EnumValueX = 0,_
    EnumValueY = 1,
    EnumValueZ = 2
  }
```

In my case however, I managed to get this working by removing the 0 value from my enum:
```
  export someEnum {
    _EnumValueX = 1,_
    EnumValueY = 2,
    EnumValueZ = 3
  }
```

First example fails in AOT build, while the second one succeeds. Though this may not be a solution for everyone, it might be good to know!

**Comment by Vladimex** [comment]
The same problem with enums in my project.
Will it be fixed or I have to remove all enums from the project?

**Comment by MaklaCof** [comment]
@hansl Any progress? It's 5 months. I just upgraded to `angular 4.4.6` and `angular CLI 1.4.9`. The error is still raised.

I have over 300 components and it is becoming a real mess because I can not nest imports into NgModule.
I would really like to do it this way:
```
import * as Containers from "./containers/containers";
@NgModule({
    declarations: [
        AdminComponent,
        Containers.SyncComponent,
        Containers.TagsComponent,
        Containers.DashboardComponent,
        Containers.Tables.TablesComponent,
        Containers.Tables.Translates.TranslateComponent,
        Containers.Tables.Translates.TranslateTranslateComponent,
        Containers.Tables.Countries.CountriesComponent,
        Containers.Tables.Countries.CountryTranslatesComponent,
        Containers.Tables.Settings.SettingsComponent,
        Containers.Tables.PostCodeComponent,
        Containers.Tables.AddressComponent,
        Containers.Tables.Users.UsersComponent,
        Containers.Tables.Users.UserSettingsComponent,
        Containers.Tables.Users.UserFlagsComponent,
        Containers.Tables.Groups.GroupsComponent,
        Containers.Tables.Groups.GroupUsersComponent,
        Containers.Tables.Groups.GroupRightsComponent,
        Containers.Tables.Partners.PartnersComponent,
        Containers.Tables.Partners.PersonsComponent,
        Containers.Tables.Partners.AddressesComponent,

```
and not this:
```
import { SyncComponent } from "./sync/sync.component";
import { TagsComponent } from "./tags/tags.component";
import { DashboardComponent } from "./dashboard/dashboard.component";
import { TablesComponent as TablesTablesComponent } from "./tables.component";
import { AddressComponent as TablesAddressComponent } from "./address/address.component";
import { PostCodeComponent as TablesPostCodeComponent } from "./postcode/postcode.component";
import { CountriesComponent as TablesCountriesCountriesComponent} from "./countries/countries.component";
import { CountryTranslatesComponent as TablesCountriesCountryTranslatesComponent} from "./country-translates/translates.component";
//.....
@NgModule({
    declarations: [
        AdminComponent,
        SyncComponent,
        TagsComponent,
        DashboardComponent,
        TablesTablesComponent,
        ablesTranslatesTranslateComponent,
        TablesTranslatesTranslateTranslateComponent,
        TablesCountriesCountriesComponent,
        TablesCountriesCountryTranslatesComponent,
        TablesSettingsSettingsComponent,
        TablesPostCodeComponent,
        TablesAddressComponent,
        TablesUsersUsersComponent,
        TablesUsersUserSettingsComponent,
        TablesUsersUserFlagsComponent,
        TablesGroupsGroupsComponent,
        TablesGroupsGroupUsersComponent,
        TablesGroupsGroupRightsComponent,
        TablesPartnersPartnersComponent,
        TablesPartnersPersonsComponent,
        TablesPartnersAddressesComponent,

```

**Comment by Sky4CE** [comment]
@MaklaCof , I have same project structure with imports as you have (your Containers), have you manage to work with AOT ?

**Comment by MaklaCof** [comment]
@Sky4CE  No I din't, but this is huge problem for me. I have over 100 containers and component in each lazy loaded module. Aliases in NgModule seems horrible solution. Currently I am not building as AOT, but will need to do something in next month, if @hansl doesn't fix this.
Please, let me know if you found any solution.

**Comment by mgechev** [comment]
Can you still reproduce it with the latest CLI?

**Comment by MaklaCof** [comment]
I am not sure. I restructure my entire project. I couldn't live with that.

**Comment by mgechev** [comment]
If the problem still exists in the latest version of the CLI, please open a new issue following the template and providing a minimal demo where we can reproduce it. Thanks! :-)
