### ISSUE TITLE
Compilation error after upgrading Angular 7 to 13

### ISSUE THREAD

**Issue by kissy0205** [angular/angular-cli#23586]
Hi,

I've followed [this official document to upgrade](https://update.angular.io/) my Angular v.7.x to v13.x. Successfully updated. but when doing `ng serve`, getting below issues. I don't understand the problem even after going through some technical documentation. I need someone to help me on this

**ERROR - 1**

Generating browser application bundles (phase: setup)...(node:8132) UnhandledPromiseRejectionWarning: 
Error: The target entry-point "**@this-is-custom-library/built-with-older-angular-version**" has missing dependencies:
 - @angular/forms/src/directives/control_value_accessor
 - @angular/core/src/type
 
 **tsConfig.json**

```
{
  "extends": "./node_modules/@this-is-custom-library/built-with-older-angular-version/config/tsconfig.base",
  "compilerOptions": {
    "importHelpers": true,
    "outDir": "dist",
    "strictPropertyInitialization": false,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "module": "es2015",
    "baseUrl": "src",
    "skipLibCheck": true
  },
  "angularCompilerOptions": {
    "preserveWhitespaces": "true"
  },
}
```

when i remove the **_"extends": "./node_modules/@this-is-custom-library/built-with-older-angular-version/config/tsconfig.base",_** from tsConfig.json, its compiled and throwing some other error like below.

ERROR- 2

```
 src/app/appComponent.ts:2:58 - error TS2792: Cannot find module '@angular/router'. Did you mean to set the 'moduleResolution' option to 'node', 
 or to add aliases to the 'paths' option?
2 import { ActivatedRoute, NavigationExtras, Router } from '@angular/router';
```

Could someone please help me to understand the issue and share solution for fixing issues?

Thanks Team
                                                       ~~~~~~~~~~~~~~~~~

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
