### ISSUE TITLE
1.6.2+ breaks when using import('module') syntax

### ISSUE THREAD

**Issue by devoto13** [angular/angular-cli#9158]
### Versions
```
Angular CLI: 1.6.3
Node: 8.7.0
OS: darwin x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

* Clone repo https://github.com/devoto13/esnext-repro
* `ng serve --aot`

### Observed behavior

Build fails and TS error is reported:

> ERROR in src/app/app.component.ts(12,5): error TS1323: Dynamic import cannot be used when targeting ECMAScript 2015 modules.

### Desired behavior

No error is reported.

### Mention any other details that might be useful (optional)

This is a regression in 1.6.2. It worked correctly in 1.6.1. I managed to isolate it to this commit: https://github.com/angular/angular-cli/commit/09177d1.

This commit ensured that `forceTsCommonjs` works for AngularCompilerPlugin, but changing `esnext` module format to `commonjs` leads to the above error. Note this only happens with `target=es2015` because `target=es5` treats `import()` as a normal function call (compiler just passes it through) and than it is picked up by Webpack and treated as ESNext import and everything works because of happy coincidence.

But I really think that CLI should not attempt to replace `esnext` with `commonjs` as it is not a drop in replacement as indicated by the error above.

**Comment by admosity** [comment]
I had the same issue, but got past this by setting my module type to `esnext` in src/tsconfig.app.json:

```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "esnext",
    "types": [
      "node"
    ]
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

Using this to conditionally load some polyfills specifically for IE:

```typescript
/**
 * Handling specifically for IE
 **/
async function loadIEPolyfills() {
  await import('./polyfills-ie.browser');
}

const isIE11 = !!(window as any).MSInputMethodContext && !!(document as any).documentMode;

if (isIE11) {
  loadIEPolyfills();
}
```

Everything seems to be working fine so far...

**Comment by devoto13** [comment]
@adomosity Since you polyfill IE you probably have `target=es5`, but this issue only appears with `target=es2015`. I also have `module=esnext` in the `src/tsconfig.app.json` and it doesn't help. See linked reproduction. I think what you have experienced may be a different issue.

I would just wait until the fix PR is merged. Thanks for sharing you workaround anyway :)

**Comment by admosity** [comment]
Yep, you're right. I do have es5 as my target in the parent tsconfig. I did experience an issue when it wasn't set to esnext, but I don't recall what it was...
