### ISSUE TITLE
Cannot find name 'require' after upgrading to cli1.0.0 and Angular4

### ISSUE THREAD

**Issue by xg-wang** [angular/angular-cli#5748]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 7.7.1
os: darwin x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

### Repro steps.
```
ng new newapp
cd newapp
npm install chart.js --save
echo "export const { Chart } = require('chart.js');" >> src/app/chart.loader.ts
ng serve
```

### The log given by the failure.
ERROR in /Users/xgwang/Workspace/playground/newapp/src/app/chart.loader.ts (1,26): Cannot find name 'require'.

### Desired functionality.
In previous version it should work.

Clearly, in `node_modules/@types/node/index.d.ts` there is `declare var require: NodeRequire;`
But I don't understand why it does not compile.

**Comment by demirk4n** [comment]
@xg-wang I had the same error with firebase and the following update worked for me.

```
// const firebase = require('firebase');
import * as firebase from 'firebase';
```

**Comment by xg-wang** [comment]
@demirk4n Thanks, that works. Just confused why require can't do here.

**Comment by xg-wang** [comment]
add
```
"types": [
  "node"
]
```
into 'src/tsconfig.app.json'

**Comment by DenisVuyka** [comment]
No longer helps with 1.1.1

**Comment by larssn** [comment]
Doesn't seem to work in 1.1.3 either.

**Comment by NoNameProvided** [comment]
Setting this in `tsconfig.json` wont help because it's for the ide you use, the config file actually used for compilation is `src/tsconfig.app.json`. Putting

```json
"types": [
      "node"
    ]
```

there solves the problem for me.

**Comment by gubenkovalik** [comment]
SHIT! ANGULAR IS SHIT

**Comment by gajalchouhan** [comment]
please someone help me resolve when I try to install crypto.js. This error comes 
ERROR in /home/gajal/loktra/lms/src/app/login/login.component.ts (117,20): Cannot find name 'require'.
ERROR in /home/gajal/loktra/lms/src/app/login/login.component.ts (118,18): Cannot find name 'require'.
