### ISSUE TITLE
Cannot find module 'exists-sync'

### ISSUE THREAD

**Issue by jvaranam** [angular/angular-cli#1240]
1.  OS Windows 7
2.  node version 5.2.0  npm version 3.5.1
5.  When i try to run the code using ng serve throw error Error:Cannot find module 'exists-sync' at Function.Module._resolveFilename(module.js:327:15).  plz help me to resolve this issue

**Comment by Chyngyz** [comment]
Same problem, Ubuntu 16.04, node v.4.4.6 npm v.2.15.5

**Comment by debapamdas** [comment]
try running npm install in %AppData%\Roaming\npm\node_modules\angular-cli

**Comment by RazaLabs** [comment]
I had the same issue, updated node version and worked fine
```

npm cache clean -f
npm install -g n
n stable
node --version
```

**Comment by hiepxanh** [comment]
thanks god. after 10 hours, Finnaly

you HAVE to run cmd at ADMINTRATOR mode to run "ng new app-name"
finnally I can install it

**Comment by jvaranam** [comment]
When i updated my node to 6.2.2, its start working 

Thanks
